### ISSUE TITLE
Import Paths not working

### ISSUE THREAD

**Issue by squarestar** [leafo/scssphp#104]
When switching from v.04 to v.07, import paths stop working. The output in firebug is identical but the scss_cache folder does not get filled with the full complement of files as per v.04.

I can reproduce this issue on my local setup (WAMP, PHP v5.3.6) and a remote host (LAMP, PHP v5.2.17).

Is there a PHP version requirement for v.07 that might be the cause?

The code I'm using is:

``` php
require '../includes/scssv7.inc.php';
$directory = 'stylesheets/';
scss_server::serveFrom($directory);
```

The results are the same with this code:

``` php
require '../includes/scssv7.inc.php';
$directory = 'stylesheets/';
$scss = new scssc();
$scss->setImportPaths($directory);
$server = new scss_server($directory, null, $scss);
$server->serve();
```

I can switch from scssv4.inc.php to scssv7.inc.php with no other changes to cause the issue.

**Comment by alexol91** [comment]
You need set Import Paths 

http://leafo.net/scssphp/docs/#including
