### ISSUE TITLE
Incompatible units with scssphp

### ISSUE THREAD

**Issue by ConneXNL** [leafo/scssphp#107]
When using the scssphp filter i get the following error when dumping the MopaBootstrapBundle.

[Exception]
Incompatible units: "%" and "in".: failed at *margin-left: $fluidGridGutte
rWidth - (.5 / $gridRowWidth * 100px * 1%); vendor/
mopa/bootstrap-bundle/Mopa/Bundle/BootstrapBundle/Resources/public/sass/../
../bootstrap-sass/lib/_mixins.scss on line 621

**Comment by robocoder** [comment]
Branch: `wip/incompatible-units`
Status:
* [x] refactoring array('number', ...' to Node\Number
* [ ] units conversion

**Comment by robocoder** [comment]
note to self: abstractions merged into master; wip branch needs to be rebased
