### ISSUE TITLE
source-map support

### ISSUE THREAD

**Issue by edwinveldhuizen** [leafo/scssphp#135]
There are currently two ways how you can debug sass quite easily:
-  use the option --line-numbers which parses the line-numbers of the original files as comments in the output
- use the option --source-map with the pre-releases of sass which creates a source-map file next to the css so you can debug it really easily with Crome Dev Tools

As far as I know both of the above features aren't implemented in scssphp, but it would be a great addition! Now it's really hard to track where that rule was written.

**Comment by Screenchecker** [comment]
I've forked this project and added the line number feature into the develop branch:
https://github.com/Screenchecker/scssphp/tree/develop#optional-output-scss-line-numbers

**Comment by robocoder** [comment]
Branch: `wip/source-maps`
Status:
* [x] Base64 and Base64VLQ classes
* [ ] Generator
* [ ] MappingList ?
* [ ] Util ?
* [ ] bin/pscss
* [ ] Compiler integration
* [ ] Server integration

**Comment by robocoder** [comment]
(p.s. --line-numbers and --debug-info are available in the latest version of scssphp)

**Comment by acasar** [comment]
@robocoder Any update on source maps? Or do you maybe know about any Chrome plugin that would work with --line-numbers?

Thanks a lot!

**Comment by robocoder** [comment]
@acasar Support for sourcemaps is a work-in-progress being juggled with other issues (eg selectors and scope). Sorry, I don't know of any Chrome plugins that support --line-numbers.

**Comment by smachi** [comment]
+1 for this

**Comment by riverofjanuary** [comment]
Please please add sourcemaps - it is impossible to do live debug (remote) without it.

**Comment by wojtas** [comment]
@robocoder Could you share your current code for source maps' generation? I desperately need them, maybe I could pick up where you left and finish that feature?

**Comment by robocoder** [comment]
@wojtas: there's not much here: https://github.com/leafo/scssphp/tree/wip/source-maps

**Comment by nickleus** [comment]
+1 for source maps

**Comment by CamilleBouliere** [comment]
+1 for source maps

**Comment by acasar** [comment]
If anyone is interested - in my project I managed to quite easily extract line number comments to a real source map using this package: https://github.com/koala-framework/sourcemaps

@robocoder Maybe if we add it as a dependency it would be much easier to implement source maps natively?

**Comment by robocoder** [comment]
Feel free to submit a PR.

**Comment by SimonEast** [comment]
+1 for source-maps. Has been over a year since it being a WIP. Would love to see it eventuate, but not sure if it's likely any time soon?

**Comment by dstorozhuk** [comment]
So here is my gist:
https://gist.github.com/dstorozhuk/e90e6b151129f5bb9d20e871e0137d38

The code extends the Leafo\ScssPhp\Server. The most important methods for generating maps is `CssServer::compile()` and `CssServer::generateMap()`.

**Comment by s4msung** [comment]
+1 for source maps

**Comment by NicolaF** [comment]
See https://github.com/leafo/scssphp/pull/541

**Comment by riverofjanuary** [comment]
@NicolaF, i'll go ahead and try that commit to see how it works. Any special config or it just "works"?

**Comment by NicolaF** [comment]
@riverofjanuary It just works ;-)
`$compiler->setSourceMap(Compiler::SOURCE_MAP_INLINE);
$compiler->setSourceMapOptions([
    'sourceMapBasepath' =>'<your root directory>'
    'sourceMapRootpath' => '<whatever url works for serving the original files so that your browser can display the sources>'
]`

The option names are a bit misleading, but I kepts the names from oyejorge/less.php, for those of us who are transitioning to bootstrap 4 and used oyejorge/less.php with the less version of bootstrap 3.

**Comment by riverofjanuary** [comment]
Thanks. I see I cant actually pull that SHA because it hasn't been committed, but I'll wait to see what the dev does.
