### ISSUE TITLE
What about SCSS 3.3?

### ISSUE THREAD

**Issue by jslegers** [leafo/scssphp#139]
I need some SCSS 3.3 features. I did install the official 3.3 prerelease of Sass, but I feel more comfortable in a PHP environment than in a Ruby environment.

I wonder if there's any somewhat stable prerelease of Scssphp that implements new 3.3 features or if you have any plans to support SCSS 3.3....

**Comment by YamiOdymel** [comment]
Still waiting for the 3.3

**Comment by torkiljohnsen** [comment]
I switched to libsass (locally, with Gulp) and sassc on my server, and I never looked back. Better feature parity with Sass, and a fraction of the compile time.

**Comment by GabrielGil** [comment]
Def right @torkiljohnsen!

**Comment by parhumm** [comment]
I really need this because  I compile codes on server with https://github.com/reyhoun/sass-watcher . scssphp use PHP and every server support PHP easily.

**Comment by jslegers** [comment]
@torkiljohnsen :

I don't think libsass can be used on servers that have `shell_exec` disabled, which is a necessary requirement for the kind of projects I'm working on.

**Comment by torkiljohnsen** [comment]
I feel for you. On a large project my compile time was reduced by over 96% after switching to sassc, if memory serves.

**Comment by YamiOdymel** [comment]
Just saying that I'm decide to use `exec()` to instead (If your server supported)

And you'll need to install sass command-line

    /** Compile by the SASS command-line can be more faster */
    exec('sass ' . $SCSS_PATH . ' 2>&1', $Output, $Code);
            
    /** Convert the output array to the string */
    $Output = implode("\n", $Output);
            
    /** Error occurred if the status code is not zero */
    if($Code != 0)
        exit($Output);

    /** Compiled result */
    exit('This is SCSS: ' . $Output);

**Comment by whitnelson** [comment]
+1 for Bourbon support.

**Comment by robocoder** [comment]
Closing this ticket as the question has been answered, and other tickets have been created for the specific scss 3.x features that are missing.

**Comment by jslegers** [comment]
@robocoder :

So what's the progress on the implementation of missing Sass 3.3 and 3.4 features? Are they coming to this library in the forseeable future?

**Comment by robocoder** [comment]
Thanks to some PRs, we are making progress once again. Over the past few months:
* v0.1.2 added support for 3.3's map type and map functions
* v0.1.4 added 3.3's string functions
* v0.1.6 added !global and pulled in the latest scss_test.rb for compatibility testing
* v0.1.7 added --line-numbers and --debug-info

So, I'm optimistic about the library.
* support for 3.3's @extend !optional and @at-root is missing; hopefully, we'll address all the @extend-related compatibility issues at that time.
* 3.3's source maps is closer to realization after the internal changes to support --line-numbers and --debug-info
*and wrt built-in functions introduced in 3.3/3.4, there are 6 remaining to implement
