### ISSUE TITLE
Issue with lists

### ISSUE THREAD

**Issue by muxahuk** [leafo/scssphp#146]
Hello, playing around with you'r script and added compass to it..
Problem i have:
``` TEXT
Parse error: parse error: failed at `$browser-minimum-versions: (
` C:\OpenServer\domains\m7.loc/wp-content/themes/m7/scss\screen.scss on line 7
```
and here's what i'v got in file
``` SCSS
$browser-minimum-versions: (
  'chrome':  null,
  'firefox': null,
  'ie':      null,
  'safari':  null,
  'opera':   null
) !default;
```
I'm not doing anything with it, just these code..
Any help why is these happaning and how to solve ?

**Comment by robocoder** [comment]
v0.1.3 adds map support, so this example no longer throws a parse error.  list support is still on the todo list, so closing this specific issue
