### ISSUE TITLE
[feature] create foo.css from foo.scss, not hash-string-filename.css

### ISSUE THREAD

**Issue by panique** [leafo/scssphp#148]
Maybe I'm completely wrong here, but scssphp creates something like d36a5eecd10affc68dd87e4c2486469b.css from a test.scss, not test.css! Why is it not possible to get a simple test.css, like every other SASS compiler does ? Or - let me reform the question - how can we create test.css from test.scss ?

**This is an absolute must-have, and to be honest that's the basic use-case of SASS.**
Your LESS-compiler does exactly that btw ($less->checkedCompile("input.less", "output.css");), excellent way, but scssphp is not able. I'm confused.

**Comment by robocoder** [comment]
Cherry-picked into master
