### ISSUE TITLE
linear-gradient() (Bourbon)

### ISSUE THREAD

**Issue by dovy** [leafo/scssphp#156]
scssphp FTW. Love you guys. Great work.

I am using the newest version of scssphp, even tried some dev branches. I am also using bourbon as a mix-in library.

I am getting two errors that I can get around, but would love to see fixed instead.

For some reason, a nested translate within a transform fails. Example: 
```
@include transform(translate(0px, -50%));
```

So I have to do this manually:
```
-webkit-transform: translate(0px, -50%);
-moz-transform: translate(0px, -50%);
-ms-transform: translate(0px, -50%);
-o-transform: translate(0px, -50%);
transform: translate(0px, -50%);
```

Also when running the following line:
@include background-image(linear-gradient($gradient-primary, $gradient-secondary), url('../img/pattern.png'), url('../img/dark_shore.jpg'));

The URL is ignored, so I have to manually run:

```
background-image: -webkit-linear-gradient( 
	$gradient-primary, $gradient-secondary ), 
 	url("../img/pattern.png"), 
 	url("../img/dark_shore.jpg"
);

background-image: linear-gradient( 
	$gradient-primary, 
 	$gradient-secondary ), 
 	url("../img/pattern.png"), 
 	url("../img/dark_shore.jpg"
 	298
);
```

or the background image will not show.

If you fix these two issues you would make my life perfect. I love you guys.

**Comment by robocoder** [comment]
@robocoder: test to see if this is fixed in v0.1.4

**Comment by robocoder** [comment]
The nested transform(translate() is working in the latest version of scssphp, but the background-image(linear-gradient()) is borked.
```
.background2 {
  background-image: , , ;
  background-image: , , ; }
```

**Comment by robocoder** [comment]
Fixed in master
