### ISSUE TITLE
Problems with maps?

### ISSUE THREAD

**Issue by jameslomas** [leafo/scssphp#170]
I'm trying to use Gridle{.scss} with scssphp (I'm new to this - please let me know if that's just not going to work) and running into some problems:

PHP file called 'style.php', contains just this:

<?php
require "scssphp/scss.inc.php";
scss_server::serveFrom("sass");

Which first loads sass/_settings.scss, which looks like:
// import gridle
@import "gridle/gridle";

// setting up the grid
@include gridle_setup( (
    context : 12,
    gutter-width : 20px,
    direction : rtl,
    // etc...
) );
and then some more stuff (irrelevant).

The @import "gridle/gridle" seems to go fine. I get the error here:
Parse error: parse error: failed at `@include gridle_setup( (
` sass/_settings.scss on line 5

The interesting thing is that the error also appears when using really simple syntax in the normal compiler:
echo $scss->compile('
$settings: (bla: 1, foo: 2);
');

parse error: failed at `$settings: (bla: 1, foo: 2);` line: 2' in scss.inc.php on line 3966

I've tested with PHPUnit (whatever that does - I have no idea tbh) with no errors.

Thanks in advance guys! Am I going to have to use ruby for this? :(

**Comment by Jeff-Russ** [comment]
Does scssphp still not support maps?
