### ISSUE TITLE
Combine nested media queries on compilation

### ISSUE THREAD

**Issue by melat0nin** [leafo/scssphp#175]
Would it be possible to combine nested MQs on compilation to reduce filesize? At the moment scss-php (and I believe SASS in general) will output this:

```
@media (max-width: 767px) {
  header #logo {
    background: black; } }
@media (max-width: 767px) {
  header {
    width: 90%; } }
```

...instead of:

```
@media (max-width: 767px) {
  header #logo {
    background: black; } 
  header {
    width: 90%; } }
```

The duplication of code can make for large files if there's a lot of SASS.

**Comment by robocoder** [comment]
Closing this under the sass community guidelines (until there's a reference implementation in ruby sass).
