### ISSUE TITLE
foundation 5 compilation error with operations

### ISSUE THREAD

**Issue by berndhofer** [leafo/scssphp#186]
@robocoder @kadaj- foundation 5 uses some operations like this example. when using phpscss the following css error occurs:

![f5-menu-icon](https://cloud.githubusercontent.com/assets/4447150/3811998/9b2665f4-1ca5-11e4-9727-c5afccbf3b43.png)

scss example
```
$width: 20px;
.test {
 margin-top: -$width/2;
}
```

phpscss output
```
.test { margin-top: -20px/2; }
```

http://sassmeister.com/gist/73beed80d1e9916266ab
```
.test { margin-top: -10px; }
```

**Comment by robocoder** [comment]
This problem is fixed in the develop branch.
```
$width: 20px;
.test {
 margin-top: -$width/2;
}
```

**Comment by robocoder** [comment]
Closing.  The other issues appear to be related to #107.
