### ISSUE TITLE
SassScript maps

### ISSUE THREAD

**Issue by robocoder** [leafo/scssphp#192]
See sass 3.3.0 [release notes](http://sass-lang.com/documentation/file.SASS_CHANGELOG.html).

The following map related functions are also tracked in #191:
* [ ] map_get(map, key)
* [ ] map_has_key(map, key)
* [ ] map_keys(map)
* [ ] map_merge(map1, map2)
* [ ] map_remove(map, key)
* [ ] map_values(map)

**Comment by g105b** [comment]
Any news on this? Would be great to see this implemented.

**Comment by grilly86** [comment]
i am also waiting for this! is there a plan to support those some day?

**Comment by robocoder** [comment]
Merged.  Tagged master as v0.1.3
