### ISSUE TITLE
@at-root support

### ISSUE THREAD

**Issue by robocoder** [leafo/scssphp#193]
See sass 3.3.0 [release notes](http://sass-lang.com/documentation/file.SASS_CHANGELOG.html).

Nice summary: http://sassbreak.com/getting-back-to-our-roots/

**Comment by vinigarcia87** [comment]
Any news on this, guys?
can't compile bootstrap 3.3.5 without @at-root. :S

**Comment by robocoder** [comment]
Not yet.

**Comment by robocoder** [comment]
Branch: `wip/at-root`
Status:
* [x] Parser.php: parses `@at-root [optional-selector-list] [(without: ...)] [(with: ...)]`
* [ ] Compiler.php: naively compiles block at the root level; needs to handle the selector list and with/without options; see compileMedia() for example of hoisting

**Comment by corradomatt** [comment]
Yes! This will be awesome! I posted a bounty for it, please join in if you love this project as much as I do - https://www.bountysource.com/issues/3632927-at-root-support

**Comment by robocoder** [comment]
Further improvements in #359.

**Comment by a-westbrook** [comment]
Cannot pass "&" after @at-root 
Returns empty char
