### ISSUE TITLE
support for protocol-relative paths

### ISSUE THREAD

**Issue by antiphp** [leafo/scssphp#203]
works (http):

	@CHARSET "UTF-8";
	@import url(http://example.org/some.css);
	$bgColor: red;
	body {
		background: $bgColor;
	}

works (https):

	@CHARSET "UTF-8";
	@import url(https://example.org/some.css);
	$bgColor: red;
	body {
		background: $bgColor;
	}

does not work (//):

	@CHARSET "UTF-8";
	@import url(//example.org/some.css);
	$bgColor: red;
	body {
		background: $bgColor;
	}

output instead:

	@charset "UTF-8";
	@import url(//example.org/some.css);
	$bgColor: red;
	body {
	  background: ;
	}

**Comment by robocoder** [comment]
scssphp and libsass appear to both treat `//example.org/some.css);` as a comment.
