### ISSUE TITLE
setVariables() - Override variables with php

### ISSUE THREAD

**Issue by hocubo** [leafo/scssphp#206]
Hi,

I created sample scss file for testing and defined variable in this file ( $color ) 

$color: #FFFFFF;
.test-div { color:$color; }

And, I have written code as follows in php side. Basically, I want to override $color variables in php side. How can i do it?

$scss = new scssc();
$scss->setVariables(array(
  "color" => "#000000"
));
$scss->compile(...);

**Comment by mahagr** [comment]
you can use scss !default in your scss file allowing variables to override your default values.

**Comment by robocoder** [comment]
scssphp master now contains the *_exist() functions and !global from sass 3.3.

**Comment by mahagr** [comment]
Nice work! I see that you've been more active lately. :) Also saw the change for variable_exists() and the test case for it.

Unrelated question: is there any ETA for getting source maps support in from the other branches?

**Comment by robocoder** [comment]
There's just the development branches for `line-numbers-v2` and `experiment-line-numbers`. One of these will be mainlined before we tackle source maps.

**Comment by mahagr** [comment]
I'm still learning how the code works, but slowly getting there..

PS: I'm really hoping that you would change compileValue() to be public as otherwise it is really hard to handle SCSS parameters in external functions.

https://github.com/gantry/gantry5/blob/develop/src/classes/Gantry/Component/Stylesheet/Scss/Compiler.php#L48-L61

**Comment by robocoder** [comment]
done; see 3735be9

**Comment by mahagr** [comment]
Cool, that will allow me to compile parameter back to string in case if I need to make some string comparisions/operators with it. :)

**Comment by padalec** [comment]
Hi there,
what I have to do for replace sass variable defined in _varibale.scss file to defined in php? I can't use !default because I use bootsrap and if I add !default to my variable letter isn't changed.

**Comment by robocoder** [comment]
Sorry @padalec ... it's missing from the docs http://leafo.github.io/scssphp/docs/

Basically, it's something along the lines of:

```
use Leafo\ScssPhp\Compiler;

$scss = new Compiler();

$scss->setVariables(array(
    'enable-flex' => true,
));

echo $scss->compile('
  @import "bootstrap.scss";
   ...
');
```

**Comment by padalec** [comment]
OK many thanks!
