### ISSUE TITLE
Divide by zero error

### ISSUE THREAD

**Issue by Colir** [leafo/scssphp#207]
Hi. i encounter an error when doing this
https://gist.github.com/colir/07500ba575f027373556

This return me a php error 'divide by zero'.

but if i use this (without the $modColor variable) it work :
@mixin block-color($color){
@for $i from 1 through 15 {
$pc : (100/15) * $i;

.color-#{$i}{
background-color:lighten($color,$pc * 1%);
transition:all 0.15s linear;
&:hover{background-color: darken($color,10%);}
}
 
}

When dig in it, it's appear that when $pc is up to 60%, this send error

To be clear this sen me an error
$var : lighten($color,10%);

And this not :
backgrounsd-color:lighten($color,10%);

Can you please help me ?
thanks

**Comment by robocoder** [comment]
The current develop branch is compatible with the libsass 3.2.4 output. For some reason, ruby sass computes the background-color differently. Closing for now.
