### ISSUE TITLE
Include/Enable Globbing?

### ISSUE THREAD

**Issue by katrinkerber** [leafo/scssphp#210]
Is there a way to include [Sass Globbing](https://github.com/chriseppstein/sass-globbing) with this script?

If so, would someone be kind enough to point out how best to do that?

Thank you :)

**Comment by robocoder** [comment]
A glob package:  https://github.com/webmozart/glob

Still have to figure out integrating it into scssphp core or as a plugin.

**Comment by robocoder** [comment]
Closing this under the sass community guidelines (until there is a reference implementation in ruby sass).

**Comment by nsrosenqvist** [comment]
Any chance of this being reopened? gulp-sass supports globbing and sassc is working on an implementation. It would be a great feature!
