### ISSUE TITLE
Double compile time after upgrading from 0.0.14 to 0.1.1

### ISSUE THREAD

**Issue by torkiljohnsen** [leafo/scssphp#216]
I just have to say that the compile time is now extremely slow. It was already a whole lot slower than libSass on version v0.0.14, but I think the scssphp compile time doubled after I upgraded to v0.1.1.

I haven't done any profiling yet, but I just wanted to hear if anyone was experiencing the same?

**Comment by robocoder** [comment]
scssphp will always be slower than libsass. (I assume you've already made the switch.) That said, scssphp has been getting slower (and it was already slower than ruby scss). Since the focus continues to be compatibility rather than speed, I'm closing this ticket.
