### ISSUE TITLE
comments are inserted in the previous section

### ISSUE THREAD

**Issue by mokraemer** [leafo/scssphp#227]
See the following example

.sidebar h3 {
 padding-left: 22px;
 background-repeat: no-repeat;
 background-position: left center;
}

 /* ------ products -------- */
 .product-list {
 margin-top: 0px;
 }

results in
 .sidebar h3 {
   padding-left: 22px;
   background-repeat: no-repeat;
   background-position: left center;
   /* ------ products -------- */ }

 .product-list {
   margin-top: 0px; }

**Comment by Screenchecker** [comment]
Same issue here!

I'm trying to implement automated line comments for debugging, but scssphp keeps moving them within the generated css file.

**Comment by robocoder** [comment]
You don't appear to be using the latest version of scssphp. On the master and develop branches, I get:
```
.sidebar h3 {
  padding-left: 22px;
  background-repeat: no-repeat;
  background-position: left center; }
/* ------ products -------- */
.product-list {
  margin-top: 0px; }
```

**Comment by mokraemer** [comment]
I'm using the latest "stable" version, which can be downloaded.
It's not very common to use the unreleased versions.

**Comment by Screenchecker** [comment]
your given example is working fine (i'm using the latest master version).

if your using nested rules on the other hand, you'll run into your described problem. See  [issue #228] (https://github.com/leafo/scssphp/issues/228)
