### ISSUE TITLE
Issue compiling a float number

### ISSUE THREAD

**Issue by Lors** [leafo/scssphp#236]
Hi, Im trying to compile a float in sass.

I need the whole set of numbers from this equation: ( 100% / 3)

the result should be: 
33.3333333333%

but instead, the compiler only displays ( missing five numbers "3" ) : 
33.33333%

I tried using this function: **abs( $value )**

But it doesn't display the **COMPLETE SET OF NUMBERS** and is really important to have it all.

Any help with this would be really appreciated,

Thanks

Lors

**Comment by howard** [comment]
Values are rounded to a certain level of precision, which is `5` by default. You can change that using `Compiler::setNumberPrecision()`.

**Comment by robocoder** [comment]
You might want to look at #239.
