### ISSUE TITLE
Minimum Requirements Error

### ISSUE THREAD

**Issue by varun21** [leafo/scssphp#245]
I'm on PHP 5.2.17

And it throws an error. Is there a minimum required version of PHP?

Warning: include(__DIR__/src/Colors.php) [function.include]: failed to open stream: No such file or directory in /home/webmaster/public_html/website/lib/scssphp/scss.inc.php on line 2

Warning: include(__DIR__/src/Colors.php) [function.include]: failed to open stream: No such file or directory in /home/webmaster/public_html/website/lib/scssphp/scss.inc.php on line 2

Warning: include() [function.include]: Failed opening '__DIR__/src/Colors.php' for inclusion (include_path='.:/usr/lib/php:/usr/local/lib/php') in /home/webmaster/public_html/website/lib/scssphp/scss.inc.php on line 2

**Comment by robocoder** [comment]
Requires php 5.3 and above.

https://github.com/leafo/scssphp/blob/master/composer.json#L26
