### ISSUE TITLE
Errors not being displayed

### ISSUE THREAD

**Issue by melat0nin** [leafo/scssphp#249]
I've just transferred my site running v0.1.1 from a public CentOS Apache server to a local server (Ubuntu, Apache 2.4, php 5.5) but I'm not seeing any errors being thrown -- the output is just blank, making debugging a pain. Not even anything in Apache's error log. On the original server exceptions were displayed as expected.

Is there anything environment-specific about error reporting? PHP's error reporting is working for other purposes so I'm assuming it's not that, but scssphp's errors are self-reporting anyway, AFAIK.

**Comment by robocoder** [comment]
If you look at bin/pscss, it uses error_reporting(E_ALL).  Anywhere else, it uses your system's default config.  You can paste ```<?php phpinfo(); ?>``` into a file and load it from your browser to see what your mod php settings are.  (e.g., look for error_reporting and display_errors.)
