### ISSUE TITLE
Are string functions supported?

### ISSUE THREAD

**Issue by grilly86** [leafo/scssphp#250]
I just tried to do a `str-slice($color,1)` but it won't compile to anything other than `str-slice(#f00,1)`

Should the [string functions](http://sass-lang.com/documentation/Sass/Script/Functions.html) already work or does anybody have an idea what i'm doing wrong?

**Comment by vita10gy** [comment]
It doesn't look like it, no.

**Comment by robocoder** [comment]
No.  See #191
