### ISSUE TITLE
parse error

### ISSUE THREAD

**Issue by standus** [leafo/scssphp#253]
this is my example:
// Variable Definitions

$page-width:    800px
$sidebar-width: 200px
$primary-color: #eeeeee

used code:
<?php
require "scssphp/scss.inc.php";
$scss = new scssc();
$scss->setImportPaths("assets/stylesheets/");
// will search for `assets/stylesheets/mixins.scss'
echo $scss->compile('@import "mixins.scss"');

and got error:
parse error: failed at `$page-width: 800px `
Parser.php:1698
on line:
if ($this->count != strlen($this->buffer)) {
    $this->throwParseError();
}
where $this->count is 27
and strlen($this->buffer) is 98.
What is wrong?
I tried remove commented text but same error.

**Comment by okj579** [comment]
It looks like you forgot semicolons.

**Comment by standus** [comment]
You right. Thank you. 
I have another questions about variables. In less.php exists option to parse variables, here is it over fedined function. Is it possible do it more universaly?
