### ISSUE TITLE
Parse error 

### ISSUE THREAD

**Issue by Zutatensuppe** [leafo/scssphp#255]
Getting parse error for input: %#{$name}-#{$breakpoint} { @content } (I think at the percentage sign)

**Comment by robocoder** [comment]
Version? master branch? or develop branch?

**Comment by robocoder** [comment]
Appears to have been fixed on the develop branch.

**Comment by robocoder** [comment]
```
$name: test;
$breakpoint: 300;

%#{$name}-#{$breakpoint} {
  color: red;
}

div {
  @extend %#{$name}-#{$breakpoint};
}
```

output:
```
div {
  color: red; }
```

**Comment by robocoder** [comment]
The fix is now on the master branch.
