### ISSUE TITLE
disable CALC() value

### ISSUE THREAD

**Issue by tomas-kadlec** [leafo/scssphp#256]
Is there any chance to disable compiling calc() value?
I need to pass the expression into the browser.

Source and also requested output (scss file):
element {left:calc(50% - 150px);}

But compiler outputs:
element {left:calc(-100%)}

I need to keep that expression untouched, in order to be compiled by browser. Quotation doesn't help.

**Comment by robocoder** [comment]
TL;DR: Yes, but blocked by another bug.

The calc() function is experimental, and unsupported/buggy in some browsers. As such, it's usually used in conjunction with a fallback. However, there's an outstanding bug in scssphp where duplicate properties may be dropped, rendering the aforementioned fallback inoperable.

**Comment by robocoder** [comment]
BTW your example works correctly in the latest version 0.1.5.

I'm closing this issue as the duplicate property bug is reported elsewhere.
