### ISSUE TITLE
Division by zero

### ISSUE THREAD

**Issue by michanismus** [leafo/scssphp#260]
I am trying to compile Bootstrap with scssphp. The Compiler throws an "Division by zero" exception in function opDivNumberNumber($left, $right), $left[1] and $right[1] having value "0".
I dont know if it is scss file related or scssphp but anyway, there should be a check to avoid a division by zero.

I am using https://github.com/twbs/bootstrap-sass library and the following statement causes the exception:

File: assets/stylesheets/bootstrap/_utilities.scss
Line: 21-23
Code:

.text-hide {
  @include text-hide;
}

mixin:
@mixin hide-text() {
  font: 0/0 a;
  color: transparent;
  text-shadow: none;
  background-color: transparent;
  border: 0;
}

**Comment by michanismus** [comment]
Ok its is scss file related "font 0/0 a" but there should be a test for division by zero.

**Comment by michanismus** [comment]
To throw an exception maybe is not the best solution. What do you think about just returning $left[1] and skip division.

**Comment by robocoder** [comment]
Handling the "font-size / line-height" syntax can't be fixed here in opDivNumberNumber.

**Comment by arekf** [comment]
Hi,

I'm using version 0.3.3 and it still throws an exception (in the same Bootstrap file as in the issue). Has it been fixed? Is there any way to workaround this?

Thanks.

**Comment by robocoder** [comment]
Try the master branch. It's not 100% compatible with ruby scss in that scssphp never outputs NaN for some inputs.

**Comment by arekf** [comment]
Much thanks, works great now! :+1:

**Comment by arekf** [comment]
Sorry, looks like there's still something wrong going on in here. Here's the stacktrace:
http://pastebin.com/8G9mfMyj

**Comment by robocoder** [comment]
@arekf please open a new issue; some sample scss would help to troubleshoot
