### ISSUE TITLE
Outputting CSS From The Main style.scss file.

### ISSUE THREAD

**Issue by JakeHenshall** [leafo/scssphp#263]
Hi,

I'm trying to use this within side of WordPress. Ive included the latest version of SCSSPHP and WordPress is at 4.2.2.

Im trying to get the scss_server function to work so it will automatically compile the SCSS into CSS if any values have been changed in any SCSS files.

1. Im using the Theme Customizer to change things like the background colour and Text size etc... how would i put those values from the theme customizer into the SCSS files ready to be compiled by SCSSPHP if there is a change in said file.

2. Can i create a style.css file that wont be cached and include the values from the .scss file into the newly created .scss file.

Any help would be much appreciated,

Thanks.

**Comment by robocoder** [comment]
1. you have a variety of options here. Some simple ones:

a. write those settings to a .scss file that is imported your theme .scss, or

b. use setVariables() to pass those settings to scssphp 

In both cases, call $server->compileFile('your theme.scss', 'your theme.css').  And let the web server serve the generated .css file directly.

2. No.

**Comment by JakeHenshall** [comment]
Hi robocoder,

thanks for the reply, i've now got it working,

1. Would I use setVariables() in my style.php file? if so what would the syntax be?

Thanks.

**Comment by robocoder** [comment]
setVariables() takes a map, e.g.,
```
$server->set variables(array(
    'color' => 'red',
    'height' => '10px',
));
```

which would be equivalent to this in scss:
```
$color: red;
$width: 10px;
```

**Comment by JakeHenshall** [comment]
Thanks again for the reply,

i don't know how much you know about WordPress, but its worth a shot.

From the theme customizer you will use get_theme_mod function to grab the value from the theme customizer and use it in any file.

the 2 questions i have are:

1. How can i get the value from the theme customizer using get_theme_customizer and put the value within side of a .scss file, which will be updated?

2. How can i specify a value to go into a certain .scss file.

My main scss file is style.scss which has alot of partials like below:

    @import "variables-site/variables-site";
    @import "mixins/mixins-master";

    /*--------------------------------------------------------------
    # Normalize
    --------------------------------------------------------------*/
    @import "normalize";

Say that i need to put a value inside of mixins-master how can i specify the value to put inside of there?

Thanks

**Comment by JakeHenshall** [comment]
Hi,

i'm using this, is there any reason that it throwing back a 500 Internal Server error:

<?php

class Aristath_Dynamic_CSS {

    public $stylesheet_id;

    public function __construct() {
        add_action( 'customize_save_after', array( $this, 'make_css' ) );
    }

    /**
     * Enqueue the dynamic CSS.
     */
    public function enqueue_dynamic_css() {
        wp_enqueue_style( 'dynamic-css', $this->file( 'uri' ) );
    }

    public function make_css() {

        global $wp_filesystem;

        // Initialize the Wordpress filesystem.
        if ( empty( $wp_filesystem ) ) {
            require_once( ABSPATH . '/wp-admin/includes/file.php' );
            WP_Filesystem();
        }

        $content = "/********* Compiled - Do not edit *********/\n" . $this->compile_scss() );

        // Take care of domain mapping
        if ( defined( 'DOMAIN_MAPPING' ) && DOMAIN_MAPPING ) {

            if ( function_exists( 'domain_mapping_siteurl' ) && function_exists( 'get_original_url' ) ) {

                $mapped_domain   = domain_mapping_siteurl( false );
                $mapped_domain   = str_replace( 'https://', '//', $domain_mapping );
                $mapped_domain   = str_replace( 'http://', '//', $mapped_domain );

                $original_domain = get_original_url( 'siteurl' );
                $original_domain = str_replace( 'https://', '//', $original_domain );
                $original_domain = str_replace( 'http://', '//', $original_domain );

                $content = str_replace( $original_domain, $mapped_domain, $content );

            }

        }

        // Strip protocols
        $content = str_replace( 'https://', '//', $content );
        $content = str_replace( 'http://', '//', $content );

        if ( is_writable( $this->file( 'path' ) ) || ( ! file_exists( $this->file( 'path' ) ) && is_writable( dirname( $this->file( 'path' ) ) ) ) ) {

            if ( ! $wp_filesystem->put_contents( $this->file( 'path' ), $content, FS_CHMOD_FILE ) ) {

                // Fail!
                return false;

            }

        }

    }


    /*
     * Determines if the CSS file is writable.
     */
    public function can_write() {

        global $blog_id;

        // Get the upload directory for this site.
        $upload_dir = wp_upload_dir();
        // If this is a multisite installation, append the blogid to the filename
        $blog_id = ( is_multisite() && $blog_id > 1 ) ? '_blog-' . $blog_id : null;

        $file_name   = '/dynamic-css' . $blog_id . '.css';
        $folder_path = $upload_dir['basedir'] . DIRECTORY_SEPARATOR . 'dynamic-styles';

        // Does the folder exist?
        if ( file_exists( $folder_path ) ) {
            // Folder exists, but is the folder writable?
            if ( ! is_writable( $folder_path ) ) {
                // Folder is not writable.
                // Does the file exist?
                if ( ! file_exists( $folder_path . $file_name ) ) {
                    // File does not exist, therefore it can't be created
                    // since the parent folder is not writable.
                    return false;
                } else {
                    // File exists, but is it writable?
                    if ( ! is_writable( $folder_path . $file_name ) ) {
                        // Nope, it's not writable.
                        return false;
                    }
                }
            } else {
                // The folder is writable.
                // Does the file exist?
                if ( file_exists( $folder_path . $file_name ) ) {
                    // File exists.
                    // Is it writable?
                    if ( ! is_writable( $folder_path . $file_name ) ) {
                        // Nope, it's not writable
                        return false;
                    }
                }
            }
        } else {
            // Can we create the folder?
            // returns true if yes and false if not.
            return wp_mkdir_p( $folder_path );
        }

        // all is well!
        return true;

    }


    /*
     * Gets the css path or url to the stylesheet
     *
     * @var     string  path/url
     *
     */
    public function file( $target = 'path' ) {

        global $blog_id;

        // Get the upload directory for this site.
        $upload_dir = wp_upload_dir();
        // If this is a multisite installation, append the blogid to the filename
        $blog_id = ( is_multisite() && $blog_id > 1 ) ? '_blog-' . $blog_id : null;

        $file_name   = 'dynamic-css' . $blog_id . '.css';
        $folder_path = $upload_dir['basedir'] . DIRECTORY_SEPARATOR . 'dynamic-styles';

        // The complete path to the file.
        $file_path = $folder_path . DIRECTORY_SEPARATOR . $file_name;
        // Get the URL directory of the stylesheet
        $css_uri_folder = $upload_dir['baseurl'];

        $css_uri = trailingslashit( $css_uri_folder ) . 'dynamic-styles/' . $file_name;

        // Take care of domain mapping
        if ( defined( 'DOMAIN_MAPPING' ) && DOMAIN_MAPPING ) {
            if ( function_exists( 'domain_mapping_siteurl' ) && function_exists( 'get_original_url' ) ) {
                $mapped_domain   = domain_mapping_siteurl( false );
                $original_domain = get_original_url( 'siteurl' );
                $css_uri = str_replace( $original_domain, $mapped_domain, $css_uri );
            }
        }
        // Strip protocols
        $css_uri = str_replace( 'https://', '//', $css_uri );
        $css_uri = str_replace( 'http://', '//', $css_uri );

        if ( 'path' == $target ) {
            return $file_path;
        } elseif ( 'url' == $target || 'uri' == $target ) {
            $timestamp = ( file_exists( $file_path ) ) ? '?timestamp=' . filemtime( $file_path ) : '';
            return $css_uri . $timestamp;
        }

    }
    
    public function compile_scss() {
        require dirname( __FILE__ ) . '/framework/scss/wp-scss/scssphp/scss.inc.php';
        
        $scss = new scssc();
        $scss->setImportPaths( 'framework/scss/' );
        $scss->setFormatter( 'scss_formatter_compressed' );
        
        $variables = Kirki::get_variables();
        $vars      = '';
        foreach ( $variables as $variable => $value ) {
            $vars .= '$' . $variable . ':' . $value . ';';
        }
        
        $scss_string = $vars . '@import "style.scss";';
        
        $css = $scss->compile( $scss_string );
        
        return $css;

    }

}
$compiler = new Aristath_Dynamic_CSS
// Omit closing PHP tag to avoid "Headers already sent" issues.

https://gist.github.com/aristath/7b6eb847c9302e289583

Thanks Jake

**Comment by robocoder** [comment]
try:
```
$scss->setFormatter('compressed');
```
