### ISSUE TITLE
Docs blocked by firewall

### ISSUE THREAD

**Issue by tomjoad2000** [leafo/scssphp#267]
Docs blocked by firewall:

Request denied by WatchGuard HTTP proxy.
Reason: Category 'Web Chat' denied by WebBlocker policy 'WebBlocker.2'.
Method: GET
Host: leafo.net
Path: /scssphp

**Comment by robocoder** [comment]
Worksforme.

In the meantime, you can use:

https://github.com/leafo/scssphp/blob/master/site/docs/index.md
