### ISSUE TITLE
Wrong output order of rules with lone `&` as selector breaks cascading

### ISSUE THREAD

**Issue by Marat-Tanalin** [leafo/scssphp#271]
Order of rules in output CSS is wrong when using a lone `&` as selector. Since CSS is a cascading thing, exact rule order is _critical_. Minimal testcase is below.

Source SCSS code:

    UL {
    	& {
    		margin: 0;
    	}
    
    	margin-left: 35px;
    }

Actual result:

    UL {
    	margin-left: 35px;
    }
    UL {
    	margin: 0;
    }
    /* Effective `margin` value is `0`. */

Expected result:

    UL {
    	margin: 0;
    }
    UL {
    	margin-left: 35px;
    }
    /* Effective `margin` value is `0 0 0 35px`. */

The testcase is _minimal_. In reality, `&` is a part of a selector _enumeration_ allowing to apply the same styles to the element and its nested elements at once, and then override it partially for the element itself:

    UL {
    	&, LI {
    		margin: 0;
    	}
    
    	margin-left: 35px;
    }

FWIW, as far as I remember, lessphp is affected by the same issue (probably due to some common parser/formatter parts shared by both).

**Comment by robocoder** [comment]
The current behavior matches ruby sass and libsass.

**Comment by Marat-Tanalin** [comment]
Thanks, I will report it to SASS team.
