### ISSUE TITLE
Does not support JEET.gs

### ISSUE THREAD

**Issue by justinotero** [leafo/scssphp#280]
I am using Jeet.gs for my grid systems, but it won't compile Jeet?

**Comment by robocoder** [comment]
What scssphp version are you using?

I didn't have a problem compiling jeet 6.1.2's index.scss with scssphp v0.1.6 or master.

**Comment by robocoder** [comment]
Please post a snippet of scss that shows the problem you're seeing.

**Comment by robocoder** [comment]
Closing.  I'm guessing you weren't using the latest version at the time as prior to v0.1.6, scssphp didn't support the function-exists() or set-nth() built-in functions that jeet relies on heavily for feature detection.
