### ISSUE TITLE
Help port less to scss complier !

### ISSUE THREAD

**Issue by jimmyphong** [leafo/scssphp#283]
i need port my project from less to scss but so hard to do !

example for my less complier 

              $options = array(
			'cache_dir' => BASE_CACHE . 'less',
			'compress' => true,
			'output' => BASE_TEMPLATE . 'bootstrap-less.css'
		);
		
		$to_cache[BASS_TEMPLATE . 'mytheme/bootstrap/bootstrap.less'] = 'view/mytheme/bootstrap';
	        $variables = array(/* some variables */);
		$css_name = \Less_Cache::Get($to_cache, $options, $variables);
               return $css_name;

so now i need port this to using sass css 
i had download bootstrap-sass from https://github.com/twbs/bootstrap-sass

so i dont now how to complier with some options like less
1) Set cache directory
2) Set compress
3) Set or return output file
4) Set some varibales to override bootstrap variables

Thanks for any help !

**Comment by robocoder** [comment]
https://github.com/leafo/scssphp/blob/master/site/docs/index.md

**Comment by jimmyphong** [comment]
Hi @robocoder thanks for you help , now it working so i have one question ?
where function to set import path

example for less complier 
i setting  
                $to_cache[BASS_TEMPLATE . 'mytheme/bootstrap/bootstrap.less'] = 'view/mytheme/bootstrap';

when complier sucess in css path (bootstrap font path) will append relative path like

              url('view/mytheme/fonts/bootstrap/glyphicons-halflings-regular.eot?#iefix')

so for scss complier any function to do that !

**Comment by robocoder** [comment]
The Compiler class has addImportPath(string) and setImportPaths(array) methods.

**Comment by jimmyphong** [comment]
Thanks @robocoder 
One question ? how to see cache file ?
i has set cache folder like
                        
                        .................
                        $output = PATH . 'bootstrap.min.scss';
			$scss = new Compiler();
                        $scss->setImportPaths(dirname($output));
			$cache_dir = CACHE_DIR. 'sass';
			$server = new Server(dirname($file), $cache_dir, $scss);
			$css = $server->compileFile($file, $output);

any work and a folder sass creat in CACHE_DIR
so it empty !

maybe im wrong some config;

**Comment by robocoder** [comment]
I'm sorry it isn't clear from the docs but compileFile() doesn't use the cache.

use:
```
$css = $server->checkCachedCompile($file, $output);
```
