### ISSUE TITLE
Incorrectly compiling the latest zurb/foundation (5.5.2)

### ISSUE THREAD

**Issue by rebelmiles** [leafo/scssphp#293]
Compiling Foundation 5.5.2 results in missing selectors. Reverting to 5.3.0 seems to work just fine.

(example - input fields appear disabled because the :disabled, [disabled] and :hover selector is appended only to the last group of the comma separated selectors)

**Comment by robocoder** [comment]
Without some test case, this sounds like a dupe of #160.

**Comment by rebelmiles** [comment]
Looking in to it, yes. Looks closer to #160 - but they seem like similar bugs.

Any ETA on a fix for this?

**Comment by robocoder** [comment]
No, I don't have an estimate at this time.

**Comment by vita10gy** [comment]
This can be worked around pretty easily. That's the only call to that function. Just put the list there directly and it's fine.

**Comment by rebelmiles** [comment]
@vita10gy : That then defies the purpose of composer and version control - paricularly if  I start making amendments in one package to compensate for bugs in another...

As it is I have locked Foundation to 5.3.0 and scssphp at 0.1.3 which seems to work just fine. But a fix for this would be good as it's only going to become more common.

**Comment by robocoder** [comment]
I agree that pinning is a short term solution and that this needs to be fixed -- ideally before the bump to 0.2.

**Comment by vita10gy** [comment]
Well, sure, I never meant to imply this issue should never be addressed, just that it can be worked around very easily, as opposed to if text-inputs() was used in 10 places.

Given the state of things, what's less convenient for your work flow: Using an older copy of foundation with x number of issues/missing features, not using phpscss, or a 4 second copy/paste in one place?

**Comment by rebelmiles** [comment]
Not the solution you think, I guess. Anyway, this isn't the place.

**Comment by vita10gy** [comment]
You're introducing a years worth of bugs and other issues with foundation to every website you're making because of one issue in scssphp, which takes zero time to compensate for. That feels crazy to me.

**Comment by rebelmiles** [comment]
Stop being so truculent - you don't need to be right. I don't adhere to either of your expressed views of what Foundation is. This forum is about a bug in scssphp - can we just agree there is a bug that needs fixing and we have both found workarounds?

**Comment by vita10gy** [comment]
There's a $10 word. :)

As for scssphp, when I posted this as issue #248 it was closed in favor of #244, so at least at the time someone must have thought it was more like that,.

**Comment by robocoder** [comment]
@vita10gy, @rebelmiles : could you please test master against your respective bug reports (#248 and #293); I've just committed a fix that closes 3 similar issues with selector lists

**Comment by vita10gy** [comment]
Looks like it fixed it for me yes. Good work, thanks.

**Comment by rebelmiles** [comment]
@robocoder : That has fixed it as far as I can see! Thanks - really appreciated!

\o/

**Comment by robocoder** [comment]
OK, expect to see a tagged release in the next few days

**Comment by robocoder** [comment]
I improved the original fix. v0.1.9 has now been tagged. Enjoy!
