### ISSUE TITLE
Variable in nested rule leaks to parent rule

### ISSUE THREAD

**Issue by Marat-Tanalin** [leafo/scssphp#295]
Testcase:

    BODY {
        $bg: green;

        DIV {
            $bg: red;
        }

        background: $bg;
    }

Actual result:

    BODY {
        background: red;
    }

Expected result:

    BODY {
        background: green;
    }

**Comment by robocoder** [comment]
Can you test this on sassmeister? I'm on my smartphone and afk, but I think this is the actual result is the expected behavior.

**Comment by Marat-Tanalin** [comment]
Thanks for the tip about SassMeister as an easy way to test SCSS code using original SCSS implementation.

I've tested the testcase, looks like libsass has the same bug. I will report it to SCSS team.

But below is another testcase that gives **different** results in SassMeister and scssphp:

    BODY {
        DIV {
            $bg: red;
        }
    
        background: $bg;
    }

Actual result in scssphp:

    BODY {
        background: red;
    }

Expected result (and actual result in SassMeister):

    Undefined variable: "$bg".

**Comment by Marat-Tanalin** [comment]
And yet another testcase that gives different results in scssphp and SassMeister (please let me know if it should be reported as a new issue):

    @mixin example {
    	background: $bg;
    }
    
    P {
        $bg: red;
    
    	@include example;
    }

Actual result in scssphp:

    P {
        background: red;
    }

Expected result (and actual result in SassMeister):

    Undefined variable: "$bg".

**Comment by Marat-Tanalin** [comment]
And yet another one related to the same variable-scope issue:

    @mixin example {
    	$color: red;
    }
    
    A {
    	$color: green;
    	@include example;
    	color: $color;
    }

Actual result in scssphp:

    A {
        color: red;
    }

Expected result (and actual result in SassMeister):

    A {
        color: green;
    }

**Comment by robocoder** [comment]
Interesting. Thanks for investigating the scoping of variables. Ruby sass/scss is the reference implementation, so we'll make changes to match their behavior.

**Comment by robocoder** [comment]
Re-opening in connection with #367
