### ISSUE TITLE
Color functions output white and black colors

### ISSUE THREAD

**Issue by fede91it** [leafo/scssphp#296]
Using **darken** and **lighten** functions, the output color is always #000 using `darken` and #FFF using `lighten`

**Comment by robocoder** [comment]
Can you post your test case?  I just tested this:

```
test {
  background-color: darken(#2ba6cb, 40%);
  color: lighten(#2ba6cb, 10%);
}
```
and `bin/pscss` returned:
```
test {
  background-color: #071c23;
  color: #4fbada; }
```

**Comment by fede91it** [comment]
My fault! I didn't use the percentage but only the number.
It's work fine thank you,

**Comment by robocoder** [comment]
Reopening. Ruby sass coerces whole numbers into percentages.
