### ISSUE TITLE
variable-exists always return true

### ISSUE THREAD

**Issue by pikilon** [leafo/scssphp#312]
Hi, first of all thanks for this great script to implement sass in php.

Maybe it is not implemented yet but variable-exists always returns true
```sass
@if variable-exists($non_existent) {
 $non_existent:5px solid white;
}
```
Maybe scssphp has another way of checking this.

thanks again

**Comment by robocoder** [comment]
Did you mean this?
```
@if variable-exists('non_existent') {
 $non_existent:5px solid white;
}
```

**Comment by pikilon** [comment]
Thank you very much for your help, 

If someone sees this (stupid) post of mine notice that the right sentence is like this: (without dollar or quotes)

```sass
@if variable-exists(non_existent) {
 $non_existent:5px solid white;
}
```

**Comment by robocoder** [comment]
If it didn't work with quotes, then it's probably a bug...

**Comment by pikilon** [comment]
I can confirm it works with and without quotes.

**Comment by robocoder** [comment]
Thanks for confirming.
