### ISSUE TITLE
Double imports occur

### ISSUE THREAD

**Issue by Nimja** [leafo/scssphp#315]
If you have multiple mentions of an import, the file is included multiple times.

This is easy to fix in \Leafo\ScssPhp\Compiler

    protected function importFile($path, $out)
    {
        // see if tree is cached
        $realPath = realpath($path);
        if (isset($this->importCache[$realPath])) {
            // Nothing to do, already imported.
            return;

**Comment by Nimja** [comment]
Additional note; currently if someone creates:

reset.scss
    @import 'reset';

You can crash the compiler.

**Comment by robocoder** [comment]
The import loop is a bug, but double imports are allowed in the ruby implementation.  See sass/sass/issues/139
