### ISSUE TITLE
Update Compiler->parsedFiles array to same format as in lessphp

### ISSUE THREAD

**Issue by dleffler** [leafo/scssphp#320]
Since it's not used in scssphp, it is more valuable (to me) to have the $this->parsedFiles array hold both the filename and file modified time as it does in lessphp by changing line ~#2659 in Compiler.php from
```
            $this->parsedFiles[] = $path;
```
to
```
            $this->parsedFiles[realpath($path)] = filemtime($path);
```

**Comment by robocoder** [comment]
Sure but I will defer this to the next minor version bump since it's technically an API combat buster.

**Comment by dleffler** [comment]
Thanks, but looks like you left off the $ from the realPath variable in the updated line?

**Comment by robocoder** [comment]
Yup. I fixed it in a later commit.
