### ISSUE TITLE
v0.3.0 regressions

### ISSUE THREAD

**Issue by robocoder** [leafo/scssphp#324]
Had to partially revert 73c403dc (variable scoping fix) to work with the bootstrap v4-dev branch. If I had to guess, I suspect it's related to nested mixins.

**Comment by mahagr** [comment]
I'm not sure if this is related to variable scoping, but it looks like earlier versions had a bug that caused SCSS compiler not to fail when some variables were not defined at all.

Now SCSS compiler fails hard with exception; would it be possible to create backwards compatible mode where it would just warn about the undefined variables?

I need the code as our theme framework uses your scss compiler and there are some broken stuff that several parties have created -- and just updating the framework would break all of those old themes. 

I'm writing the code anyway, just asking if you are interested on it...

**Comment by robocoder** [comment]
@mahagr : indeed not throwing exceptions for undefined variables was a bug; failing hard is part of the variable scope fixes in 0.3.0 to more closely match ruby scss. If you submit a PR, I'll take a look at including it.

**Comment by mahagr** [comment]
There was an easy way to "work around" the new issue by extending compiler class and doing this:

    public function get($name, $shouldThrow = true, $env = null)
    {
        try {
            return parent::get($name, $shouldThrow, $env);
        } catch (\Exception $e) {
            echo $e->getMessage() . "\n";
            return ['string', '', ['']];
        }
    }

I'm not sure if PR is needed on that one as the solution is that simple. Right now I'm hardcoding the behavior to display warning instead (with output buffering).
