### ISSUE TITLE
Different Websites

### ISSUE THREAD

**Issue by keithwyland** [leafo/scssphp#325]
If I do a Google search for "scssphp" I come up with the site:
http://leafo.net/scssphp/

But the link from the Github repository goes to the site:
http://leafo.github.io/scssphp/

These sites have different versions linked for download. Is confusing for those finding scssphp via Google vs. Github.

**Comment by robocoder** [comment]
One day leafo.github.io may have more googlejuice to rank higher in the search results... Until then...

**Comment by keithwyland** [comment]
Ok... So the 'owner' of both websites are different people?

**Comment by robocoder** [comment]
Technically, both sites have the same owner. The first one is the original, dogfed its scss, and was pushed manually from the master branch. The latter is the most up-to-date, is published automatically by github, and separates the site content (gh-pages branch) from the code.

**Comment by keithwyland** [comment]
Sorry, maybe I'm just not understanding something... If you have access to both sites, why can't the old one just be deleted/taken down?
