### ISSUE TITLE
Doesn't compile Twitter Bootstrap v3 or v4 alpha?

### ISSUE THREAD

**Issue by dleffler** [leafo/scssphp#326]
I've been unable to get a correct compilation of either Twitter Bootstrap v3.5.1 or v4 alpha.  It compiles without error, the the output file is missing something as the navbars, navtabs, etc...are not displayed correctly

**Comment by dleffler** [comment]
The Bootstrap 3.5.1 issue was my fault and I'm not sure that v4 alpha is intended to compile just yet (but the above symptoms occur when I compile it)

**Comment by robocoder** [comment]
There's a regression in 0.3.0 that's preventing scssphp from compiling bootstrap v4. There's a temporary workaround in e688a858 until I have a proper fix.
