### ISSUE TITLE
Is there a way to make the compiler more performant?

### ISSUE THREAD

**Issue by tlaverdure** [leafo/scssphp#328]
Hey there! Thanks for all your hard work on this great library. I read in a previous issue that currently development is focused more on compatibility than performance. Which sounds great, but I also wanted to know if were any plans or ideas around how to make the performance of this library better?

I'm currently using scssphp to compile Bootstrap with custom variables on a server and the compilation process is taking about 1.5 - 2 seconds which does seem kind of slow.

Just wanted to know if there is a game plan out there yet and if there is somewhere I can jump in to help.

Thanks

**Comment by vita10gy** [comment]
Are you letting it compile every load?

**Comment by tlaverdure** [comment]
Not per page load - but every time a custom variable is changed. For example, changing the background color, font color, button color, etc. and seeing a real-time update. I'm passing my variables via JavaScript and updating the stylesheet when the ajax function is complete. Since this process is synchronous I'm having to wait about a couple seconds before the next change can be made.

**Comment by robocoder** [comment]
If you need performance, I would suggest using a php extension that uses libsass. When scssphp was first released, libsass hadn't been released yet. In the time since, I think scssphp's niche has become that of being a pure php implementation (as opposed to being the fastest implementation).

Here are a couple of optimization ideas:
* cacheable/serializable parse tree; for starters, the sourceParser in each block would need to change from being a reference to the current Parser to an index into a list of parsed files
* eliminate the separate adjustAllChildren() pass in the Nested formatter

**Comment by tlaverdure** [comment]
Thanks, I've looked at the libsass php extension but was hoping to find a solution that could easily be used without having to install anything. The goal is to add a scss compiler to a self-hosted solution that runs out of the box and scssphp seemed to have fit that use case better.

Thanks for sharing those ideas on optimization.

**Comment by mahagr** [comment]
We are using leafo SCSS compiler in Gantry 5 framework and its serving us fine, but I agree that compilation times and high memory usage are a bit issue in some hosts. But those put aside, I think they work great and there are indeed some ways to optimize, which I have been playing with.

One of the most obvious ways to improve the speed is to only recompile when user saves the changes. For the others, I'm still looking ways to save both memory and CPU time.

**Comment by tahpot** [comment]
>I'm currently using scssphp to compile Bootstrap with custom variables on a server and the compilation process is taking about 1.5 - 2 seconds which does seem kind of slow.

I'm compiling bootstrap and it takes over 60 seconds... has something changed since then or am I doing something wrong?
