### ISSUE TITLE
Notice in Compiler.php while using @extend

### ISSUE THREAD

**Issue by cichy380** [leafo/scssphp#332]
Hi,

I have multi notices:
<strong>Notice: Undefined offset: 0 in (...)\leafo\scssphp\src\Compiler.php on line 278</strong>
while I am compiling Bootstrap SASS files. I found that this noice is in line with <code>@extend</code>.

regards

**Comment by robocoder** [comment]
Are you using bootstrap v4-dev?  What scssphp version are you using?

Try applying the PR from https://github.com/leafo/scssphp/pull/327.

If you can, please provide sample scss (either standalone or using bootstrap) that I can add to the unit tests.  Thanks.

**Comment by robocoder** [comment]
It looks like you're using an older version of scssphp (circa v0.1.10). A guard was added in 8a37178.

If you still have a problem with `master` or the latest version (v0.3.1), please re-open.

**Comment by cichy380** [comment]
Hi,

I am using <strong>Bootstrap 3</strong> but when I used <strong>scssphp</strong> from <strong>master</strong> branch - notices gone.

Thank you very much. Regards, Marcin
