### ISSUE TITLE
Extension support for Parser?

### ISSUE THREAD

**Issue by IceReaper** [leafo/scssphp#335]
Any plans on letting us write extensions to the parser?
In my case i would like to add an @importOnce function which simply caches the path so i can specify dependencies without having them to load up twice. As this is non-standard yet (planned for sass v4) the only two ways would be either modifying the source, or allow us to extend the parser. Second solution preferred as i wish to use composer to get scssphp.

**Comment by robocoder** [comment]
No plans. There's a lot of internals and compatibility work remaining so a parser extension API is unlikely in the near future. (In other words, the current API is unstable.)

For something as purpose built as import-once, I would suggest forking and modifying the source. You then choose if/when to merge/rebase from upstream.

In the case of import once, you can also consider the zurb foundation approach (using !global).

If you choose the composer route, you can go ahead and subclass. However, you'll need to specify a version constraint to avoid breakage when running `composer update`.
