### ISSUE TITLE
Bootstrap-sass 3

### ISSUE THREAD

**Issue by dleffler** [leafo/scssphp#337]
I have a nested .scss file which wraps the entire Twitter Bootstrap 3 styles to subclass them which now doesn't seem to compile do to this code around line #2502 of Compiler.php
```
            if (! $hasNamespace && isset($env->marker)) {
                $env = $this->rootEnv;
                continue;
            }
```
This fragment prevents the code from moving deeper into the nested '$env->parent->store' variable because the $env->marker is set to 'mixin' and simply picks up the $this->rootEnv which is the variable passed to the compiler prior to compilation.  My .scss file looks like:
```
.exp-skin {
	$swatch: "united"; // newui uses this swatch
	$themepath: "united"; // hack to prevent crash
	@import "_bootstrap.scss";
}
```
where i import the appropriate variables/bootswatch in the _bootstrap.scss file.  The base _bootstrap.scss compiles correctly, but when compiling the 'wrappered' one it'll exit with an exception of 'Undefined variable grid_columns'

My (temporary) solution is to comment out the lines show above.

**Comment by dleffler** [comment]
FWIW, the top of my _bootstrap.scss looks like this (bootswatch v3.3.5+3 & bootstrap v3 scss are both dropped into the bootstrap3 code folder)
```
// Core variables and mixins
@import "#{$themepath}/_variables.scss"; //exp Modify this for theme colors, font-sizes, etc
@import "../less/#{$swatch}/_variables.scss"; //exp Modify this for custom colors, font-sizes, etc
@import "bootstrap/variables";
@import "bootstrap/mixins";
```

**Comment by robocoder** [comment]
I couldn't get your example to compile with ruby scss 3.4.15. Do you have a repo I can clone to take a look?

**Comment by robocoder** [comment]
Please re-open when you're able to provide a more complete test case to reproduce the error. Thanks.
