### ISSUE TITLE
Main file NOT added to list of $compiler->parsedFiles

### ISSUE THREAD

**Issue by dleffler** [leafo/scssphp#339]
To maintain consistency with lessphp and the intent of cached compiling the following needs to be added to Compiler.php around line #164 (since there is no 'addParsedFile() method in scssphp)
```
        if (!empty($name)) {
            $realPath = realpath($name);
            $this->parsedFiles[$realPath] = filemtime($realPath);
        }
```
Ref #334 & #321

**Comment by robocoder** [comment]
Sure. Submit a PR.
