### ISSUE TITLE
The Import rule within the media directive.

### ISSUE THREAD

**Issue by hitok** [leafo/scssphp#344]
Hi,

To reproduce the bug:
1. Create sample SCSS file, for example "sample.scss" with valid scss code.
2. Prepare php script with folling code:

    require_once "scss.inc.php";
    use Leafo\ScssPhp\Compiler;
    $scss = new Compiler();
    $scssSource = '
      @import "sample";
      @media (min-width: 0px) and (max-width: 500px) {
           @import "sample";
      }
    ';
    echo $scss->compile($scssSource);

Result: 
```
Notice: Undefined property: stdClass::$sourceParser in Z:\home\scss.loc\www\src\Compiler.php on line 2921
Fatal error: Call to a member function getSourceName() on a non-object in Z:\home\scss.loc\www\src\Compiler.php on line 2921
```
Testing Env: Windows 7, PHP 5.4.25, Apache 2.0

I had quick fix - Compile.php (line 490):
```
        if ($type !== 'block' && $type !== 'media' && $type !== 'directive') {
```
to
```
        if ($type !== 'block' && $type !== 'media' && $type !== 'directive' && $type !== 'import') {
```
to prevent wrapping...

Thank you for the great compiler. I look forward to fixing a bug. I look forward to fixing a bug.

**Comment by robocoder** [comment]
Looks good. Submit a PR.
