### ISSUE TITLE
Styles are not recompiled when imports are changed

### ISSUE THREAD

**Issue by kelnar** [leafo/scssphp#350]
Styles are not recompiled when some of the imports are changed.

**Comment by robocoder** [comment]
Can you elaborate on how you're using scssphp?  Command line (bin/pscss), Server class (what options?), or via some thrd-party wrapper?

**Comment by kelnar** [comment]
I've created separated file called ```style.php```:

```php
require_once "scssphp-0.3.2/scss.inc.php";

use Leafo\ScssPhp\Server;

$directory = "styles";

Server::serveFrom($directory);
```

Then use this:
```html
<link href="style.php/mystyle.scss" rel="stylesheet">
```

**Comment by designerno1** [comment]
i think there is the problem Server.php method needsCompile
```php
foreach ($metadata['imports'] as $import => $importMtime) {
                if ($importMtime > $mtime) {
                    return true;
                }
            }
```
for me it looks like $importMtime is the filetime whene the files are compiled and $mtime is the filetime of the compiled file when it is compiled

but i think you have to check the filetime when the imports are compiled against the current filetime of the import file

i added this to the foreach loop
```php
                $importFtime = filemtime($import);
                if ($importFtime > $importMtime) {
                    return true;
                }
```
for me it looks like it's working i save a imported file and the scss gets new compiled

**Comment by robocoder** [comment]
Thanks.

**Comment by designerno1** [comment]
i think it should be
```php
if (filemtime($import) > $importMtime) {
```
because $mtime is the time of the whole file not the included file?

**Comment by robocoder** [comment]
I was restoring the equivalent behavior prior to 0.3.0.

If we're going to compare timestamps for the original file, then a PR for `if (filemtime($import) !== $importMtime) {` may better handle edge cases such as switching branches or restoring from a backup file.
