### ISSUE TITLE
Support for SASS 3.3

### ISSUE THREAD

**Issue by marcwieland95** [leafo/scssphp#355]
Is there a plan to support SASS 3.3?

I've got a problem with the gird-framework Jeet.

This code isn't compiled correctly:

    @for $i from 1 through ceil(length($list)/2) {
        $tmp: nth($list, $i);
        $tmp: if(length($tmp) > 1 and $recursive, reverse($tmp, $recursive), $tmp);

        $list: set-nth($list, $i, nth($list, -$i));
        $list: set-nth($list, -$i, $tmp);
     }

**Comment by robocoder** [comment]
Yes. Known outstanding [issues](https://github.com/leafo/scssphp/issues) are labelled 3.3 or 3.4.

I don't think that code works in Jeet. There's no `reverse` function defined in Jeet and no built-in in ruby scss 3.4.15.

**Comment by robocoder** [comment]
Please test using the master branch.  AFAICT this will be fixed in the next release as it contains the set-nth() fix in a763e28ed14cd5d5478d754cece0b9ad726b9661.

**Comment by marcwieland95** [comment]
Hi, thanks for your prompt respond.
I just tested it. It works now (master branch)

Yes, the `reverse` function is quite interesting, but see:
https://github.com/mojotech/jeet/blob/master/scss/jeet/_functions.scss#L87
