### ISSUE TITLE
Proposal: Raise minimum PHP requirement to PHP 5.4?

### ISSUE THREAD

**Issue by robocoder** [leafo/scssphp#360]
* PHP 5.3.x is no longer maintained or updated; the last release was 5.3.29 on August 14, 2014
* Dropping PHP 5.4 support will be proposed later. It reached End-of-Life on September 14, 2015.

Voting closes November 7.

[Results](http://poll.gitrun.com/leafo/scssphp/issues/360)

**Comment by robocoder** [comment]
+1

**Comment by nazar-pc** [comment]
I don't even mind about 5.5+

**Comment by vita10gy** [comment]
Is there anything specifically that you'd like to use from 5.4 that 5.3 doesn't have?

**Comment by nazar-pc** [comment]
Nice array syntax, different interpretation of `$this` in callbacks - first what came to my mind

**Comment by nazar-pc** [comment]
And generally it is good to force people using supported versions instead of outdated insecure versions.

**Comment by vita10gy** [comment]
Except "people" often have no say over such things. And, hopefully without undercutting the Herculean efforts here, I would say this caters to those people more so than in general things might. 

Almost by definition anyone using this would have some kind of external determination of what they're allowed to use on their server, because if we didn't we'd be running the official scss compilation tools.

**Comment by nazar-pc** [comment]
Do you want to say it is good to encourage people to use old software with known security holes that will never be fixed? I prefer not doing so and any adequate business will do the same, they don't run software that is by definition insecure.
Moreover, 5.4+ requirement is too soft, 5.3 was abandoned long time ago and even 5.4 is not supported anymore. I don't see any reason to support 5.3 at all, 5.4 might be discussed with those who stuck in past for whatever reason.

There are 67 people subscribed to this repository, lets see what they say.

P.S. Many new projects support only 7.0+, which is another extreme:)

**Comment by vita10gy** [comment]
"Encourage" and "accept the reality of the situation" are two pretty different things. 

If these are to be trusted (though I don't know how they'd get these numbers), PHP 5.3 is the dominant version out there. http://w3techs.com/technologies/details/pl-php/5/all

If we could all just flip a switch and be upgraded, obviously we would be already. And, again, I mean no offense to those who have invested so much time here, but the idea that one 3rd party thing dropping support for 5.3 is what would make it suddenly possible to upgrade is pretty silly. 

This project should pick whatever is for the good of the project, but the notion that this being 5.3 compatible 'encourages' an outdated version of PHP is pretty strange. Are YOU proposing anyone in a position to install any version of PHP install the minimum version some project they like allows for?

**Comment by mahagr** [comment]
:+1: for PHP 5.4 minimum. We have already dropped PHP 5.3 support in our new products and it looks like people/companies can upgrade their PHP version without any issues if they have to. If the minimum version stays on PHP 5.3, nobody will ever upgrade.

On the other hand as PHP 5.4 is still kinda supported, I wouldn't drop support for it just yet.

**Comment by etu** [comment]
:+1: for 5.4 minimum. I'd rather say 5.5 though since 5.4 is EOL.

Also for @vita10gy: Well, if you're on an old version of PHP. You can always install an old version of scssphp to have a complete experience of outdated software.

**Comment by robocoder** [comment]
Thanks for all the input/feedback/discussion.

There are a few days left to vote. [Results](http://poll.gitrun.com/leafo/scssphp/issues/360)
