### ISSUE TITLE
Variable is unavailable in nested @content mixin

### ISSUE THREAD

**Issue by Marat-Tanalin** [leafo/scssphp#367]
Looks like 73c403d has introduced another scoping bug making scssphp inconsistent with LibSass as for mixins. The previous version (f88ecf1) did not contain the bug. The bug is still here in the latest version 0d18559. Minimal testcase:

	@mixin foo {
		@content;
	}

	@mixin bar {
		@content;
	}

	A {
		@include foo {
			$top: 10px;

			@include bar {
				top: $top;
			}
		}
	}

**Scssphp** result:

	Uncaught Exception: Undefined variable $top

**SassMeister** result:

	A {
		top: 10px;
	}

(The testcase is very minimal. In real-world stylesheets where the bug has been discovered, mixins contain `@content;` inside `@media` rules.)

**Comment by robocoder** [comment]
The fix for #295 seems to be half-baked...unless it's fixed properly, I'll revert it for the next release.

**Comment by Marat-Tanalin** [comment]
Thanks. I confirm scssphp now works correctly with real-world SCSS code that involves `@content`, not just with the minimal testcase above.
