### ISSUE TITLE
hookpoints or way to manipulate compiled css

### ISSUE THREAD

**Issue by designerno1** [leafo/scssphp#369]
is there a way to manipulate the output css before it gets saved?
i implement an autoprefixer and think about how i can manipulate the compiled css, so for now my workflow is hardcoded in Compiler.php method compile()
```php
if (statement) {
    $out = do something;
}
return $out;
```
maybe there is a better way to dothis?

**Comment by robocoder** [comment]
Maybe add methods to the Formatter?

**Comment by designerno1** [comment]
hm i take a look and give it a try.
