### ISSUE TITLE
"Compressed" formatter is removing comments.

### ISSUE THREAD

**Issue by chrisblakley** [leafo/scssphp#373]
I've been troubleshooting this for a while, and everything is pointing to the "Compressed" formatter.

When I compile using "Compact", the comments remain, and if I change it to Crunched everything is minified and the comments are removed- totally expected. However, if I use Compressed, everything is minified and the comments are removed (just like Crunched). I've switched back and forth between Compact and Compressed and the comments are always removed when using Compressed.

Everything else is working fine.

I wish I had more information to share. I just updated to the latest version on this repo, but still get the same results.

**Comment by robocoder** [comment]
Yes, crunched removes all comments. Compressed preserves comments with the bang symbol, i.e., `/*! Comment */`

**Comment by chrisblakley** [comment]
Thanks that helped. I knew that's how Crunched worked, but I did not know I had to add the ```!``` to my comments in Compressed. Thanks for the info.
