### ISSUE TITLE
HHVM support

### ISSUE THREAD

**Issue by nazar-pc** [leafo/scssphp#377]
What is the reason of dropping HHVM support? It was small just simple hack.

**Comment by robocoder** [comment]
3 strikes. It was a hack that would have been required yet again to fix https://travis-ci.org/leafo/scssphp/jobs/90411962

**Comment by nazar-pc** [comment]
Any chance to bring HHVM support back?

**Comment by robocoder** [comment]
Maybe when https://github.com/facebook/hhvm/issues/5457 is fixed.
