### ISSUE TITLE
moving from 0.4 to 0.5 yields multiple E_NOTICE

### ISSUE THREAD

**Issue by Zxurian** [leafo/scssphp#378]
had a working install using Assetic & scssphp v0.3

did a composer update and saw it jumped to 0.5. Went to use my site as usual and upon page load it started spamming the following errors:
```
E_NOTICE: Undefined index: in
in /var/www/dev-hub/vendor/leafo/scssphp/src/Node/Number.php at line 114
E_NOTICE: Undefined index: in
in /var/www/dev-hub/vendor/leafo/scssphp/src/Node/Number.php at line 114
E_NOTICE: Undefined index: pc
in /var/www/dev-hub/vendor/leafo/scssphp/src/Node/Number.php at line 114
E_NOTICE: Undefined index: pc
in /var/www/dev-hub/vendor/leafo/scssphp/src/Node/Number.php at line 114
E_NOTICE: Undefined index: pt
in /var/www/dev-hub/vendor/leafo/scssphp/src/Node/Number.php at line 114
...
```
the actual undefined index character change, but the notice message are spammed continuously (depending on size of scss file loaded).

and it goes on and on. Rolling back to v0.4 and things were working fine again.

**Comment by robocoder** [comment]
Looks like you have a custom handler that doesn't check if error_reporting() returns 0, i.e., the notice was suppressed by the @ operator.
