### ISSUE TITLE
Call to a member function getSourceName() on a non-object in Compiler.php (Line 886)

### ISSUE THREAD

**Issue by chrisblakley** [leafo/scssphp#383]
I apologize if this has been asked before, and I especially apologize if this is an implementation issue on my part. I searched around but only found [one (seemingly unrelated) issue](https://github.com/leafo/scssphp/issues/344).

I'm getting the following fatal error when attempting to use ```$scss->setLineNumberStyle(\Leafo\ScssPhp\Compiler::LINE_COMMENTS);```

**Fatal error: Call to a member function getSourceName() on a non-object in .../scssphp/src/Compiler.php on line 886**

I'm using that when a debug query string is active, and it only errors on certain .scss files (but I can't find anything common between them that the other successful files don't have).

It was happening with v0.3.4, so I updated to the latest (v0.5.1) with no improvement.

I am including scssphp slightly differently than I've seen others use it, but here is the core of my code:
```php
require_once(get_template_directory() . '/includes/libs/scssphp/scss.inc.php');
$scss = new \Leafo\ScssPhp\Compiler();
$scss->addImportPath(get_template_directory() . '/stylesheets/scss/partials/');
$scss->setFormatter('Leafo\ScssPhp\Formatter\Compact');
$scss->setLineNumberStyle(\Leafo\ScssPhp\Compiler::LINE_COMMENTS); //If this line is commented out, the script works 100%. With it in it works on some files, but not all.
$this_scss_contents = file_get_contents($file); //$file is the file path of the .scss file
$compiled_css = $scss->compile($this_scss_contents);
```
*[Here is the entire code implementation](https://github.com/chrisblakley/Nebula/blob/master/functions/nebula_utilities.php#L1166) for reference.*

If it does turn out to be a simple fix, hopefully this will be helpful for anyone else with a similar issue. Regardless, thanks for such an awesome library!

**Comment by robocoder** [comment]
Please see if e9f44a5 fixes this. There was some inconsistency with wrapped blocks.

**Comment by chrisblakley** [comment]
Thanks for the quick response- unfortunately the error is still occurring. Same fatal error, but the line number moved to 879:

```
Fatal error: Call to a member function getSourceName() on a non-object in .../scssphp/src/Compiler.php on line 879
```

**Comment by robocoder** [comment]
Your approach looks ok. Unusual but not unexpected is where nebula_render_scss calls the compile() method multiple times on a single Compiler instance (inside a loop). I don't have an explicit test case for this, so I'll start my investigation there.

**Comment by robocoder** [comment]
Ok. I'm able to reproduce this.

**Comment by chrisblakley** [comment]
Confirming that this works on my server too. Thanks again for looking into this.

**Comment by robocoder** [comment]
If you get a chance, I'd appreciate it if you'd confirm it still works after 1f5c1eeba750f09653432511876613eba3dd2242

**Comment by chrisblakley** [comment]
Just tested the latest commit and it's still working great.
