### ISSUE TITLE
!default variables

### ISSUE THREAD

**Issue by smachi** [leafo/scssphp#386]
According to SASS official docs:

*You can assign to variables if they aren’t already assigned by adding the !default flag to the end of the value. This means that if the variable has already been assigned to, it won’t be re-assigned, but if it doesn’t have a value yet, it will be given one.*

But on the scssphp docs says that: *To override a variable already defined in your scss source, use the !default flag.*

I understand that have opposite meanings, is this right?

**Comment by vita10gy** [comment]
It looks like at least as of my last update it works the wrong way was well, so it's not just a documentation issue.

**Comment by vita10gy** [comment]
I take it all back, I just screwed up my test, which makes a lot more sense since this would be a pretty big deal to go unnoticed. 

Looks like a documentation issue.

**Comment by robocoder** [comment]
Yes, it is specific to the use case with setVariables().  I'll tweak the docs.

**Comment by smachi** [comment]
Then, if I'm loading variables from my scss sources (for example Bootstrap variables file) and I want to override them with my own array of custom variables, how to do it without touching the Bootstrap sources?

I'm using setVariables before compilation but all these preset variables are being overridden by those specified on source files variables
