### ISSUE TITLE
Implement placeholder selectors.

### ISSUE THREAD

**Issue by greg-1-anderson** [leafo/scssphp#392]
From the [SASS Reference Manual](http://sass-lang.com/documentation/file.SASS_REFERENCE.html#placeholders):
```
Placeholder selectors look like class and id selectors, except the # or . is replaced by %. They can be used anywhere a class or id could, and on their own they prevent rulesets from being rendered to CSS.
```
It would be useful if these were supported.

**Comment by robocoder** [comment]
What scssphp version are you using?  We've have placeholder selectors for a while now.

**Comment by robocoder** [comment]
Feel free to re-open with additional test cases not already covered by https://github.com/leafo/scssphp/blob/master/tests/inputs/placeholder_selector.scss
