### ISSUE TITLE
Absolute URL on background-image property

### ISSUE THREAD

**Issue by WebMaestroFr** [leafo/scssphp#393]
Hello, and congratulations on the good work. *scssphp* is awesome and working great.

Though I have an issue using the *background-image* property and can't find a way out.

My image paths cannot be relative to the compiled CSS, and the absolute URL must be defined through PHP... I tried `$scss->setVariables( array( 'site-url' => 'http://my-site.com' ) );`, but the output of `url(#{$site-url}/my-image.jpg)` is `url(http/my-image.jpg)`. I tried to escape it all in different ways, but the result gets weirder and weirder.

In the documentation it says about the **Custom Functions** : "*Some possible applications include appending your assets directory to a URL with an asset-url function...*". Well, that sounds quite like what I try to achieve. But after all my efforts, I get to the same awkwardly backslashed filled results. Is this exact "possible application" somewhere to be found by any chance ? Or where am I doing it wrong ?

Thanks for your time.

**Comment by robocoder** [comment]
The value is the scss source to be parsed. If you want to parse a string, you have to represent it as a string, e.g,, 'var' => '"string"'.

So, in your example:
```
$scss->setVariables( array( 'site-url' => 'http://my-site.com' ) );
```
would be as if you had written:
```
$site-url: http://my-site.com;
```
which isn't what you want. Try this instead:
```
$scss->setVariables( array( 'site-url' => '"http://my-site.com"' ) );
```

**Comment by WebMaestroFr** [comment]
Of course ! Thank you very much for your answer.

**Comment by chrisblakley** [comment]
I also want to thank you for this explanation. I was struggling with this for a while, too.
