### ISSUE TITLE
ParserException while compling files containing cyrillic comments

### ISSUE THREAD

**Issue by artvaleev** [leafo/scssphp#394]
Hello! I get a error while trying to compile any scss file containing cyrillic comments. Example file:
[main.scss.txt](https://github.com/leafo/scssphp/files/62638/main.scss.txt)

Errors look like:

[Leafo\ScssPhp\Exception\ParserException] 
parse error: failed at `*/
` (stdin) on line 3 (0)
scssphp\src\Parser.php:120

**Comment by robocoder** [comment]
It works for me. What php version are you running? If possible, please provide the output from `php -i` or `phpinfo()`.

**Comment by robocoder** [comment]
BTW you can use the command line script to test this, e.g.,

    bin/pscss main.scss.txt

**Comment by robocoder** [comment]
Can you see if 493e05a95431e0cbb3ed6cbca65e07e6e443e19e helps?

**Comment by robocoder** [comment]
Nevermind.... I was able to duplicate it using:
`php -dmbstring.func_overload=2 -dmbstring.internal_encoding=utf-8 vendor/bin/phunit`

**Comment by artvaleev** [comment]
Thank you! You saved much time for many people!
