### ISSUE TITLE
Parse error: failed at `$spacers: (` bootstrap/scss/_variables.scss on line 63

### ISSUE THREAD

**Issue by hatuhay** [leafo/scssphp#400]
Error compiling [Bootstrap 4 - GitHub] (https://github.com/twbs/bootstrap/tree/v4-dev)
Error message: Parse error: failed at `$spacers: (` bootstrap/scss/_variables.scss on line 63).
```scss
$spacers: (
  0: (
    x:   0,
    y:   0
  ),
  1: (
    x:   $spacer-x,
    y:   $spacer-y
  ),
  2: (
    x:   ($spacer-x * 1.5),
    y:   ($spacer-y * 1.5)
  ),
  3: (
    x:   ($spacer-x * 3),
    y:   ($spacer-y * 3)
  )
) !default;
```

**Comment by robocoder** [comment]
Please use the latest version of scssphp. (Currently, v0.6.2.)  You're using an old version of scssphp.  Map support was added in v0.1.2.
