### ISSUE TITLE
$content will not be respected in @at-root

### ISSUE THREAD

**Issue by johannessteu** [leafo/scssphp#407]
This markup

```
@mixin block($name, $type: null) {
  @at-root {
    @if $type != null {
      .#{$name}-#{$type} {
        @content
      }
    } @else {
      .#{$name} {
        @content
      }
    }
  }
}

@mixin element($name) {
  @at-root {
    &__#{$name} {
      @content
    }
  }
}

@mixin modifier($name) {
  @at-root {
    &&--#{$name} {
      @content
    }
  }
}

@include block(testblock) {
  display: block;

  @include element(content) {
    display: block;
  }
}
```

should render

```
.testblock {
  display: block; }
  .testblock__content {
    display: block; }
```

but returns

```
.testblock {
    display: block; }
    __content {
      display: block; }
```

**Comment by robocoder** [comment]
There's something wrong in your markup. It doesn't parse with `scss` or `bin/pscss`.

What version of `scssphp` are you using?  I suspect it doesn't handle this selector syntax yet. `&#{&}--#{$name}`.

**Comment by johannessteu** [comment]
Hey @robocoder !
Yeah, i was actually missing some `}` - sorry for that! Also updated the `&#{&}--#{$name}` selector and examples.

i'm using `0.6.*` wich currently points to `0.6.3`. I think the second `&` is the problem in `&&--#{$name}`.
