### ISSUE TITLE
Resource interpreted as Stylesheet but transferred with MIME type text/html:

### ISSUE THREAD

**Issue by kamal549** [leafo/scssphp#408]
I am getting this error, what to do? 
Resource interpreted as Stylesheet but transferred with MIME type text/html

**Comment by robocoder** [comment]
Leafo\ScssPhp\Server sets the Content-Type to text/css unless there's an error (in which case, the Content-Type is text/plain).

If you're serving the compiled CSS in some other way, then you need to check your web server or integration with the scssphp library.
