### ISSUE TITLE
Handling of font shorthand syntax does not always work

### ISSUE THREAD

**Issue by JanST123** [leafo/scssphp#413]
Hi,

shorthand syntax for fonts (size / line-height) is already handled in a special way in SCSSPhp. This is because otherwise the syntax will be recognised as a formular and the size is devided by the line-height. 
But the special handling does not work in the following cases:
- more than one font-family is given (e.g. _font: 400 1em/1.3 Arial,Helvetica_) -> because of the comma separated font-list the value is turned into a list internally, which breaks the special handling
- The value for the font: attribute comes from a variable -> because the variables value is reduced before internally saving, the special handling does not work

**Test-Case 1 (will work, is outputted as is):**
`p {  font: 400 1em/1.3 Arial; }`

**Test-Case 2 ( will not work. Will be outputted as font: 400 0.76923em Arial, Helvetica):**
`p.one { font: 400 1em/1.3 Arial,Helvetica; }`

**Test-Case 3 ( will not work. Will be outputted as font: 400 0.76923em Arial, Helvetica):**
`
$font: font: 400 1em/1.3 Arial;
p.two { font: $font; } font: 400 1em/1.3 Arial; }
`

**Comment by deltamualpha** [comment]
Would love to see this merged as well, just ran into it and is a blocker for me to switch to this library.

**Comment by robocoder** [comment]
Fixed by #641
