### ISSUE TITLE
List containing exactly 1 List is misinterpreted

### ISSUE THREAD

**Issue by IceReaper** [leafo/scssphp#415]
```
$sizes: (
  ((1,1), (1,1), (1,1), (1,1)),
  ((1,1), (2,1), (1,1)),
  ((2,1), (2,1)),
  ((4,1))
);
```

Above list $sizes has a length of 4. When looping over the list and accessing its entries, the last ((4,1)) gets interpreted as (4,1).
The following example is expected to produce [data-grid='1-1'], but doesnt due to this bug.

```
@for $i from 1 through length($sizes) {
  $a: nth($sizes, $i);
  @for $j from 1 through length($a) {
    $b: nth($a, $j);
    [data-grid='#{length($a)}-#{$j}'] { height: #{100% * nth($b, 2)}; width: #{25% * nth($b, 1)}; }
  }
}
```

**Comment by robocoder** [comment]
This is the behaviour in ruby scss. As unintuitive as it is, for compatibility, we can't fix this bug.
