### ISSUE TITLE
@extend class append or preppend ?

### ISSUE THREAD

**Issue by hroma** [leafo/scssphp#420]
It's more a question than an issue. Extending a class, the output sould be ?

1. .label.error
2. error.label

Currently the class output **.label.error** wich seems wrong to me. It shoud output **.error.label**
Please find below a test case:

%label {
  display: inline-block;
  &.error {
    background: red;
    }
  }

  .label {
  @extend %label;
  font-size: .6em;
  }

**Comment by okj579** [comment]
Since both are classes, both need a period. The star is optional, but will
be included if you add it to your scss (`*.label {}`).

**Comment by robocoder** [comment]
It's technically a compatibility bug with ruby scss but since the order shouldn't matter in this case, I'm going to close it.
