### ISSUE TITLE
Parse error in a loop with @at-root

### ISSUE THREAD

**Issue by pierre-sarrazin** [leafo/scssphp#421]
In a loop with a "For", the "@at-root" like this:
`@for $i from 1 through 3 {
    @at-root .item-#{$i} {
        background: red;
    }
}`

Resulting a parse error, with the current master release:

> Warning:  array_map(): An error occurred while invoking the map callback in /.../src/Compiler.php on line 1013
> Warning:  array_map(): An error occurred while invoking the map callback in /.../src/Compiler.php on line 989
> Fatal error:  Uncaught exception 'Leafo\ScssPhp\Exception\CompilerException' with message 'Undefined variable $i: line: -1' in /.../src/Compiler.php:3296

**Comment by robocoder** [comment]
Testing with `master`, the parse error is gone, but the output is wrong.

scssphp:
```
  .item-1 {
    background: red; }
  .item-2 .item-2 {
    background: red; }
  .item-3 .item-3 .item-3 {
    background: red; }
```

ruby scss:
```
.item-1 {
  background: red; }
.item-2 {
  background: red; }
.item-3 {
  background: red; }
```

**Comment by cojmar** [comment]
👍 Same here

**Comment by khantry** [comment]
👍 Same here, please fix it!

**Comment by robocoder** [comment]
Fixed in master. Will be in the upcoming 0.7.9 release.
