### ISSUE TITLE
Too slow

### ISSUE THREAD

**Issue by Sam116** [leafo/scssphp#422]
Hello, i am using this compiler in module for 1c bitrix, and it compiling so slow. Especially it seems in projects with large main styles.scss file. I think it's connected with lots of using mixin breakpoint, because when i do not use it, plugin compiles instantly. In one project with 5000 lines it complies about 10sec, in other with 8700 lines about 30sec. In one project with 1200 lines and without breackpoints it complies instantly.

**Comment by robocoder** [comment]
Sorry, I can't help you here. This is dependent on both the content being compiled, the system environment (e.g., hardware, vps vs shared hosting vs dedicated server, php version, opcode cache, etc), and how bitrix integrates with scssphp.

**Comment by vita10gy** [comment]
If it helps it's not "supposed" to be instant. I mean, obviously that's ideal, but the fact that it isn't doesn't mean you have a problem somewhere. It takes about 7 seconds to compile Zurb's Foundation 5 on our server. It's not something you should have happening "live" either way.

**Comment by roberthenniger** [comment]
@Sam116 I have the sae impression. When you use mixins it gets very slow. Have you found a solution to your problem?

**Comment by Sam116** [comment]
@roberthenniger No, just compile localy and upload to server

**Comment by roberthenniger** [comment]
I see, unfortunately this is not an option in our setup.

**Comment by vita10gy** [comment]
We have ours compile in place on the server, we just cache the results until there's changes made.

**Comment by roberthenniger** [comment]
We do the same but still our compilation time is too long.

**Comment by mhdhamouday** [comment]
@Sam116 If you are merging files before compile them, add import instead of merge them, then compile thems ex.:
` @import '/your file1'; `
` @import '/your file2'; `
` @import '/your file3'; `
