### ISSUE TITLE
Browser cache-busting

### ISSUE THREAD

**Issue by Toutouwai** [leafo/scssphp#424]
Using the `Server::serveFrom` function creates a problem where style changes can be made in your SCSS files but the changes are not shown in the browser because the browser is caching the compiled CSS file.

A common cache-busting technique is to modify the stylesheet href when changes are detected, to force browsers to reload the CSS. For static CSS files one technique is to append a querystring generated by PHP's filemtime() function, e.g.
`example.com/stylesheets/style.css?1455591803`
Is there a way to use scssphp so that the CSS href changes on each recompile?

**Comment by robocoder** [comment]
scssphp doesn't generate the CSS href URL.

If you don't mind adding another roundtrip to the browser request, you can wrap the serveFrom() with a redirect to a cache buster URL.
