### ISSUE TITLE
Not compiling

### ISSUE THREAD

**Issue by nilsmielke** [leafo/scssphp#427]
PHP—kind of—newbie here.  
I got this running on a web server. Now, when I move that installation to a different server (PHP 5.6.20), it stops compiling. The folder "scss_cache" is being created, but the compiling fails. I don't get any errors.  
What could be the problem and it there a way to test for possible server issues?

**Comment by exigon** [comment]
your php/apache log was completely empty?

**Comment by robocoder** [comment]
It's often a permissions issue (between the process owner of the web server vs the owner of the directory being read from/written to).

But try compiling your scss from the command line using `bin/pscss` to see if it is a scssphp issue.
