### ISSUE TITLE
Weird id compile error

### ISSUE THREAD

**Issue by bnqtoan** [leafo/scssphp#429]
Hi there, 
Thank you for writing this cool package, I used it in my many recent projects.
Today, I got this wrong thing: while I compile

#9b3c92e078e1edbcb0c04de658fe0734{}

it compile to

#9b3c92**e78**e1edbcb0c04de658fe0734{} (instead of 9b3c92**e078**e1edbcb0c04de658fe0734{})

Can we figure out about this problem please.

Thank you for your time.

**Comment by exigon** [comment]
could you put up your original/compiled code chunk?
