### ISSUE TITLE
compile method not throwing error; script dies instead

### ISSUE THREAD

**Issue by Nicscott01** [leafo/scssphp#430]
Hi,

I've noticed an issue where the compile method will just stop running without throwing any errors. As it turns out, in my case the error was an undefined variable. I found that by compiling offline with Ruby.

**Am I missing anything to get the error messages to be returned?**

Note: I'm writing the compiler into a function, and so I need to instantiate the class before I enter the function, hence the use of the global variable.

Essentially my code is:

`use Leafo\ScssPhp\Compiler;

global $cc_scss;
$cc_scss = new Compiler();
$cc_scss->setFormatter('Leafo\ScssPhp\Formatter\Compressed');

function my_compiler_function() {

global $cc_scss;

	$cc_scss->setImportPaths( array ( 
			'/path/to/bootstrap/files',
			'path/to/custom/styles', 
			) );

$scss = //string with variables defined and @imports

$style_sheet = $cc_scss->compile( $scss );

}
`

When it gets to the compile line, I get white screen. All help is appreciated. Thanks for making this great way to compile SCSS with PHP!

**Comment by mahagr** [comment]
Look at your Apache error logs, it usually tells what goes wrong. I suspect that you run out of memory, its the most common issue with css compiler.

**Comment by Nicscott01** [comment]
I checked my logs--there was nothing in there about running out of memory. Its just odd that it didn't return an error message, but instead just died. In fact, I up-ed my memory to 512M to test a few days ago and that didn't help. 

Could it be an issue with PHP7?

**Comment by mahagr** [comment]
I'm using PHP7 without any issues. Some kind of error is really needed to figure out what might be happening.

**Comment by robocoder** [comment]
Are you sure it's getting to the `$style_sheet = $cc_scss->compile( $scss );` line?  Perhaps the string assignment `$scss = //string with variables defined and @imports` needs some quotes escaped?
