### ISSUE TITLE
New release? (dev-master has changes I need)

### ISSUE THREAD

**Issue by mahagr** [leafo/scssphp#431]
@robocoder 

Is it possible to make a new release soon? I do not really want to release my software with composer dependency to dev-master, which we need right now (or we will be stuck on phpscss 0.3). I've been waiting new release for months already and I really cannot postpone scss 3.4 support anymore.

Thanks!

**Comment by BrunoDeBarros** [comment]
Just use `"leafo/scssphp": "dev-master"` in your composer.json file, and you'll get the changes you need without waiting for releases. Alternatively, target a specific commit with `dev-master#c4ad181885e5f85a9f71002983597d9da2c11a8c`.

**Comment by mahagr** [comment]
Yes, I'm using dev-master for development versions, but I'd rather not to target a specific commit when we do the release. :) I'm just hopeful that my issue gets closed within a few weeks.

**Comment by robocoder** [comment]
tagged v0.6.4
