### ISSUE TITLE
Possible memory leak

### ISSUE THREAD

**Issue by exigon** [leafo/scssphp#432]
**The following code produced a nasty error message**

Plugins:
susy (2.2.12)
breakpoint (2.6.1)

Code (with expected result):
https://gist.github.com/exigon/57905c7d03a98be600cacb369037a9a6

Actual result (500 Internal Server Error):
PHP Fatal error:  Out of memory (allocated 149159936) (tried to allocate 130968 bytes) in /Libraries/scssphp/src/Compiler.php on line 1204

I tracked it to the span mixin of susy. (Without including spans, all went well, although it made susy useless.)

**Comment by syphen** [comment]
I was just trying to get Susy running myself and ran into this issue. Does anyone have any potential fixes or should I be using a different branch?
`Allowed memory size of 134217728 bytes exhausted (tried to allocate 130968 bytes) in <b>/Users/rui/Development/paychex/redesign/includes/src/Compiler.php</b> on line <b>1205</b>`

**Comment by Cerdic** [comment]
Still an issue
```
Fatal error: Allowed memory size of 134217728 bytes exhausted (tried to allocate 262144 bytes) in /Users/cedric/Sites/scssphp/src/Compiler.php on line 1502```

**Comment by Cerdic** [comment]
Not a memory leak but an infinite compiling loop due to the tricky:

```
@mixin span($span) {
...
    @include nested($span) { @content; }
 ...
}
```

which was falling on a mixin `@content` bug (picking the wrong level one)
