### ISSUE TITLE
Can't import from database

### ISSUE THREAD

**Issue by tahpot** [leafo/scssphp#434]
The [docs](http://leafo.net/scssphp/docs/#import_paths) state:

> Besides adding static import paths, it’s also possible to add custom import functions. This allows you to load paths from a database, or HTTP, or using files that SCSS would otherwise not process (such as vanilla CSS imports).

The `addImportPath()` method permits specifying a custom function, however that function still has to return a path on the file system.

Compiler.php L3181 always loads from a file:

```
$code   = file_get_contents($path);
```

How can I load an import path with code from a database?

**Comment by robocoder** [comment]
At the moment, indirectly. Your callback would fetch the scss code from your database, save it locally to a temp file, and return the oath of the temp file

**Comment by robocoder** [comment]
Typo. "path" (not oath)
