### ISSUE TITLE
parse error: failed at `if @content 

### ISSUE THREAD

**Issue by raphtag** [leafo/scssphp#435]
I tried something like this, but it would not work:

@mixin foo($bar) {
  color: $bar;
  @if @content {
    @content 
  }
}

.class1 {
  @include foo(#fff);
}

.class2 {
  @include foo(#fff) {
    display: block; margin-top: 10px
  };
}

**Comment by exigon** [comment]
Hi, I don't really get what you are trying to do with this code
@if @content {
@content
}
Are you trying to add a **@content** directive if any other content should be present with an **@if**?
If that should be the case, then **@content** does it all without **@if** like this:

```
@mixin foo($color) {
  color: $color;
  @content;
}
```
see the results here:
https://gist.github.com/exigon/ae642d7360ce64991a87b334b3321efc

**Comment by robocoder** [comment]
That's not valid scss input.  Please test for yourself on sassmeister.com.

```Invalid CSS after "@if ": expected expression (e.g. 1px, bold), was "@content {"```
