### ISSUE TITLE
Comments rearranged

### ISSUE THREAD

**Issue by sebastianwebb** [leafo/scssphp#437]
Hey, I've noticed an issue with CSS comments ending up in odd places in the compiled CSS. I have this test code: https://themeover.com/scss-comments/scss-styles.scss

It compiles to this (with the various comments in the wrong place e.g. Large Desktop): https://themeover.com/scss-comments/active-styles.css

I'm currently using: $scss->setFormatter('scss_formatter'); 

Any ideas?

Cheers,
Sebastian

P.S. I tried to add the CSS code directly to this post but the formatting got a bit skewed.

**Comment by robocoder** [comment]
I'm guessing you're not using the latest version because the scss_formatter doesn't exist anymore.

Please try v0.6.4 (or master).
