### ISSUE TITLE
Cant get it to run!

### ISSUE THREAD

**Issue by tobias-wedel** [leafo/scssphp#441]
Hi, im trying to get scssphp to run for hours now.

I want to use scssphp with my joomla template and dont know what im doing wrong.

Here's my code:
```php
require_once JURI::root(true) .'templates/' . $this->template . '/lib/scssphp/scss.inc.php';

use Leafo\ScssPhp\Compiler;
use Leafo\ScssPhp\Server;

$scss = new Compiler();
$scss->setFormatter('Leafo\ScssPhp\Formatter\Compressed');
$scss->setImportPaths(JURI::root(true) . 'templates/' . $this->template . '/scss');

echo $scss->compile('@import "bootstrap";');

$server = new Server(JURI::root(true) . 'templates/' . $this->template . '/css', null, $scss);
$server->serve();
```

I always get a message: "/* INPUT NOT FOUND scss v0.6.3 */ "

echo $scss->compile('@import "bootstrap";');
shows the css correctly, but nothing is complied.

Any help is appreciated!

**Comment by robocoder** [comment]
Internally, `$server->server()` calls $scss->compile() again, which resets the internal state of the parser and compiler, so it has no knowledge that bootstrap was processed.

Drop the `echo $scss->compile('@import "bootstrap";');` and instead put `@import "bootstrap";` at the top of your .scss files that you expect to serve.

When `$server->serve()` is called, it first looks for the name of the .scss file in the `p` argument.

**Comment by Chacapamac** [comment]
Newbie and not a coder here...
Where do you put the code shown here ?
Do you have to visit that php file to start the compiler?

My goal will be to automatically compile a (or all) scss file in a folder to a (or all) css file in another folder.
Not sure if possible ?

Taking the exemple from tobias-wedel here this is what I did in Joomla,
**1-** I put all files from scssphp-0.7.6 in a new “lib” folder in my working Joomla template
—> Joomla root > templates > My Template > lib > scssphp >>>> All files from download

**2-** I add a scss file (and a folder “grafcustomscss”) to that same template
—> Joomla root > templates > My Template > scss > grafcustomscss > graf.scss

**3-** I add a new php file at the first level of Joomla
I really  like to put it in the template but I’m not to sure if I will able to reach it?_
—> Joomla root > grafcompiler.php
with that code (Similar to tobias) :
`<?php

require_once JURI::root(true) .'templates/' . $this->template . '/lib/scssphp/scss.inc.php';

use Leafo\ScssPhp\Compiler;

$scss = new Compiler();
$scss->setFormatter('Leafo\ScssPhp\Formatter\Compressed');
$scss->setLineNumberStyle(Compiler::LINE_COMMENTS);
$scss->setImportPaths(JURI::root(true) . 'templates/' . $this->template . '/scss/grafcustomscss');

// will search for 'template-in-use/scss/grafcustomscss/graf.scss'
echo $scss->compile('@import "graf.scss";');
 `
I’m visiting —> mysite.com/grafcompiler.php = white page, no errors, no graf.css generated or being loaded if I return to the site.

So far, graf.css do not show up as a loaded css file and I have no idea how to have the compiled css file be automatically added to the template css folder as graf.css
—> Joomla root > templates > My Template > css > all template css here

**Any hint will be appreciated.**

**Also, is this secure in Joomla ?**

**And can it be done automatically, on the fly?**

Thanks and happy New Year to everybody!
