### ISSUE TITLE
Full working example?

### ISSUE THREAD

**Issue by tobias-wedel** [leafo/scssphp#443]
Hi,

i still got problems to run scssphp successfully.

Is there anywhere a full working example to download?
This would help to find out failures by myself.

Thx.

**Comment by robocoder** [comment]
Refer to the docs and try one of the simpler examples to test your integration with this library.

http://leafo.github.io/scssphp/docs/

Alternatively, use a wrapper like assetic.

https://github.com/kriswallsmith/assetic
