### ISSUE TITLE
Import always give parse error on first line

### ISSUE THREAD

**Issue by nwiborg** [leafo/scssphp#444]
Hello!

I'm trying to implement scssphp in my project but I get a problem where my imported files always cast an parse error. No matter what the imported files content is there is always the same error on the first line.

"Message: parse error: failed at `﻿@import 'reset';` assets/scss/main.scss on line 1"

```
use Leafo\ScssPhp\Compiler;

header('Content-Type: text/css');

$scss = new Compiler();
$scss->setImportPaths('assets/scss/');

echo $scss->compile('
    @import "main";
');
```

**Comment by robocoder** [comment]
Your import path is relative to whatever happens to be the current directory. Try specifying an absolute path.

**Comment by nwiborg** [comment]
I don't think that is the problem here. The code finds my main.scss files from the import-statement. However, it always give the parse error on the first line inside main.scss, no matter the content in it.

**Comment by robocoder** [comment]
Have you tried compiling your .scss from the command-line using scssphp's `bin/pscss` or ruby `scss`?

Is there a git repo or web site where I can look at your .scss files?

**Comment by nwiborg** [comment]
The files compile just fine in Visual Studio with the Web compiler, I use that for my regular use of scss. However, now I need to add dynamic variables from the database into på scss-files so I have to go through php. 

I've just invited you into my private repo "lagbygget", the code I'm writing is in the "Dev2.02" branch.

You'll find the scss-files under Lagbygget/assets/scss/

Note these tests:

```
echo $scss->compile('
    $color: red;
    div{color: $color}
');
```
This compiles just fine.

If i change the content inside main.scss to the same as above and run:

`echo $scss->compile('
    @import "main";
');`

This also return a parse error on the first line.

**Comment by robocoder** [comment]
Ok, found the problem.  Your .scss files begin with the Byte Order Marker (\xEF\xBB\xBF).

**Comment by nwiborg** [comment]
Thank you very much! This solved my problem.
