### ISSUE TITLE
Cant Figure out setVariables

### ISSUE THREAD

**Issue by cortet94** [leafo/scssphp#447]
Hello, 

I'm currently trying to override variables that exist in my _variables.scss and then compile the main.scss to accommodate those changes

Currently I have as follows

`
$scss = new Compiler();

$scss->setVariables(array
           $scss->setVariables(array(
            'color-1' => '"#000000"',
            ));

echo  $scss->compile('@import "_variables.scss"');
`

I've looked over "setVariables() - Override variables with php #206" issue with no help, can someone please help me so I can figure this out!

**Comment by robocoder** [comment]
http://leafo.github.io/scssphp/docs/#preset-variables

In _variables.scss, if you define $color-1, then you need to use the !default flag, eg
```
$color-1: red !default;
```

**Comment by cortet94** [comment]
$color-1: #f16624 !default;
$color-2: #1c94d2 !default;
$color-3: #000000 !default;
$color-4: #000000 !default;
$color-5: #000000 !default;
$color-6: #000000 !default;
$color-7: #000000 !default;
$color-8: #000000 !default;

This is what i currently have

**Comment by cortet94** [comment]
Is there anything around What i posted that needs to be added? Such as a command that compiles the main.scss of imports the correct directory?

**Comment by robocoder** [comment]
If _variables.scss doesn't import main.scss, then I would change things up a bit, eg
```
echo $scss->compile('@import "main.scss"');
```
Then main.scss would import _variables.

**Comment by cortet94** [comment]
Is anything dependent upon where I have the scssphp directory located? So far none of these suggestions have worked.
