### ISSUE TITLE
RE: Cant figure out setVariables

### ISSUE THREAD

**Issue by cortet94** [leafo/scssphp#448]
Hello,

I'm currently trying to override variables that exist in my _variables.scss and then compile the main.scss to accommodate those changes

Currently I have as follows

`
$scss = new Compiler();

$scss->setVariables(array
$scss->setVariables(array(
'color-1' => '"#000000"',
));

echo $scss->compile('@import "_variables.scss"');
`

I've looked over "setVariables() - Override variables with php #206" issue with no help, can someone please help me so I can figure this out!

I've already included the !default in my variables.scss, that is not the issue!!!

**Comment by robocoder** [comment]
Try this:
```
$scss = new Compiler();

$scss->setVariables(array(
'color-1' => '"#000000"',
);

echo $scss->compile('@import "main.scss";');
```

And change main.scss to import _variables.

**Comment by robocoder** [comment]
Typo

```
$scss = new Compiler();

$scss->setVariables(array(
'color-1' => '"#000000"',
));

echo $scss->compile('@import "main.scss";');
```

**Comment by robocoder** [comment]
Sorry, replying from my phone.

```
$scss = new Compiler();

$scss->setVariables(array(
'color-1' => '#000000',
));

echo $scss->compile('@import "main.scss";');
```

**Comment by cortet94** [comment]
Still no good. Should I have the scssphp directory in the same directory as _variables.scss?

**Comment by robocoder** [comment]
I assumed your code was just a snippet.  Maybe you need a more complete example?
```
<?php
require_once 'path-to-scssphp/scss.inc.php';

use Leafo\ScssPhp\Compiler;

$scss = new Compiler();

$scss->setImportPath('where your scss is located');

$scss->setVariables(array(
'color-1' => '#000000',
));

echo $scss->compile('@import "main.scss";');
```

**Comment by bologer** [comment]
@robocoder hey, I have something like this: 

```
@charset "utf-8";

@import "normalizer";
@import "_variables";
@import "_mixins";
@import "_common";
@import "_buttons";
@import "comments";
@import "theme-dark";
```

I would like to override all inside `_variables`, but at the end I always get what is the default value inside the scss. 

My usage: 

```php 
$scss = new \Leafo\ScssPhp\Compiler();
$scss->setFormatter( 'Leafo\ScssPhp\Formatter\Crunched' );
$scss->addImportPath('/assets/theming/' );
$replaceVariables = [
     'font-size'   => '15px',
     'global-radius' => '4px',
];
$scss->setVariables( $replaceVariables );

$compiled = $scss->compile( $content );
```
