### ISSUE TITLE
[Leafo\ScssPhp\Exception\ParserException] (stdin) on line 7 at `font-family: @font-family-base

### ISSUE THREAD

**Issue by ideal-it-solutions** [leafo/scssphp#450]
pls can someone help me ? i am getting this exception when i try to dump my assets `[Leafo\ScssPhp\Exception\ParserException] (stdin) on line 7 at `font-family: @font-family-base`

**Comment by robocoder** [comment]
Do you have a gist that I can look at?  It doesn't sound like you're compiling a .scss file -- rather, it looks like you need a less compiler.

**Comment by ideal-it-solutions** [comment]
THANKS I HAVE DEBUGGED IT. THERE WAS A BUG IN ONE OF MY CCS FILE
