### ISSUE TITLE
"INPUT NOT FOUND" error

### ISSUE THREAD

**Issue by julie2234** [leafo/scssphp#452]
I am using `scss_server::serveFrom` and everything was working at one point, but now I keep getting `/* INPUT NOT FOUND scss v0.0.12 */` and cannot figure out why.

I've tried passing my scss file in `$_SERVER["PATH_INFO"]` as well as the GET p parameter. If I visit the url `.../lib/style.php?p=main.scss` or `.../lib/style.php/main.scss` the css is compiling fine, it just doesn't serve it when I link to this same url in my webpage head tag.

Any help would be appreciated!

![screen shot 2016-07-20 at 11 02 12 pm](https://cloud.githubusercontent.com/assets/5760765/17012676/25d72dd0-4ece-11e6-814e-6a49d84e96ad.png)
![screen shot 2016-07-20 at 11 02 44 pm](https://cloud.githubusercontent.com/assets/5760765/17012675/25d4afb0-4ece-11e6-959e-217b8087118d.png)

**Comment by robocoder** [comment]
When you use the Server class, you have to pass the root directory to the .scss files.

```
use Leafo\ScssPhp\Server;

Server::serveFrom('/path-to-your-stylesheets/');
```
