### ISSUE TITLE
is not working with symfony and sass-rem

### ISSUE THREAD

**Issue by tniemann** [leafo/scssphp#455]
I try to get this runnning with the sass mixin sass-rem (https://github.com/pierreburel/sass-rem)

here is the code in my twig file:

`{% stylesheets filter="scssphp" output="/assets/css/style.css" "@AppBundle/Resources/sass/style.scss" %} <link rel="stylesheet" href="{{ asset_url }}" /> {% endstylesheets %}
`
Here is the sass code:

```
$nav-font-size: 15px; 
@include rem(( font-size: $nav-font-size ));
```

My rem-baseline is:
`$rem-baseline: 16px;`

and this is what comes out:

```
font-size:15px; 
font-size:0.00977rem --> it should be 0.997
```

Calculated rems are to small of factor 100, so if i put 1500 as baseline it works.

When i generate the css file with an other tool or manual everything works fine.

Any idea what cause this?

Regards
Thomas

**Comment by robocoder** [comment]
Maybe you could retry with `master`?  I'm getting the same results with both the latest scssphp and scss (3.4.20).

```
@import 'rem';
$rem-baseline: 16px;

$nav-font-size: 15px; 
div {
@include rem(( font-size: $nav-font-size ));
}
```

Both output:
```
div {
  font-size: 15px;
  font-size: 0.9375rem; }
```
