### ISSUE TITLE
Support 2-space indentation

### ISSUE THREAD

**Issue by michaelk83** [leafo/scssphp#458]
This library is sometimes used to process the `:scss` filter in HAML templates, e.g. with the MtHaml library. HAML's native indentation is 2 spaces, but this library requires 4 spaces. This forces inconsistent-looking code. Please add support for 2-space indentation of the input.

**Comment by robocoder** [comment]
this library doesn't process sass syntax, so it doesn't care about the indentation of the input.

**Comment by michaelk83** [comment]
My mistake, the exception was thrown from MtHaml's `Parser` class. Apologies.
