### ISSUE TITLE
Warning: in_array() expects parameter 2 to be array, boolean given ...

### ISSUE THREAD

**Issue by svratenkov** [leafo/scssphp#461]
You have now these 2 warnings in Compiler.php:
Warning: in_array() expects parameter 2 to be array, boolean given in ...\scssphp-master\src\Compiler.php on line 1465
Warning: in_array() expects parameter 2 to be array, boolean given in ...\scssphp-master\src\Compiler.php on line 1466

In lines:
1465: $isDefault = in_array('!default', $flags);
1466: $isGlobal = in_array('!global', $flags);

Suggest to set error_reporting(-1) to show ALL errors, including warnings.

**Comment by robocoder** [comment]
Please provide a test case. Thanks.

**Comment by robocoder** [comment]
Not reproduceable at this time.

**Comment by svratenkov** [comment]
I investigated the problem a little. Error raises at first var declaration in the imported file, like:
		$banner_gap: 1em;
In this case both compileChildrenNoReturn() and compileChild() parser tree start with:
    0 => array(7) (
        0 => string(6) "assign"
        1 => array(2) (
            0 => string(3) "var"
            1 => string(10) "banner_gap"
        )
        2 => object Leafo\ScssPhp\Node\Number(6) {
            public dimension => string(1) "1"
            public units => array(1) (
                "em" => integer 1
            )
            public type => string(6) "number"
            public sourceIndex => NULL
            public sourceLine => NULL
            public sourceColumn => NULL
        }
        3 => bool FALSE
        -2 => integer 5
        -3 => integer 1
        -1 => integer 7
    ) 
I didn't find the source of this error. But to avoid it you could enhance the condition check replacing
1572                     $flags = isset($child[3]) ? $child[3] : [];
with
1572                     $flags = !empty($child[3]) ? $child[3] : [];

**Comment by svratenkov** [comment]
Sorry, @robocoder, please close this issue. It's my fault. I made a small extension to your compiler. It adds file caching of parsed trees between different compiles. And when I replaced your scssphp v0.6.2 with new v0.6.6 I forgot to clear old file cache. So I compiled mixed trees. Sorry please.

**Comment by robocoder** [comment]
no problem
