### ISSUE TITLE
im having problem import _prefix.scss

### ISSUE THREAD

**Issue by tereaksmey123** [leafo/scssphp#464]
i have no idea why it can't be import 
call php file
```
	require "../../css/scssphp/scss.inc.php";
	use Leafo\ScssPhp\Server;
	use Leafo\ScssPhp\Compiler;
	$scss = new Compiler();
	$directory="stylesheets";
	$scss->setLineNumberStyle(Compiler::LINE_COMMENTS);
	
	$scss->setFormatter("Leafo\ScssPhp\Formatter\Compressed");
	
	$server = new Server($directory, null, $scss);
	$server->serve();
```
_prefix.scss file
```
@mixin border-radius($radius) {
  -webkit-border-radius: $radius;
     -moz-border-radius: $radius;
      -ms-border-radius: $radius;
          border-radius: $radius;
}

@mixin box-shadow($shadow) {
  -webkit-box-shadow: $shadow;
     -moz-box-shadow: $shadow;
      -ms-box-shadow: $shadow;
          box-shadow: $shadow;
}
```
style.scss file
```
@import "prefix.scss";

.loginmodal-container input[type=text]:hover{
		@include box-shadow(inset 0 1px 2px rgba(0,0,0,0.1));
		border:1px solid #b9b9b9;
		border-top:1px solid #a0a0a0;
}
```

**Comment by willpower232** [comment]
I believe the .scss part of the import is to blame.

This line works fine for me in my code: `@import "grid";`

**Comment by tereaksmey123** [comment]
i have already test it be4 without .scss extension it not work only i remove import "prefix"; and copy all code in _prefix.scss file to style.scss it work fine

**Comment by willpower232** [comment]
It might be that you have to specify an import path to be the folder of your stylesheets, or wherever `_prefix.scss` is.

See here [http://leafo.net/scssphp/docs/#import_paths](http://leafo.net/scssphp/docs/#import_paths)

**Comment by tereaksmey123** [comment]
thz @willpower232 cheer just add this problem gone   
`
$scss->setImportPaths("stylesheets/");
`
