### ISSUE TITLE
@function not working as expected

### ISSUE THREAD

**Issue by mikey0000** [leafo/scssphp#465]
```scss
#{$all-buttons}
```
this is within bitters buttons sass which goes all the way back to an @function called _assign-inputs

```
@function _assign-inputs(
    $inputs,
    $pseudo: null
  ) {

  $list: ();

  @each $input in $inputs {
    $input: unquote($input);
    $input: if($pseudo, $input + ":" + $pseudo, $input);
    $list: append($list, $input, comma);
  }

  @return $list;
}
```

**Comment by willpower232** [comment]
whats the error message? it might be that bitters requires ruby so can't work with scssphp...

**Comment by mikey0000** [comment]
might be, I don't know enough about this library to answer that, but I just switched to node sass within the php project. I wasn't getting an error message directly from scssphp sorry.
