### ISSUE TITLE
Compilation problems under Leafo\ScssPhp\Compiler

### ISSUE THREAD

**Issue by gaelhelle** [leafo/scssphp#466]
Hi,

I tried for the first time your script and I have some issues using the Leafo\ScssPhp\Compiler.

Here's my structure : 

```
- compiler/
--- scssphp/
--- compiler.php
--- cssfiles/
------ style.scss
------ imports/
--------- _variables.scss
--------- _base.scss
--------- _mains.scss
--------- _mixins.scss
--------- _normalize.scss
--------- _plugins.scss
```

using:   http://xxxxxx/compiler/compiler.php/style.scss
---
# INSIDE STYLE.SCSS

```
@import "imports/variables";
@import "imports/mixins";
@import "imports/normalize";
@import "imports/base";
@import "imports/plugins";
@import "imports/main";
@import "imports/responsive";
```
---
# INSIDE COMPILER.PHP

Case 1 : Simple server compilation : 
**Input :** 

```
require_once "scssphp/scss.inc.php";
use Leafo\ScssPhp\Server;
$directory = 'cssfiles/';
Server::serveFrom($directory);
```

**Output :** 
http://pastebin.com/r888i7N2

Working good, but no parameters to compress the .css output. Is it possible to add parameters or line number comments if error, with this script ?
---

Case 2 : Trying to use Leafo\ScssPhp\Compiler;
**Input :** 

```
require_once "scssphp/scss.inc.php";
use Leafo\ScssPhp\Compiler;
use Leafo\ScssPhp\Server;
$directory = 'cssfiles/';
$scss = new Compiler();
$scss->setFormatter('Leafo\ScssPhp\Formatter\Compressed');
$scss->setImportPaths('cssfiles/imports/');
$server = new Server($directory, null, $scss);
$server->serve();
```

**Output :** 
http://pastebin.com/RSNBUD9b

This just compile the file style.scss and do not import any file within. Just string with all the imports.
---

Case 3 : Trying to use Leafo\ScssPhp\Compiler with imports in the script;
**Input :** 

```
require_once "scssphp/scss.inc.php";
use Leafo\ScssPhp\Compiler;
$scss = new Compiler();
$scss->setImportPaths('cssfiles/imports/');
echo $scss->compile('@import "variables.scss";');
echo $scss->compile('@import "base.scss";');
```

**Output :** 
http://pastebin.com/f2bSGk1J

This time, imports are working, but if a variable declared in variables.scss is used in base.scss (or other file), the script is not working anymore.
---
- Is it possible to use something like this ?

```
if(APPLICATION_ENV == "dev" || "test"){
<link rel="stylesheet" href="compiler.php/style.scss">
}else{
<link rel="stylesheet" href=style.css">
}
```
---

Please help me using your script,

**Comment by willpower232** [comment]
Case 2 seems to answer Case 1.

In Case 2, you set your imports directory to the imports folder so I reckon you should remove them from the actual `@import` lines, i.e. `@import "imports/variables";` becomes `@import "variables";`

In Case 3, since the files are being compiled separately, the variables from one will not reach the other, you should rely on code in Case 2.

As for your final bullet point, there is nothing stopping you doing that however you would need to come up with a process for caching the output of your SCSS, either manual or programmatic.

Hope this helps.

**Comment by gaelhelle** [comment]
@willpower232 Ok, I managed to make case 2 work with your help.
``require_once "scssphp/scss.inc.php";
use Leafo\ScssPhp\Compiler;
use Leafo\ScssPhp\Server;
$directory = 'cssfiles/';

$scss = new Compiler();
$scss->setFormatter('Leafo\ScssPhp\Formatter\Compressed');
$scss->setImportPaths('cssfiles/imports/');
$scss->setLineNumberStyle(Compiler::LINE_COMMENTS);

$server = new Server($directory, null, $scss);
$server->serve();
``

But for the final bullet point, I'm still trying to find how to rename the compiled .css file for the prod env.

**Comment by willpower232** [comment]
Conveniently, I recently uploaded some of my notes on this subject using a .htaccess rewrite and a bit of PHP which creates or reads a cache file of the compiled SCSS.

[https://github.com/willpower232/howiusescss](https://github.com/willpower232/howiusescss)

**Comment by tereaksmey123** [comment]
@willpower232 not yet test ur howusescss yet but i see code there nice reference ; ) but if i have difference Directory how should i modify them ? httaccess and ...? i want to say i don't know preg_replace rule o.O
```
CSS
--->scss.php
--->Stylesheet
--------------->scss.scss
```

**Comment by robocoder** [comment]
Case 1: the Server class is really only meant to be an example of how to use Compiler and Parser. If you want more control of the compilation, caching, and/or output, you need to use the Compiler and Parser classes directly.

Case 2: you should use absolute paths; relative paths are tricky when serving from the Server class, so if the underlying Parser can't find the file, it falls back to outputting an `@import` statement.

Case 3: the environments are not preserved across compiler() calls. This is probably want to you:
```
echo $scss->compile('@import "variables.scss"; @import "base.scss";');
```
