### ISSUE TITLE
tried Foundation 6.2.1 => scssphp not working :-(

### ISSUE THREAD

**Issue by designerno1** [leafo/scssphp#468]
Hi, i tried compiling a clean foundation 6.2.1 through scssphp and get this error
`Parse error: Undefined variable $i: line: 86`

commenting out all undefined variable errors in grid/_classes.scss
`@include grid-col-size($i);` and others compiles the foundation

looks like a scoping issue maybe you can take a look?

**Comment by garrett-eclipse** [comment]
Same issue being investigated in #446

**Comment by mindeffects** [comment]
The latest version I got running was "foundation-sites-5.5.3".

**Comment by Cerdic** [comment]
Foudation 6.5 is now compiling withour any error and this condition is included in test cases
