### ISSUE TITLE
charset going missing?

### ISSUE THREAD

**Issue by deltamualpha** [leafo/scssphp#469]
Does scssphp not support setting `@charset` anymore? I'm calling `setEncoding('UTF-8');` but don't see the expected `@charset "UTF-8"` in the output.

**Comment by robocoder** [comment]
Sorry, setEncoding() is a hint for parsing the expected input; it has no effect on output and was never documented as such.

**Comment by deltamualpha** [comment]
Ah, OK. There was some example I found that made it seem like it could be used for that. Thanks!
