### ISSUE TITLE
Cant get cache to work

### ISSUE THREAD

**Issue by mrvx** [leafo/scssphp#470]
My setting are in header like so. I want to get cache to work - its quite slow right now.

`

require "scssphp/scss.inc.php";
use Leafo\ScssPhp\Compiler;
$scss = new Compiler();
//$scss->setLineNumberStyle(Compiler::LINE_COMMENTS);

$scss->setImportPaths(**DIR** . '/scss/');

// will search for 'assets/stylesheets/mixins.scss'
$scssIn = file_get_contents(**DIR** . '/scss/pageStyle.scss');

$cssOut = $scss->compile($scssIn);
file_put_contents(**DIR** . '/css/pageStyle.css', $cssOut);`

**Comment by willpower232** [comment]
Your code is probably only half of what you want, you will have to run your code every time you update the SCSS.

I would recommend something like my code here [https://github.com/willpower232/howiusescss](https://github.com/willpower232/howiusescss) which either compiles the SCSS or outputs the CSS depending on the status of the file.

**Comment by robocoder** [comment]
Refer to the Server class for an example on caching.
