### ISSUE TITLE
Quotes error - Interpolation of lists

### ISSUE THREAD

**Issue by maxibanki** [leafo/scssphp#471]
##### Expected behavior

right half of the image
##### Actual behavior

left half of the image
The transform property is in quotes.
##### Reproduce steps

`<link href="{{ [
         'assets/sass/main.scss'
         ]|theme }}" rel="stylesheet">`

=> `@include vendor('transform', 'translateX(#{_size(navPanel)})');`
for example
with other compilers like Scout-app for windows, it works fine.
##### October build

365

![image](https://cloud.githubusercontent.com/assets/17984549/19606316/b589a2fa-97c1-11e6-99d1-df6cf5784e17.png)

**Comment by robocoder** [comment]
Please provide .scss example. Thanks.

**Comment by maxibanki** [comment]
Here is the source file: 
https://html5up.net/alpha/download
File:
assets/sass/main.scss
Line:
1612-1627
for example

**Comment by robocoder** [comment]
Smaller test case:
```
$x: ('a', 'b');
div {
    prop: #{$x};
}
```
Expects:
```
div {
  prop: a, b; }
```

Actual:
```
div {
  prop: 'a', 'b'; }
```
