### ISSUE TITLE
single equals fails to parse in @if

### ISSUE THREAD

**Issue by exactquery** [leafo/scssphp#473]
While this is probably of benefit, it does not match the behavior of the original SASS compiler.  The following will fail to compile:

`@if $x = $y { }`

Obviously, the SCSS author should have written this with == like below, as the single equal sign will not only not work correctly for the if statement, but will likely change the value of $x, which is probably not the intent.  In the case where I discovered it, it was a simple typo.  

`@if $x == $y { }`

Again, the behavior of scssphp may be more desirable than the behavior of the original compiler, as it does catch a 'typo', however since the behavior is different, I thought it might be worth mentioning.

**Comment by robocoder** [comment]
Latest scss reports:
```
Invalid CSS after "@if $x ": expected "{", was "= $y {"
```

So, this is a wontfix.
