### ISSUE TITLE
Line comments not working for @media statements

### ISSUE THREAD

**Issue by gajcapuder** [leafo/scssphp#475]
Easiest way to explain with with a basic example (v0.6.6):

[Source]

header {
	position: absolute;
	width: 100%;
	#logo {
		padding: 30px 0 0 40px;
		img {
			width: 215px;
		}
		@media #{$mobile} {
			padding: 30px 0 0 0;
			text-align: center;
		}
	}
}
#page {
	background: url(/media/dsg/bg.jpg);
}
main .media {	
	.item {
		img {
			@media #{$tablet} {
				max-width: 200px;
			}
			@media #{$mobile} {
				max-width: 140px;
			}
		}
		@media #{$tablet} {
			display: none;
		}
	}
}

[Output]

/* line 1, D:\WWW\projects\detox/media/css/layout.scss */
header {
  position: absolute;
  width: 100%; }
/* line 4, D:\WWW\projects\detox/media/css/layout.scss */
header #logo {
  padding: 30px 0 0 40px; }
/* line 6, D:\WWW\projects\detox/media/css/layout.scss */
header #logo img {
  width: 215px; }

@media (max-width: 544px) {
      header #logo {
        padding: 30px 0 0 0;
        text-align: center; } }
/* line 15, D:\WWW\projects\detox/media/css/layout.scss */
#page {
  background: url(/media/dsg/bg.jpg); }
/* line 18, D:\WWW\projects\detox/media/css/layout.scss */
/* line 19, D:\WWW\projects\detox/media/css/layout.scss */

/* line 20, D:\WWW\projects\detox/media/css/layout.scss */

@media (max-width: 768px) {
        main .media .item img {
          max-width: 200px; } }
  @media (max-width: 544px) {
      main .media .item img {
        max-width: 140px; } }

@media (max-width: 768px) {
      main .media .item {
        display: none; } }

**Comment by Cerdic** [comment]
With #688 the following test case
```
$mobile:'(max-width: 544px)';
$tablet:'(max-width: 768px)';

header {
  position: absolute;
  width: 100%;

  #logo {
    padding: 30px 0 0 40px;

    img {
      width: 215px;
    }

    @media #{$mobile} {
      padding: 30px 0 0 0;
      text-align: center;
    }
  }
}

#page {
  background: url(/media/dsg/bg.jpg);
}

main .media {
  .item {
    img {
      @media #{$tablet} {
        max-width: 200px;
      }
      @media #{$mobile} {
        max-width: 140px;
      }
    }

    @media #{$tablet} {
      display: none;
    }
  }
}
```

gives

```
/* line 4, t475.scss */
header {
  position: absolute;
  width: 100%;
}
/* line 8, t475.scss */
header #logo {
  padding: 30px 0 0 40px;
}
/* line 11, t475.scss */
header #logo img {
  width: 215px;
}
@media (max-width: 544px) {
  /* line 15, t475.scss */
  header #logo {
    padding: 30px 0 0 0;
    text-align: center;
  }
}
/* line 22, t475.scss */
#page {
  background: url(/media/dsg/bg.jpg);
}
/* line 26, t475.scss */
/* line 27, t475.scss */
/* line 28, t475.scss */
@media (max-width: 768px) {
  /* line 29, t475.scss */
  main .media .item img {
    max-width: 200px;
  }
}
@media (max-width: 544px) {
  /* line 32, t475.scss */
  main .media .item img {
    max-width: 140px;
  }
}
@media (max-width: 768px) {
  /* line 37, t475.scss */
  main .media .item {
    display: none;
  }
}
```

I think this could solve the issue, if this match the initial intention (I mean, except if this is not done on purpose at the moment)

**Comment by Cerdic** [comment]
this issue can be closed @robocoder
