### ISSUE TITLE
Crash after nesting import for encapsulation

### ISSUE THREAD

**Issue by imjosecampos** [leafo/scssphp#480]
This eats up all the available memory when trying to encapsulate imports, for example:

.selector {
    @import "styles_to_encapsulate"
}

In a best case scenario I would not have to do this but I need to import bootstrap just for a specific part of a site.

**Comment by dleffler** [comment]
Sounds similar to #380

**Comment by imjosecampos** [comment]
Very familiar, better explained on that issue.
