### ISSUE TITLE
file_exists instead of is_file!?

### ISSUE THREAD

**Issue by tdeuling** [leafo/scssphp#484]
Hi,
there is an is_file() in the following file:
https://github.com/leafo/scssphp/blob/master/src/Compiler.php#L3499

Sometimes, when the file doesn't exist, it throws a warning. Depending on our error handling, it will rise an exception in our frontend.

Couldn't we use a file_exists() instead of an is_file() ?
Link: http://php.net/manual/en/function.file-exists.php

Alternatively we could prefix a '@', so that this warning doesn't throw an exception - for example:
```return @is_file($name);```

**Comment by mahagr** [comment]
Silencing bad code isn't a good idea. It'll slow down the site if error handling is turned on.

**Comment by robocoder** [comment]
What's the warning/exception?  file_exists() returns true for both files and directories, so I don't see how that fixes the underlying cause in your environment.

**Comment by tdeuling** [comment]
is_file() expects an existing resource path. In case that the resource path isn't valid, it will be thrown an E_WARNING (see: http://php.net/manual/en/function.is-file.php#refsect1-function.is-file-errors).

file_exists() will return true for directories as well, you're right.
It seems that we have to check both:
```return file_exists($name) && is_file($name);```

With that code, your method really does what it named for (```protected function fileExists($name)```) - check if a file exists.

**Comment by robocoder** [comment]
Sure. Sounds like a reasonable PR.
