### ISSUE TITLE
Undefined Variable on @import partials

### ISSUE THREAD

**Issue by Lomejook** [leafo/scssphp#488]
Hi guys, I hope you can help me.

I had a folder like this:
![screen shot 2017-01-14 at 5 19 52 pm](https://cloud.githubusercontent.com/assets/8918952/21959487/b5275f74-da7d-11e6-9851-c73f65886288.png)

and inside _bootstrap.scss I have:
![screen shot 2017-01-14 at 5 20 43 pm](https://cloud.githubusercontent.com/assets/8918952/21959507/d2722c94-da7d-11e6-9a58-7b6de59ae877.png)

But the Compiler throws an error saying that the variable` $font-family-base` is undefined when I already initialized inside the first `@import bootstrap\variables`

I made a quick test and all @imports gets ignored

What do I need to do?

**Comment by swashata** [comment]
Hi,

Have you set paths properly? http://leafo.github.io/scssphp/docs/

Quoting from the docs

> When you import a file using the @import directive, the current path of your PHP script is used as the search path by default. This is often not what you want, so there are two methods for manipulating the import path: addImportPath, and setImportPaths.

```php
use Leafo\ScssPhp\Compiler;

$scss = new Compiler();
$scss->setImportPaths('assets/stylesheets/');

// will search for 'assets/stylesheets/mixins.scss'
echo $scss->compile('@import "mixins.scss";');
```

**Comment by robocoder** [comment]
Also, if you had set the import path to "stylesheets/bootstrap" and then @import "_bootstrap", scssphp wouldn't be able to import " bootstrap/variables" because it would be looking for "stylesheets/bootstrap/bootstrap/variables.scss"
