### ISSUE TITLE
CSS Compilation fails when http/s protocal is missing from URL

### ISSUE THREAD

**Issue by sebastianwebb** [leafo/scssphp#491]
This fails: 

background-image: url(**//**localhost:3000/wp-content/themes/twentyeleven/images/comment-arrow.png);

Where as this compiles successfully:

background-image: url(**http://**localhost:3000/wp-content/themes/twentyeleven/images/comment-arrow.png);

Cheers,
Sebastian

**Comment by robocoder** [comment]
The failure is in the parser. It interprets the // as a single line comment.

**Comment by mahagr** [comment]
I think that quoting the string makes it work as we're using `//` protocol in our project:

  background-image: url('//localhost:3000/wp-content/themes/twentyeleven/images/comment-arrow.png');

**Comment by dimitrov-adrian** [comment]
+1
