### ISSUE TITLE
@supports inside a rule: the rule is lost

### ISSUE THREAD

**Issue by Marat-Tanalin** [leafo/scssphp#493]
Testcase:

    A {
        @supports (display: block) {
            background: green;
        }
    }

Expected results (matches SassMeister behavior):

    @supports (display: block) {
        A {
            background: green;
        }
    }

Actual results using scssphp:

    @supports (display: block) {
        background: green;
    }

Workaround for scssphp (fwiw, produces the same result in SassMeister):

    A {
        @supports (display: block) {
            & {
                background: green;
            }
        }
    }

**Comment by Marat-Tanalin** [comment]
Is the project dead?

**Comment by robocoder** [comment]
Sorry, I've been spread thin across all the OSS projects that I contribute to. If anyone is interested in being a more active contributor to this project, hit up @leafo -- I don't have the project admin privs to add committers.

**Comment by varyen** [comment]
Also it breaks CSS in Mobile Safari 9 on iOS. All CSS rules after this incorrectly compiled rule are ignored.

This rule is used in Bootstrap4 so it's pretty important one. :(

**Comment by Cerdic** [comment]
#653 is fixing this issue
