### ISSUE TITLE
compilation fail with bootstrap4

### ISSUE THREAD

**Issue by Draeli** [leafo/scssphp#498]
Hi,
I know bootstrap4 is in alpha but I begin to test and I found a problem with this line :
`// `.class-name { @import "bootstrap"; }`).`
in file **scss/reboot.scss**
I watched quickly in Parser.php and regex seems to be good but I assumed comment isn't remove on first step.
To solve momentarily, I put a space which give me :
`// `.class-name { @ import "bootstrap"; }`).`

FYI, I test with Symfon3.2, I noticed that the erros are not caught (which give me 500 internal error in dev mode)

**Comment by ivanjaros** [comment]
Looks like compiling frameworks is broken right now(since june i think). See #446

**Comment by Cerdic** [comment]
This is now fixed, as well as for Bootstrap or Foundation see #647

**Comment by Cerdic** [comment]
(can be closed @robocoder )
