### ISSUE TITLE
Variables are ignored

### ISSUE THREAD

**Issue by ivanjaros** [leafo/scssphp#499]
I am trying to compile the foundation 6.3.0 and I know this library is broken on for loops, but without grid and flex classes it will compile so for now I am just playing and I have noticed that no matter what I put into Compiler::setVariables() the variables are ignored. I have tried:

```
['white' => '#ff0000']
['white' => '#ff0000 !default']
['white' => '"#ff0000"']
['white' => '"#ff0000 !default"']
```

but none is working. I tried to remove the variable definition(it does not have !default set in there) from settings file to see if setVariables() is being overloaded due to wrong order maybe but if I did that the scss won't compile which indicates that setVariables() is not working at all.

Maybe I am doing something wrong here?

**Comment by robocoder** [comment]
When you use setVariable(), the variable is set before the scss is compiled.

That means any variables in the scss that you want to override need to be defined in the scss with `!default`.  For example:

my.scss:
```
$bg-color: white !default; // background color is white unless already defined thru setVariable()
```
