### ISSUE TITLE
Difficulty getting output formatting to work properly

### ISSUE THREAD

**Issue by djw0510** [leafo/scssphp#501]
I followed the straight-forward documentation and everything is working well for me except for output formatting.  I'm trying to use the "crunched" formatter but all of the formatters seem to output the same exact thing for me.  As far as I can tell there are no errors being produced.

I feel like I'm probably missing something extremely basic and I apologize if that is the case but I have been scouring the net for hours and trying out different things with no luck.

I should also note that I downloaded the source via https://github.com/leafo/scssphp/archive/v0.6.6.tar.gz which is currently linked from http://leafo.github.io/scssphp/#installing.  I then downloaded a copy directly from the GitHub page but I'm still having the same issue.

Please let me know if I can provide any additional information that may assist in debugging the issue.

Thanks!

# Directory Structure
```
- css/
--- style.scss
- inc/
--- scssphp-0.6.6/
- style.php
```

# "style.php" Code
```
require_once "inc/scssphp-0.6.6/scss.inc.php";
use Leafo\ScssPhp\Compiler;
use Leafo\ScssPhp\Server;
$directory = "css";

$scss = new Compiler();
$scss->setFormatter('Leafo\ScssPhp\Formatter\Crunched');
//$scss->setLineNumberStyle(Compiler::LINE_COMMENTS);

$server = new Server($directory, null, $scss);
$server->serve();
```

# CSS inclusion within template
```
<link rel="stylesheet" href="style.php/style.scss" type="text/css"/>
```

# "style.php/style.css" Output (excerpt)
```
/* compiled by scssphp v0.6.6 on Tue, 21 Feb 2017 19:59:39 +0000 (0.1847s) */

* {
  margin: 0;
  padding: 0; }

html {
  height: 100%;
  width: 100%; }
```

**Comment by robocoder** [comment]
You have to clear the scss_cache folder.
