### ISSUE TITLE
Number of precision and layout

### ISSUE THREAD

**Issue by simongcc** [leafo/scssphp#508]
I just meet a case that with the default precision of 5 in `Number.php` inside `node` folder.

```
static public $precision = 9;
```

The default 5 is not enough. The following layout will have a gap if 5 is set.
Example:
```
// scss code
.wrapper {
width: 1170px;
margin: auto;
}

.small-banner {
   $width: 100%/3;
   width; $width;
   height: 100px;
   background: red;
}
...
...
<div class="wrapper">
<div style="width: 1170px; height: 100px; background: green;">something here</div>
<div class="banner-container" style="width: 1170px;">
<div class="small-banner">image here</div><div class="small-banner">image here</div><div class="small-banner">image here</div>
</div>
</div>
```

Under Chrome (I haven't tried other browser yet):
In the example, if precision is 5, the result width will be `33.33333%` showing in Chrome inspector,
the width of the banner would be `389.98px`
and thus, there is a 1px gap at the right side.

So precision at least 6 to settle it in Chrome, I personally set to 9 to avoid other browsers or unknown situation.

**Comment by robocoder** [comment]
The library provides Compiler::setNumberPrecision(), while the `pscss` script provides the `-p` (or `--precision`) option.

The default precision is 5 because that is what the default precision is in ruby `scss` 3.3.

**Comment by willpower232** [comment]
also if you want exact math in CSS you should make use of the calc() function

**Comment by simongcc** [comment]
@robocoder Thanks, you are right, I have modified the plugin which actually I use wp-scss. It use scssphp to work. 

@willpower232 Thanks for your suggestion. If compatibility of browser or browser version is not limited, this is also a convenient way. For instance, I better switch back to offline development using nodejs to compile in order to speed up the development process.

Thanks a lot for your time and effort.

**Comment by killexx** [comment]
Is there a way to set a different precision through Wordpress theme in functions.php without direct modifications in plugin files (which is bad for plugin updates)?
