### ISSUE TITLE
Failed interpolation in placeholder

### ISSUE THREAD

**Issue by GuidoJansen** [leafo/scssphp#510]
The variable interpolation does not work in placeholder, if interpolation directly follows the percent character

This fails with an error 

> "a" failed to @extend "%a". The selector "%a" was not found.: line: 6 

```
$varname: a;
%#{$varname} {
  color: red;
}
a {
  @extend %a;
}
```
If I add an underscore directly after the percent sign, it works:

This works
```
$varname: a;
%_#{$varname} {
  color: red;
}
a {
  @extend %_a;
}
```

The only difference is the underscore

Both of the above work in SassMeister and yield the same CSS code

```
a {
  color: red;
}

```

Please note. The interpolation correctly works for class names and ids
No problem with these: `.#{$varname}` and `##{$varname}`

**Comment by Cerdic** [comment]
Confirmed, still an issue
