### ISSUE TITLE
Input not found when using slash in URL

### ISSUE THREAD

**Issue by JonathanHolvey** [leafo/scssphp#514]
My development server works quite happily with SCSSPHP, but when I pushed it to production I could only get the `/* INPUT NOT FOUND scss v0.6.7 */` error. I happened across a comment in issue #30 which mentioned using `?p=file.scss` rather than `/file.scss` to reference the desired stylesheet. This solved my problem.

The same comment suggests that the cause is due to server configuration, as it may well be in my case, however it took me quite a while to find this solution, since it isn't mentioned in the docs. Better documentation of this alternative configuration would help I imagine. Maybe a FAQ?

Happy it's working now.

**Comment by robocoder** [comment]
Yes, this is a configuration issue. To use `/file.scss`, php expects `PATH_INFO` to be properly set. Since this depends on your PHP and web server configuration, it's outside the project scope.
