### ISSUE TITLE
Unclosed block parsing exception at string escapes

### ISSUE THREAD

**Issue by Kostending** [leafo/scssphp#515]
I'm getting an error when using scssphp to compile the following scss.

`str-insert($str, "\\", 1)`

Produces this error:
```
[Leafo\ScssPhp\Exception\ParserException]
  unclosed block: failed at `` path/to/file.scss on line 42
```

This error only occurs when using scssphp to compile my scss, and if i insert a space afther the "\\" like so
`str-insert($str, "\\ ", 1)`
no exception occurs. 

So i believe this is a parsing error in the compiler, since the escaping should be of the "\\".

**Comment by Defcon0** [comment]
Same here with https://github.com/mdentinho/elegant-icons-sass/blob/master/scss/_utils.scss:

```
@function unicode($str) {
  @return unquote('\'')+unquote(str-insert($str, '\\', 1))+unquote('\'');
}
```
