### ISSUE TITLE
buggy with nested media queries

### ISSUE THREAD

**Issue by cretace** [leafo/scssphp#517]
this:
@media screen and (max-width: 749px) {
     @media screen and (max-width: 600px) and (min-width: 361px) {
		.item {
                      blah
                    }
       }
}
 - - - - - - -
compiles as:
 @media screen and (max-width: 749px)  {
    @media screen  and (max-width: 749px) and (max-width: 600px) and (min-width: 361px)   {
          .item {
                  blah
            }
     }
}

**Comment by Cerdic** [comment]
No longer an issue, #671 is adding a test just in case.

**Comment by Cerdic** [comment]
you can close this issue @robocoder !
