### ISSUE TITLE
How to import scss file with all variables

### ISSUE THREAD

**Issue by oceanwp** [leafo/scssphp#520]
Hello,

I have a little problem, I hope you will be able to help me.

I have created an option page in my theme to allow users to enable/disable all scripts and styles of the theme.
I did it via css files but thanks to scssphp, I can directly do it from my scss files, which will greatly facilitate things :)
The problem is that I can not import my scss file where there are all variables, so when a file has a variable I have the error "undefined variable".

Here is my function to import and compile my scss files:
```
function generate_css() {

	// Sass Compiler (vendor)
	require_once( OE_PATH .'/includes/panel/scssphp/scss.inc.php' );

	// Styles & scripts
	$topBar = self::get_setting( 'topBar_style' );
	$header = self::get_setting( 'header_style' );

	// Get css directory uri
	$pSass 	= OE_PATH .'/sass/';
	$pDir 	= $pSass .'components/';

	// If a style is disabled
	if ( ! $topBar
		|| ! $header ) {

	    // Array
	    $aFiles = array();

		$aFiles[] = $pSass .'_config.scss';
		$aFiles[] = $pSass .'_layout.scss';

		// Load topBar css
		if ( $topBar ) {
			$aFiles[] = $pDir .'topbar/_topbar.scss';
			$aFiles[] = $pDir .'topbar/_topbar-content.scss';
			$aFiles[] = $pDir .'topbar/_topbar-menu.scss';
			$aFiles[] = $pDir .'topbar/_topbar-social.scss';
		}
			
		// Check WP_Filesystem
		global $wp_filesystem;
		self::init_filesystem();

		$scss = new Compiler();
		$scss->setFormatter( 'Leafo\ScssPhp\Formatter\Compressed' );

      	// Get files content
		$strCSS = '';
		foreach( $aFiles as $file ) :
			$strCSS .= $scss->compile( $wp_filesystem->get_contents( $file ) );
		endforeach;

		// Putting all the styles into one CSS file
		$wp_filesystem->put_contents( self::get_file( 'css', 'path' ), $strCSS );
	    
	}

}
```

My file with the variables is "_config.scss", how can I import this file to have no more errors?
Thank you a lot :)

**Comment by willpower232** [comment]
If I'm understanding your code correctly, you compile the SCSS one file at a time. This means you evaluate the variables before they get a chance to work.

You will want to create a long string and then compile that.

**Comment by oceanwp** [comment]
Hello @willpower232, thanks for your reply. Yes, I compile the scss one by one because if a user disables a style, the file will not be included in the final css file.
Do you have any idea how I can make my _config.scss file work in my case?
Thank you a lot :)

**Comment by willpower232** [comment]
Two changes should do it. Firstly remove the compilation from inside the `foreach`:

```$strCSS .= $wp_filesystem->get_contents( $file );```

then after the `endforeach` add the compilation back

```$strCSS = $scss->compile( $strCSS );```

**Comment by oceanwp** [comment]
Hi, it works perfectly now, thank you so much :)
I will win time.
