### ISSUE TITLE
compilation fail with foundation 6.4.1 and breadcrumbs or off-canvas components

### ISSUE THREAD

**Issue by adrienjs** [leafo/scssphp#523]
More precisely scssphp crash with this code :
foundation-sites/scss/components/_breadcrumbs.scss, line 52 :
  $breadcrumbs-item-separator-item-rtl: '\\' !default;

foundation-sites/scss/components/_off-canvas.scss, line 341 :
  @at-root .#{$content}.has-reveal-#{$position} {
    margin-#{$position}: $offcanvas-size;
  }

Comment out these lines makes it possible to compile the project with scssphp.

**Comment by TehTux** [comment]
6.4.3 fails too!
`parse error: failed at $breadcrumbs-item-separator-item-rtl: '\\' !default;`

**Comment by robocoder** [comment]
Also reported in #446

**Comment by Cerdic** [comment]
should be solved now, to be confirmed

**Comment by Cerdic** [comment]
Foundation 6.4.3 & 6.4.1 are now compiling without any modification. 
This can be closed @robocoder
