### ISSUE TITLE
/* INPUT NOT FOUND scss v0.6.7 */

### ISSUE THREAD

**Issue by Lanowaola** [leafo/scssphp#524]
Hi i have problem with leafo/scssphp
They cant take any files to compile...

Here is my code:

require_once '../assets/ola/module/scssphp/scss.inc.php';
use Leafo\ScssPhp\Compiler;
use Leafo\ScssPhp\Server;
$directory = 'cssfiles/';
$scss = new Compiler();
$scss->setFormatter('Leafo\ScssPhp\Formatter\Compressed');
$scss->setImportPaths('a_scss/site/1/index.scss');
$scss->setLineNumberStyle(Compiler::LINE_COMMENTS);
$server = new Server($directory, null, $scss);
$server->serve();
exit;

Thanks for help!

**Comment by robocoder** [comment]
For setImportPaths, you should use an absolute path to a folder, instead of a .scss file.
