### ISSUE TITLE
Parser failing at embedded base64 string

### ISSUE THREAD

**Issue by wout** [leafo/scssphp#526]
I'm getting the following error:

```
parse error: failed at `src: url(data:application/x-font-woff;charset=utf-8;base64,d09GRk9UV.........G3tq36AA==) format('woff'), ` (stdin) on line 262
```

Any idea what could be the problem here?

**UPDATE**

It seems the parser fails even without the base64 data, so this will throw an error too:

```css
src: url(data:application/x-font-woff;charset=utf-8;base64,) format('woff')
```

**Comment by willpower232** [comment]
do you need to include quotes like url('.....')?

**Comment by wout** [comment]
I tried that as well. Singel and double quotes fail too.

**Comment by wout** [comment]
Sorry, this is not an issue. I had a comma at the end of the line instead of a semicolon, which caused the error.

Thanks anyway!
