### ISSUE TITLE
Processing files with base64 embedded data is slow

### ISSUE THREAD

**Issue by wout** [leafo/scssphp#527]
Processing files with base64 embedded data is slow. Sometimes even so slow I get PHP timeouts (more than 30 seconds) with just three embedded fonts (±80Kb each).

I worked around this issue by replacing base64 data with reference keys and storing the references in an associative array. Then processing the SCSS and finally re-inject the base64 data.

To me, this feels like something that should be added to the core. But before putting in the work and creating a PR, I'd like to know if that's something you would accept as a feature.

**Comment by willpower232** [comment]
How many KB is the SCSS file before you take out the base64 parts?

This would be an interesting feature, particularly if one has an SCSS containing many base64 images as well as fonts.

**Comment by robocoder** [comment]
Sounds reasonable for a PR

**Comment by wout** [comment]
Before stripping out five 80 Kb base64 fonts, it's a 407.64 Kb file. So basically there are five fonts with their name variables and a few declarations.

The difference in processing the stripped file and the original one is huge. I am talking 30+ seconds (don't know exactly because of the timeout) to milliseconds a slow machine in development mode.

Although, not sure if I can put in the time for a PR on a short-term basis (swamped with work as you probably all are).

**Comment by robocoder** [comment]
Yup. If you share your fork, I'll take a look.

**Comment by brrn** [comment]
@wout Have you had a chance to dig into this any further? If you have anything you can share, I'd be happy to help.

**Comment by tenold** [comment]
Bumping this.

**Comment by wout** [comment]
@brrn No, I jumped ship and went with the ruby-sass lib which is invoked through a background process using php-resque. With ruby-sass I didn't even have to strip out base64 data or static css, and it was many times faster. Made my code much more maintainable.

**Comment by brrn** [comment]
@wout Makes sense, thanks for the follow up.

**Comment by robocoder** [comment]
Please try out e94a5c2 (driven by necessity when I ran into some 500+KB files where our devs embedded images).
