### ISSUE TITLE
Class scssc doesn't exist.

### ISSUE THREAD

**Issue by WazzaSoft** [leafo/scssphp#529]
I'm trying to get the example working: 

```php
<?php
require "scssphp/scss.inc.php";
$scss = new scssc();

echo $scss->compile('
  $color: #abc;
  div { color: lighten($color, 20%); }
');
```

However, it seems the documentation is outdated or incorrect, as `scssc` doesn't exist.

What is the correct code to get this example working?

**Comment by willpower232** [comment]
The code hasn't changed too much but yes thats out of date now.

Have a look at http://leafo.github.io/scssphp/docs/ which should do the trick.
