### ISSUE TITLE
PHP round function use locale separator in Number

### ISSUE THREAD

**Issue by Arlisaha** [leafo/scssphp#535]
I faced a weird issue when using this lib with Symfony 3 and assetic when I am in dev env. Everytime CSS are compiled "on the fly", I end up with a comma instead of a point as decimal separator. 
I have absolutely no idea why this is happening (my environment is realy locked up and I can't get to know details about configuration).
I forked your repository and made a [custom round method in "Number" class](https://github.com/Arlisaha/scssphp/commit/8b156013747f21b7769f66025670b36dbac6b882). However I am interested if you have any idea to explain this behaviour.

Thank you !

(By the way, I am french and I apologize for my poor english)

**Comment by robocoder** [comment]
Yes, the `round()` function is locale-aware, such that, depending on your locale, you might see ',' instead of '.' as the decimal separator.

However, scssphp has been overriding the locale since version 0.0.3.
* https://github.com/leafo/scssphp/blob/master/src/Compiler.php#L169

Are you sure your dev environment is pulling in the latest version of scssphp?

**Comment by Arlisaha** [comment]
Yes, my composer json requires "0.6.*" and the installed version is "0.6.7". I looked into the code and found the patch you mention. That is why it is bugging me, I cannot get to know why this is happening.
For now, the only thing I could imagine to be responsible for that is that the OS is Windows Server and that their might be some kind of bad magic with it.

**Comment by robocoder** [comment]
Ok, isn't `round()` that's locale-aware -- it returns a `float`. The locale comes into play when the `float` is converted to `string`.

It looks like `setlocale` is process-wide and thus, potentially problematic on Windows for on-the-fly compilation. http://php.net/setlocale

**Comment by robocoder** [comment]
I made some changes to `master`. Feel free to check it out.

**Comment by robocoder** [comment]
Never mind...I'm afk but I see the Travis errors. I'll fix when I get home.

**Comment by robocoder** [comment]
Looks fixed. Thanks.

**Comment by Arlisaha** [comment]
Great thank you a lot, I will try it as soon as I can.

**Comment by Arlisaha** [comment]
It's working perfectly fine, thank you again !
