### ISSUE TITLE
Variables containing comments generate color function errors

### ISSUE THREAD

**Issue by visualcom** [leafo/scssphp#536]
Hi!

I'm developing a Real Time Theme Editor for a project, and using this (amazing) compiler to convert the scss to css.

The scenario is:
- A theme has the styles (scss) with variables (for each tenant app user) stored in database, using key value pars for example: `{"color-header": "#ffffff"}`
- Variables are passed to compiler and css files are generated without problems, so far so good...

When a user start the theme customization (colors, fonts, etc) we have two paths:
1 - At each change, make an ajax call to the server and retrieve the new css (in this case embed inline, overwriting the default theme css) updating the view. Works ok.
2 - At each change, analise (parse) the changes and update the embed styles in real time (at client without ajax calls). It works very smooth with color pickers (sliding quick from one color to another), etc... and offers a very good user experience when playing with the theme.

To make the option 2 possible, I wrap the variable values in scss/css comments, something like: `"color-header": "/*!setting.color-header{*/#ffffff/*}*/"` . This way when css is generated, I have: `h1 { color: /*!setting.color-header{*/#ffffff/*}*/; }`, and is easy to process the user changes in real time using only javascript. At each change just regex globally the key changed, and update the embed styles with the new value.

When the user confirm the changes (only one ajax call), I store the new values in database and generate a clean css (without variable comments)...

The problem is: color functions like *lighten* or *darken* don't understand the syntax with comments (**assertColor** method fails for variables with comments), breaking the compilation.

I'm coming back to option 1, but option 2 was a big (Real Time Preview) step...

Any directions in how to fix this issue? Compiling in npm doesn't throw the error...

Thanks!

**Comment by robocoder** [comment]
Sorry, this is a wontfix.
