### ISSUE TITLE
One parse per webpage visit

### ISSUE THREAD

**Issue by MajkelD** [leafo/scssphp#537]
Hello,

How can I manage to parse my scss file only once per web page?
I want to avoid parsing styles over and over again while visiting another subpages.

My code is looking this way:
```
<?php
    /* placed above the <html> tag */

    require_once "sass/scssphp-0.7.1/scss.inc.php";

    use Leafo\ScssPhp\Compiler;

    $scss = new Compiler();

    $scss->setFormatter('Leafo\ScssPhp\Formatter\Compressed');

    $scss->setImportPaths('sass'); 

?>
```

and 

```
<?php

echo ('<style type="text/css">'.$scss->compile('@import "style.scss";').'</style>');

?>
```

**Comment by MichielioZ** [comment]
First thing that comes to mind is using [sessions](http://php.net/manual/en/session.examples.basic.php).

**Comment by MajkelD** [comment]
> First thing that comes to mind is using sessions.

Thanks, I'll try to figure that out

**Comment by willpower232** [comment]
Surely you want to use some server functionality to generate a CSS file and then include that compiled CSS file?

I generate a CSS file with a filename that includes the modified time of the SCSS file. This means changes are automatically compiled and loaded in the page.

**Comment by robocoder** [comment]
You can use `bin/pscss` to precompile your assets from the command-line/shell.

Or you can look at `example/Server.php` for an example that demonstrates one approach to caching, handling cache headers, etc.

**Comment by jason-engage** [comment]
Does anyone have the code for this already written?

Check Cache -> Compile -> Serve Inline
