### ISSUE TITLE
Inline CSS instead of <link>

### ISSUE THREAD

**Issue by MajkelD** [leafo/scssphp#538]
Hello,
My style.php is looking like this:

```
require_once "sass/scssphp-0.7.1/scss.inc.php";
require_once "sass/scssphp-0.7.1/example/Server.php";

use Leafo\ScssPhp\Compiler;
use Leafo\ScssPhp\Server;

$scss = new Compiler();
$scss->setFormatter('Leafo\ScssPhp\Formatter\Crunched');

$directory = "sass";

$server = new Server($directory, null, $scss);
$server->serve();
```

And then I got this inside of index.php section head:

`
		<link rel="stylesheet" href="style.php/style.scss">
`

Is there any way to put my cached css inline into head?
Thanks

**Comment by willpower232** [comment]
Including a stylesheet as you are currently is the most efficient way of including CSS.

If you wanted to improve it, you could modify your code so it caches the output and only compiles if the SCSS has changed and then only output what is needed.

If you need to inline the compiled CSS you could either ignore the server and include the compilation directly (see https://github.com/leafo/scssphp/issues/537) or you could include some code to check if the SCSS file has been modified (and compile to a CSS file as necessary) and PHP `include()` the CSS file.
