### ISSUE TITLE
Can scssphp be installed without composer?

### ISSUE THREAD

**Issue by samrocks9** [leafo/scssphp#543]
I am using shared hosting, and I would like to start writing my css in sass. I don't have access to the command line, so I can't use composer. Is it possible to install scssphp without composer? If so, how. Thanks!

**Comment by robocoder** [comment]
Yes. You would have to require/include `scss.inc.php`.

**Comment by robocoder** [comment]
Also mentioned in the docs.

http://leafo.github.io/scssphp/docs/

**Comment by samrocks9** [comment]
@robocoder I tried that, do I need to put the rest of the files somewhere?

**Comment by robocoder** [comment]
If you're moving the files around, you'll have to either change the paths in `scss.in.php`, or manually do the `require` or `include` yourself from your application.

**Comment by samrocks9** [comment]
Okay, so by default, I should place a folder called 'src' at the root of my website, and it should work?

**Comment by robocoder** [comment]
scssphp is a library. You need an application to call it. The convention is to put 3rd party dependencies in a `vendor` folder under your application root.

**Comment by samrocks9** [comment]
The guide I am following says this:

Grab the latest SCSSPHP files from the SCSSPHP GitHub repository.

Upload scss.inc.php to your serve somewhere (such as your styles directory).

Create a new file in the same directory called s.php, and put the following inside it:

<?php
require "scss.inc.php";
$scss = new scssc();
$scss->setFormatter("scss_formatter_compressed");
$server = new scss_server("stylesheets", null, $scss);
$server->serve();
?>
Now, make a directory called stylesheets and make it so that the s.php script can write to it. Upload your .scss files to the stylesheets directory.

You should now have something like the following:

css/
    s.php
    scss.inc.php
    stylesheets/
        style.scss
Now, instead of linking to your .css files in your HTML, you link to the s.php script, and specify the .scss file to load:

<link rel="stylesheet" href="css/s.php/style.scss" />

**Comment by robocoder** [comment]
Sorry, that's an outdated, unofficial, unsupported guide that won't work with the latest version of `scssphp`.

**Comment by samrocks9** [comment]
Oh, okay.

**Comment by samrocks9** [comment]
I already have a vendor folder, so should I put all the scssphp files in a folder under vendor?

**Comment by robocoder** [comment]
If you're not using composer, you're welcome to put the files anywhere you want. The composer convention would look like `vendor/leafo/scssphp`.

**Comment by samrocks9** [comment]
Is there any difference between downloading the zip from GitHub vs the tar.gz from the website?

**Comment by robocoder** [comment]
I just tagged master, so at this point, there shouldn't be a difference.
