### ISSUE TITLE
extend compiler error

### ISSUE THREAD

**Issue by of2607** [leafo/scssphp#544]
There is my scss:

```
%red{
	color: red;
}
%basic{	
	.red{
		@extend %red;		
		background:#fff;
	}
}
.test{	
	@extend %basic;
}

```
I need this result:
```
.test .red { 
color:red;
background: #fff; 
}
```
But I get this result:

```
.test .red {
  background: #fff; 
}

```

please help me thank you

**Comment by willpower232** [comment]
This seems to have cropped up in recent versions, if I try this in a much older version I get the following which matches how sass converts it:

```
.test .red{color:red;}
.test .red{background:#fff;}
```

The only reference to the much older version number is `static public $VERSION = 'v0.1.1';` in `Compiler.php`

**Comment by Cerdic** [comment]
With #681 this is fixed and I now have:
```
.test .red {
  color: red; }

.test .red {
  background: #fff; }
```

**Comment by Cerdic** [comment]
This one can be closed also @robocoder
