### ISSUE TITLE
Bugs in source map generation

### ISSUE THREAD

**Issue by mahagr** [leafo/scssphp#546]
It looks like that source map generation needs some more work. 

`SourceMapGenerator::generateJson()` uses `$sourceMap['sources']`, but there is no `sources` in the `$defaultOptions` variable. I'm not sure if the variable should be there or if the lines are something that can be removed.

Additionally, it looks like that source map JSON generation needs `Compiler::setSourceMapOptions()` to be called for every generated CSS file as I'm getting `The directory "" does not exist. Cannot save the source map..` exception.

**Comment by robocoder** [comment]
Cc @dleffler

**Comment by dleffler** [comment]
Odd, works for me, using it locally...all I did was add the saveMap() method and option into the existing inline sourcemap code.

**Comment by dleffler** [comment]
FYI, $sourceMap['sources'] are added by the addMapping() method call within the Formatter?

I can't comment on the options call as my code only sends processes a single file per call, so the environment is set each time I call the compiler (e.g., I don't call it with an array of filename and loop through the $scss->compile() call)...however having said that, it appears the \Leafo\ScssPhp\Compiler() would maintain options between calls to compile() unless you destroy/reinstantiate the object?

**Comment by dleffler** [comment]
Actually, in the latest code (0.7.3), I've noticed the $sourceMap['sources'] population code was removed, which is the issue.

```
        // A list of original sources used by the 'mappings' entry.
        $sourceMap['sources'] = array();
        foreach($this->sources as $source_uri => $source_filename) {
            $sourceMap['sources'][] = $this->normalizeFilename($source_filename);
        }
```
should be added after the $sourceMap['sourceRoot'] is set in SourceMapGenerator.php (possible editing error?)

**Comment by dleffler** [comment]
I've created a pull request #547 to address the code change (reversal) needed.

**Comment by robocoder** [comment]
Weird...I don't see the population code in the original PR. https://github.com/leafo/scssphp/pull/545/files#diff-09278961921b2e22cc08dec07581481f

Before I merge and re-tag, is there anything else missing?

**Comment by dleffler** [comment]
My pull may NOT be fully complete...but to check, the generateJson() method must contain

```
        $root = $this->options['sourceRoot'];
        if ($root) {
            $sourceMap['sourceRoot'] = $root;
        }
```
and
```
        $sourceMap['names'] = array();
```
and
```
        $sourceMap['sources'] = array();
        foreach($this->sources as $source_uri => $source_filename) {
            $sourceMap['sources'][] = $this->normalizeFilename($source_filename);
        }
```

**Comment by dleffler** [comment]
I've updated my fork with the fix for the pull request

**Comment by dleffler** [comment]
BTW, that code came from the inline source map pull request not my pr to add file based source maps.

**Comment by robocoder** [comment]
OIC. Thanks. Looks like I fat fingered something during my cleanup.

**Comment by robocoder** [comment]
Merged

**Comment by chrisblakley** [comment]
Was there a fix for the need to call `Compiler::setSourceMapOptions()` for every generated CSS file, or should I update my code to do so? I'm also getting the `directory "" does not exist` fatal error.

**Comment by dleffler** [comment]
As stated above, I do not experience the 'options' issue, and by looking at the code, the options should remain intact as long as the compiler object remains intact.
