### ISSUE TITLE
Fixed PHP Warning

### ISSUE THREAD

**Issue by masouddarvishi92** [leafo/scssphp#557]
PHP Warning:  in_array() expects parameter 2 to be array, boolean given in /home2/public_html/wp-content/themes/theme/includes/ratings.php on line 173

``	$disabled = false;
			if(get_post_meta($id, '_kksr_ips', true))
			{
				$Ips = unserialize(base64_decode(get_post_meta($id, '_kksr_ips', true)));
				$ip = $_SERVER['REMOTE_ADDR'];
				if(in_array($ip, $Ips))
				{
					$disabled = true;
				}
			}
``
line 173 = if(in_array($ip, $Ips))

**Comment by masouddarvishi92** [comment]
[ratings.zip](https://github.com/leafo/scssphp/files/1744251/ratings.zip)

**Comment by masouddarvishi92** [comment]
Please solve this problem. Thanks

**Comment by vita10gy** [comment]
Make line 173 
if(is_array($Ips) && in_array($ip, $Ips))

That said I think you're in the wrong project friendo.

**Comment by masouddarvishi92** [comment]
very nice! thankyou.

How can I remove base64_encode codes in this file without any problem?
