### ISSUE TITLE
Bracketed lists do not compile

### ISSUE THREAD

**Issue by pkerling** [leafo/scssphp#558]
According to [SASS documentation](https://sass-lang.com/documentation/file.SASS_REFERENCE.html#bracketed_lists), lists can also be written with brackets, i.e. like this: `$list = [1, 2, 3];`, but scssphp will give a generic "parse error" then. `$list = (1, 2, 3);` on the other hand works fine.

**Comment by umakantp** [comment]
When is thing feature going to be ready? Any timelines ?

**Comment by niaccurshi** [comment]
This has been updated/fixed as part of code changes with #593

**Comment by Cerdic** [comment]
looks like the patch is somewhere here https://github.com/leafo/scssphp/pull/593/commits/a8553aa54118ca4d34325041e100d29c38d69303#diff-1041b02aae148a89853dc0d2710afc9cL1217
