### ISSUE TITLE
abs() should not mutates variable.

### ISSUE THREAD

**Issue by vicary** [leafo/scssphp#560]
When I was working on bootstrap scss, specifically [_functions.scss:83](https://github.com/twbs/bootstrap/blob/3be511264c16404d5a741c3f6ec0c5c39bddaaa1/scss/_functions.scss#L83) changes the value of `$level` and thus only the first invocation yields expected result.

I tried changing the file to directly use the return value instead of variable assignment, but it still fails.

**EDIT**: Changing the line to `$level: if($level > 0, $level, $level * -1);` fixes the problem, confirming it is about `abs()`.

**Comment by robocoder** [comment]
I thought we fixed this in #551.

**Comment by dleffler** [comment]
Yes, but it's not in the most recent release version, pushed after the last release.

**Comment by robocoder** [comment]
I can't reproduce this in v0.7.5.

**Comment by vicary** [comment]
Confirmed working in 9410cbb398, and a duplicate of #551. Closing this.

Thank you for the hard works!
