### ISSUE TITLE
I don't quite get how it works locally

### ISSUE THREAD

**Issue by orso081980** [leafo/scssphp#561]
I'm trying to deploy it locally on my machine.

In my index.php file I added the reference

```
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Document</title>
    <!-- <link href="/s.php/style.scss" rel="stylesheet"> -->
    <!-- <link href="/assets/css/s.php/general.scss" rel="stylesheet"> -->
    <link href="scss.inc.php/style.scss" rel="stylesheet">
</head>
```

The structure of my root folder is the following:

```
root
--bin
--example
--src
composer.json
index.php
scss.inc.php
style.scss
```

With the hope that this script will take care of my sass file and translate into a css file but nothing happens. The problem with the documentation is that it's very basic. Do I have to compile the php framework in any way to make it readable by my local server? I have a sort of compile-file of the very framework but it's a very old version and it's not going to read my source-map.

Am I missing something?

**Comment by willpower232** [comment]
Please re read the documentation, the library is called in using `scss.inc.php` and then made use of in code, you can't just use a URL like that unfortunately
http://leafo.github.io/scssphp/#scssphp-library-reference

**Comment by orso081980** [comment]
In the doc is written:

SCSSPHP Library Reference
Complete documentation for scssphp is located at /scssphp/docs/.

To use the scssphp library either require scss.inc.php or use your composer generated auto-loader, and then invoke the Compiler class:

I assume that I have to follow one procedure or another.

Since I'm following the procedure which avoids the compiler I created some other files:

Style.php:

```
<?php
$directory = "stylesheets";

require "scssphp/scss.inc.php";


// $scss = new scssc();
// $scss->setFormatter("scss_formatter_compressed");
// $server = new scss_server(".", null, $scss);
// $server->serve();


scss_server::serveFrom(".", null, $scss);
```

And I added this line to the composer.json

```
"require": {
        "php": ">=5.4.0",
        "leafo/scssphp": "0.7.5"
    },
```
My index.html file is:

```
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>Document</title>
	<link rel="stylesheet" href="style.php/style.scss">
</head>
<body>
	ciao
</body>
</html>

```
Then I added my .scss file in the root folder and now the root folder looks like something like that:

root
--bin
--example
--src
composer.json
index.hml
scss.inc.php
style.php
style.scss

But still I'm receiving a 500 error -> net::ERR_ABORTED

**Comment by robocoder** [comment]
You're referring to out-dated docs. `scss_server` doesn't exist in the latest release.

Because of the security implications (justified or not), the Server class was moved to the example folder, and is no longer included in scss.inc.php.

If you choose to use it, start off with:
```
require "scss.inc.php";
require "example/Server.php";

$server = new \Leafo\ScssPhp\Server;
$server->serve();

```

**Comment by orso081980** [comment]
I'm testing, but I still get this error:

localhost/:6 GET http://localhost/scssphp-0.7.5/scssphp-0.7.5/style.php/style.scss net::ERR_ABORTED

**Comment by orso081980** [comment]
Thank you anyway in helping me in debugging

**Comment by robocoder** [comment]
I wish I could assist more, but it's proven difficult to support the sheer number of php.ini settings (and combinations) that can affect functionality, performance, and security of the Server class. Look at phpinfo() output in your browser as php-fcgi/mod-php  may be configured differently than pgp-cli, e.g., umask, safe mode, open base dir, max execution time, memory limit, disabled functions.
