### ISSUE TITLE
Compress file and sourcemap don't work together

### ISSUE THREAD

**Issue by orso081980** [leafo/scssphp#562]
I was finally able to deploy my file version with composer.

In order to avoid the flag of the version not supported of my configuration I simply add a wild card to my scssphp version like that:

`"leafo/scssphp": "*"`

Now I've got a problem though. I'm not able to use the combo sourcemap and the file compressed. If I choose to use both, I won't be able to easily debug my scss file because, with the compression the track of the line of css is lost.

Here's my configuration file:

```
require_once "scss.inc.php";
require_once "example/Server.php";

use Leafo\ScssPhp\Compiler;
use Leafo\ScssPhp\Server;

$scss = new Compiler();
$scss->setSourceMap(Compiler::SOURCE_MAP_INLINE);
// $scss->setFormatter('Leafo\ScssPhp\Formatter\Compressed');

$server = new Server(".", null, $scss);
$server->serve();
```
In the past, to develop a sass environment I used grunt and nodesass, but now I work in a LAMP environment so I'm using php.

Is it a debuggable problem? Thank you in advance

**Comment by orso081980** [comment]
Last question:

I'm wondering if I can compress my code in a development environment, in order to have a reasonable number of files, instead of upload all the folders and the file. One of my coworker, with a previous version of scssphp was able to use only two files in order to deploy the system onlyne, scssphp.ini.php and the style.php file

**Comment by robocoder** [comment]
The old single .php file was handy for deployment but much less so for development.

You're welcome to concatentate the .php files (in the order shown in `scss.inc.php`), keeping only the first `<?php` tag, to deploy as a single file on your server.

**Comment by dleffler** [comment]
I've run several tests of different configurations, and in the more current versions of scssphp the sourcemap feature works for both output types (inline and file) with several methods of output formatting including Condensed. I had no problem pulling up the correct .scss file/line in modern browsers like Chrome. Therefore the sourcemap feature works when turned on with Condensed format output.

If on the other hand you need to do manual/visual debugging, then selecting 'Condensed' is probably not the best output method since it is output as a single line....perhaps the 'Format' or '{ }' command would help you as it will uncompress the file in the browser developer window.

**Comment by imlinus** [comment]
Sorry for late answer. But I think someone might find it useful.

Personally I use a `$inSandbox` variable which is only set in my sandbox server (to true)
Then I just do a quick `if (isset($inSandbox)) Scss::compile()`, and then run the compiler.
It will recompile on every refresh (which is what I want during development)
Then when live, it uses the last compiled .css file until I push something new.

```
class Scss {
  
  static public function compile () {
    try {
      
      $scss = new Compiler();
      $scss->setFormatter('Leafo\ScssPhp\Formatter\Compressed');
      $scss->setSourceMap(Compiler::SOURCE_MAP_INLINE);
      $scss->setImportPaths('scss/');

      $string_css = $scss->compile('@import "stylesheet.scss";');
      file_put_contents('css/stylesheet.css', $string_css);

    } catch (\Exception $e) {
      die('SCSS Compilation gone wrong: ' . $e);
    }
  }

}
```

Sourcemaps, compressed and doesn't recompile for live users, just the dev.
Of course it's ugly, It's PHP. Don't expect something wonderful, just expect it to work.
