### ISSUE TITLE
Warning on block comments within @mixin

### ISSUE THREAD

**Issue by mehdiym** [leafo/scssphp#566]
Hello and thx for your lib!

Each time I have such a comment, eg.

`
@mixin foo() {
  /* some comment */
}
`

I get the following warning:

`[Mon Mar 26 15:42:05.503789 2018] [:error] [pid 1169] [client xxx] PHP Notice:  Trying to get property of non-object in /%path%/vendor/leafo/scssphp/src/Compiler.php on line 321, referer: http://localhost/
`

And indeed `$this->env->block` is null.

It's just a warning but as a consequence, my next header() calls complains:

`Cannot modify header information - headers already sent by (output started at /%path%/vendor/leafo/scssphp/src/Compiler.php:319)`

And it breaks my layout.

**Comment by mixahlos** [comment]
I have exactly the same problem.

**Comment by robocoder** [comment]
Is this fixed by #570?
