### ISSUE TITLE
example/Server.php, timezone setting really needed?

### ISSUE THREAD

**Issue by sebknzl** [leafo/scssphp#568]
At the bottom of example/Server.php, there's a check whether "date.timezone" is set in the ini file.

I don't think this is necessary, as I can't see any code that deals with the local time zone. filemtime()  and the timestrings for HTTP-Caching are UTC.

**Comment by willpower232** [comment]
Arguably, the references to `GMT` in the last modified headers could be replaced by adding the `e` to the date format so that if you are in a different timezone, or relying on whatever is configured (or not) in php.ini, the output of the code is still accurate.

**Comment by sebknzl** [comment]
Hi Will!

Last-Modified must always be GMT, see https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Last-Modified .

**Comment by willpower232** [comment]
Ah well every day is a school day!

There is a reference to a date here:
https://github.com/leafo/scssphp/blob/89d9dabd18f8f068c62d7d0949da0c608ae5ed94/example/Server.php#L210

So its slightly useful but if you're using PHP without a `date.timezone` set then you may have other issues already...

**Comment by robocoder** [comment]
IIRC it was to avoid notices introduced in php 5.3, e.g.,

> PHP Notice: in file xxxxx on line yy: date(): It is not safe to rely on the system’s timezone settings. You are *required* to use the date.timezone setting or the date_default_timezone_set() function. [...]

In hindsight, it was the wrong fix.
