### ISSUE TITLE
Not able to render nathansmith/unsemantic

### ISSUE THREAD

**Issue by Aybee** [leafo/scssphp#572]
Just a note that this CSS grid framework can not be compiled with leafo/scssphp
https://github.com/nathansmith/unsemantic/issues/100#issuecomment-386139971

**Comment by robocoder** [comment]
Is that with the current version of scssphp? Did you use `bin/pscss` or call the library by some other means? Can you provide a source file or minimal test case to reproduce the problem you observed?

**Comment by Aybee** [comment]
I tested with version `^0.6`. `0.6.7` is installed. Now I've done a test with `0.7.5` but it's the same.

I use it with Contao CMS 3.5.35
 - Contao LTS 3.5.35 - `^0.6`
 - Contao LTS 4.4.18 - `^0.6`
 - Contao 4.5 - `^0.7`

https://github.com/contao/core/blob/3.5.35/composer.json

I don't know if pscss is in action. Here is the code where scssphp is in action
https://github.com/contao/core/blob/3.5.35/system/modules/core/library/Contao/Combiner.php#L13
https://github.com/contao/core/blob/3.5.35/system/modules/core/library/Contao/Combiner.php#L329-L370

If you like to test you easily can install a 3.5.35 by uploading and runing example.org/contao/install.php (you need a database).
https://contao.org/en/download.html See down below "Older versions".

If you like to do this I can easily create a page for you and set up to use the unsemantic.scss in FE.

**Comment by Cerdic** [comment]
Confirmed and can be reproduced by putting https://github.com/nathansmith/unsemantic/tree/master/assets/sass in `unsemantic/` folder and running:

```
$ ../bin/pscss unsemantic/unsemantic-grid-base.scss

Fatal error: Uncaught Leafo\ScssPhp\Exception\CompilerException: ".grid-container" failed to @extend "%grid-container". The selector "%grid-container" was not found.: partials/_unsemantic-vars.scss on line 356 in /Users/cedric/Sites/scssphp/src/Compiler.php:3919
Stack trace:
#0 /Users/cedric/Sites/scssphp/src/Compiler.php(368): Leafo\ScssPhp\Compiler->throwError('".grid-containe...')
#1 /Users/cedric/Sites/scssphp/src/Compiler.php(344): Leafo\ScssPhp\Compiler->missingSelectors()
#2 /Users/cedric/Sites/scssphp/src/Compiler.php(205): Leafo\ScssPhp\Compiler->compileRoot(Object(Leafo\ScssPhp\Block))
#3 /Users/cedric/Sites/scssphp/bin/pscss(211): Leafo\ScssPhp\Compiler->compile('@import "partia...', 'unsemantic-grid...')
#4 {main}
  thrown in /Users/cedric/Sites/scssphp/src/Compiler.php on line 3919
```

**Comment by Cerdic** [comment]
This could be linked to #510

**Comment by Cerdic** [comment]
Was definitely linked to #510: with #691 you don't have the Exception anymore… 
but the compilation seems never finish, looks like it's stuck in an infinite loop somewhere…

**Comment by Cerdic** [comment]
#691 fix this one also then

**Comment by Cerdic** [comment]
this issue can be closed @robocoder

**Comment by Aybee** [comment]
I did not test your changes but thank you very much for your effort.
