### ISSUE TITLE
"transparentize" renders invalid CSS

### ISSUE THREAD

**Issue by leonardfischer** [leafo/scssphp#573]
Hello,

the `transparentize` function does not work properly and renders invalid CSS like `rgba(255, 255, 255, 0,5)`.

```php
$scss = new Compiler();

echo $scss->compile('a { color:transparentize(rgba(255,255,255,1), 40%); }');
echo $scss->compile('a { color:transparentize(#fff, 40%); }');
echo $scss->compile('$white: #fff; a { color:transparentize($white, 40%); }');
```

All three lines will result in:
`a{color:rgba(255, 255, 255, 0,6)}`

Instead of:
`a{color:rgba(255, 255, 255, 0.6)}`

**Comment by robocoder** [comment]
What version of scssphp are you using?  In v0.7.2, we switched to using `number_format` instead of relying on the locale.

**Comment by leonardfischer** [comment]
Hi there, sorry I forgot to mention the version!
I'm using scssphp v0.7.5 and compile the CSS via CLI which is running PHP 7.1.7

Running `$ php -r "echo setlocale(LC_ALL, 0);"` outputs `C/de_DE.UTF-8/C/C/C/C`

**Comment by robocoder** [comment]
Hmm... I couldn't reproduce this with PHP 7.1.7 and scssphp v0.7.5.
```
<?php
include __DIR__ . '/scss.inc.php';

setlocale(LC_ALL, 'C/de_DE.UTF-8/C/C/C/C');

$scss = new \Leafo\ScssPhp\Compiler();

echo $scss->compile('a { color:transparentize(rgba(255,255,255,1), 40%); }');
echo $scss->compile('a { color:transparentize(#fff, 40%); }');
echo $scss->compile('$white: #fff; a { color:transparentize($white, 40%); }');
```
outputs:
```
a {
  color: rgba(255, 255, 255, 0.6); }
a {
  color: rgba(255, 255, 255, 0.6); }
a {
  color: rgba(255, 255, 255, 0.6); }
```

**Comment by leonardfischer** [comment]
Strange: I can't reproduce it at home - here I'm using PHP 7.0.27 on win10.
I will debug this on tuesday and post my results here ;)

Right now it seems as if `$value[4]` in `\Leafo\ScssPhp\Compiler->compileValue` contains a string instead of a float value. Also there is no use of `number_format` - the variable simply gets concatenated in the rgba-string on line 2697: 

`return 'rgba(' . $r . ', ' . $g . ', ' . $b . ', ' . $value[4] . ')';`

**Comment by robocoder** [comment]
I committed a possible fix. I'm afk, so will test it later tonight.
