### ISSUE TITLE
Source Map does not work

### ISSUE THREAD

**Issue by ghost** [leafo/scssphp#581]
The [documentation on source maps](http://leafo.github.io/scssphp/docs/#source-maps) is missing the important part for options.

I want to create inline source maps and tried the following:

```php
$scss->setSourceMap( Compiler::SOURCE_MAP_INLINE );
```

This gives me the error that needle for `strpos()` in file `scssphp/src/SourceMap/SourceMapGenerator.php` on line **306** is empty.

Yeah, I need to set some options but what are the right ones?

```php
$scss->setSourceMapOptions( array(
    // What to do in here?
) );
```

The [wiki](https://github.com/leafo/scssphp/wiki/Source-Maps) is not really helpful (uses a constant for `setSourceMap`?!) and [this comment](https://github.com/leafo/scssphp/issues/135#issuecomment-343173184) doesn't work.

My setup for WordPress:

- Import paths set to `TEMPLATE_DIR . '/assets/css/scss/'` > resolves to `/var/www/virtual/USER/ROOT/wp-content/themes/THEME/assets/css/scss`.
- Source file lives in the same folder.
- Final file will be saved to `TEMPLATE_DIR . '/assets/css'`.
- Formatter is set to `Crunched` – other formatters don't work either.
- Setting some variables via `theme_mods`.
- Child theme adds import and source file paths for the child theme directory.

Compilation, `@import`, formatting and the variables are working flawless. But not the source maps.

So, how do I properly add source maps?

**Comment by dleffler** [comment]
I've updated my sourcemap wiki note using the comments from the SourceMapGenerator.php file

**Comment by gwillings** [comment]
@crstnio Are you still having trouble with this? I believe I have it working inline. I've also submitted a pull request to fix the `strpos()` error you encountered.

My code looks a bit like this:

```php
$scss = new Compiler();
$scss->setSourceMap(Compiler::SOURCE_MAP_INLINE);
$scss->setSourceMapOptions([
    'sourceMapBasepath' => PUBLIC_PATH
]);
$scss->addImportPath(PUBLIC_PATH);
$scss->setFormatter(Expanded::class);
$source = $scss->compile($this->source, $this->staticFileRequest->getScssUriPath());
```

It does not seem to be working when I tested in Chrome. 

The thing that fixed it for me was the second parameter to the `compile()` method.
