### ISSUE TITLE
loss of performance since version 0.7.5 ?

### ISSUE THREAD

**Issue by anthonymorel** [leafo/scssphp#584]
Hi !
Has someone noticed a great loss of performance since version 0.7.5 ?

Fatal error: Maximum execution time of 30 seconds exceeded in /leafo/scssphp/src/Compiler.php on line 3660

on my system about 10 seconds with 0.7.4 ==> 35 seconds with 0.7.5

**Comment by robocoder** [comment]
Can you use git-bisect to find the commit that caused this regression?

**Comment by anthonymorel** [comment]
Hello,

git-bisect gave me the following commit : 
https://github.com/leafo/scssphp/commit/593b92929c3f0e9d82c84ace7d29e8550e386413

**Comment by bretto36** [comment]
@robocoder - any idea when these things will be looked at?

**Comment by robocoder** [comment]
593b929 fixes #551 - library functions that incurred side-effects when the runtime returned modified lvalues. There is no alternate fix at the moment.

**Comment by bretto36** [comment]
I wouldn't have thought that would have caused so much slowness. I might look into it a bit too

**Comment by bretto36** [comment]
I've just tested locally on each version from 0.7.7 down to 0.6.7 and the timing was the same. So i wasn't able to narrow it down to a particular version change for my tests.
