### ISSUE TITLE
escape character in strings is kept in the final result

### ISSUE THREAD

**Issue by Netmosfera** [leafo/scssphp#586]
```
$foo: "\
div > p, \
div > h1 \
";

#{$foo} {
  & > strong {
    color: red;
  }
}
```

should result in

```
div > p > strong, div > h1 > strong {
  color: red;
}
```

result is instead ( "\\" are kept)

```
\
div > p > strong,
\
div > h1 \
 > strong {
	color: red;
}
```

**Comment by Cerdic** [comment]
Hmmm… I have this patch that fix the issue (ok should be better to work with all kind of newline chars)
```
$ git diff
diff --git a/src/Parser.php b/src/Parser.php
index 076f162..5dd0d40 100644
--- a/src/Parser.php
+++ b/src/Parser.php
@@ -1918,6 +1918,8 @@ class Parser
                     $content[] = $m[2] . "'";
                 } elseif ($this->literal("\\", 1, false)) {
                     $content[] = $m[2] . "\\";
+                } elseif ($this->matchChar("\n", false)) {
+                    // ignore
                 } else {
                     $content[] = $m[2];
                 }
```

But then

```
#values {
  content: "This is a \
singleline string.";
  content: "This is a
multiline string.";
}
```

will gives

```
#values {
  content: "This is a singleline string.";
  content: "This is a
multiline string."; }
```

which is not matching  the test added in https://github.com/leafo/scssphp/commit/39b58546e61476e4ee9cb31eb4c9550ff55329d1 for #164 

I don't believe we should have a different behaviour from the string context. 
Or is it in the interpolation result that the backslash-newline should be removed? Seems a bit weird.

**Comment by Cerdic** [comment]
Hmm I think I'm getting it - we have two levels of evaluation of the backslash: the compiler for the one in the var and the browser for the one in the content string property.

So i guess that here, this is in the Compiler output that a \n in a string should be re-escaped with a backslash for the browser

**Comment by Cerdic** [comment]
Sorry, some loud thinking :)

So it appears the `backslash-newline` is processed by the browser the same way we would do in the compiler with the proposed patch.
In other words, in CSS, the two following lines are equivalent:
```
  content: "This is a single\
line string.";
  content: "This is a singleline string.";
```

So I think we can safely change the output of the test, considering the compiler always process the `backslash-newline` and having a reliable behaviour
