### ISSUE TITLE
Compressed Formatter + Bootstrap 4 problem

### ISSUE THREAD

**Issue by Tomm96** [leafo/scssphp#589]
Hello,

I want to report a possible bug. If you are using Compressed/Crunched formatter and Bootstrap 4, then you might have problems with loading css on your iPhone, iOS9. 

In my case, I'm using latest scssphp version (0.7.6) and Bootstrap 4.1.2 (scss files) and on my iPhone (iOS9) bootstrap loads partly correctly and the other css files don't load at all. 

Everywhere, except (as far as I noticed/tested) iOS 9 devices, css files were loading correctly.

I changed formatter to "Nested" or "Compact" and the problem was gone. So, this solution led me to conclusion, that something is wrong with formatter.

I need to use "compressed" format, please fix it.

Thank you.

**Comment by dleffler** [comment]
Is it possible iOS9 (which is really obsolete) requires a semicolon to end a style statement? These are removed by the compressed formatter.

**Comment by Tomm96** [comment]
I don't think so, because I tested the same thing with already compiled [bootstrap.min.css](https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css) and it worked well.

**Comment by Cerdic** [comment]
There is definitely not enough information in this issue to work on it. 

My guess is even if the compilation of BS4 was working, it was producing some invalid code somewhere, wich one iOS9 was not able to deal with, stopping the parsing of the line - then of the file if using Compressed format.

It should be confirmed now with a checked and working compilation of BootStrap that produce a fully valid output.
Meanwhile I think this issue can be closed

**Comment by robocoder** [comment]
I'll leave this issue open a bit longer for feedback from the OP.
