### ISSUE TITLE
PHP 7.1.20 suddenly returns 'No input file specified.' for all my .scss files

### ISSUE THREAD

**Issue by Blastius** [leafo/scssphp#592]
(I'm using scssphp v0.7.7, also tested with v0.7.6, v0.7.5 and v0.7.4)
My local vagrant homestead server updated PHP to 7.1.20 and after this, every project returns **No input file specified.** after looking into the rendered .scss file. Everything still worked fine on PHP 7.1.19. My .htaccess already has
```
RewriteEngine on
RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d
RewriteRule ^(.*)$ index.php?/$1 [L]
```
Does somebody have a workaround? It isn't really easy to set PHP back to 7.1.19 on vagrant/homestead..

**Comment by robocoder** [comment]
You should start with comparing the php.ini config between 7.1.19 and 7.1.20.

**Comment by Blastius** [comment]
Those are identical (https://github.com/php/php-src/compare/PHP-7.1.19...PHP-7.1.20).

**Comment by robocoder** [comment]
I'm using 7.1.23 and haven't noticed any problems. The latest version is 7.1.28. Please give that a try.
