### ISSUE TITLE
scss performance tips

### ISSUE THREAD

**Issue by roberthenniger** [leafo/scssphp#594]
Hi. Are there any performance recommendation when compiling a lot of/nested code.
We have a tree structure with all the css components and render them over scssphp. 
Based on the loaded tree we check which mixin is responsible for this component and load it.

Now we see quite long processing times. We switched to use custom functions to get the tree structure which already helped to speed up the process and reduce memory usage over setVariables. 

Are there any hints / best practices to be used when dealign with nested mixins calls. Our resulting css code is round 1000lines so i would guess its not that much but still we see big performance impact when using mixins.

Thanks in advance for any tip on that issue.

**Comment by robocoder** [comment]
Please see if caching in the master branch improves performance for you.
