### ISSUE TITLE
Missing Formatter features for "Crunched"

### ISSUE THREAD

**Issue by Daijobou** [leafo/scssphp#598]
When I compile my scss with scssphp its 5KB greater than with https://sass-lang.com/
I found this difference for setFormatter('Leafo\ScssPhp\Formatter\Crunched'):

scssphp write
`.class > h1`
and sass write
`.class>h1`
without spaces between selectors https://www.w3.org/TR/CSS2/selector.html#child-selectors

Thats for all selectors; Descendant selectors, Child selectors or Adjacent sibling selectors

Maybe that should include in this formatter? Compiled with scssphp-0.7.5

**Comment by Cerdic** [comment]
Fix proposal in #689 
Not the best fix ever but efficient
