### ISSUE TITLE
Variables from inner override variables in parents

### ISSUE THREAD

**Issue by Daijobou** [leafo/scssphp#599]
scssphp version 0.7.6
Go to https://www.sassmeister.com select LibSass or DartSass or Sass 3.4.x or higher with this code
```
$width: 100px;
.test {
  $width: 200px;
  width: $width;
}
.test2 {
  width: $width;
}
```
Result
```
.test {
  width: 200px;
}
.test2 {
  width: 100px;
}
```

In scssphp its like older sass version 3.3.x and result is 
```
.test {
  width: 200px;
}
.test2 {
  width: 200px;
}
```
$width in scope .test{} override parent $width in root.

Coming here a version that working like sass version 3.4.x and higher or is here a setting for this?

**Comment by Cerdic** [comment]
This is now fixed, looks like since ae24fd0 is integrated

**Comment by robocoder** [comment]
Looks like it's still outputting ruby sass 3.3

**Comment by Cerdic** [comment]
@robocoder my bad, you're right, I read this issue in the wrong way!
