### ISSUE TITLE
PHP7 compatibility warning with Base64VLQEncoder.php 

### ISSUE THREAD

**Issue by sebastianwebb** [leafo/scssphp#600]
Hey, 

A user just reported a warning they're getting when running a PHP7 compatibility check:

> FILE: /plugins/microthemer/includes/scssphp/scssphp-july-2018/src/SourceMap/Base64VLQEncoder.php

> FOUND 3 ERRORS AFFECTING 1 LINE
> 179 | ERROR | Bitwise shifts by negative number will throw an ArithmeticError in PHP 7.0
> 179 | ERROR | Bitwise shifts by negative number will throw an ArithmeticError in PHP 7.0
> 179 | ERROR | Bitwise shifts by negative number will throw an ArithmeticError in PHP 7.0

I've read that this might be a false positive in a few places:

- https://wordpress.org/support/topic/php-7-1-compatibility-error-3/
- https://github.com/PHPCompatibility/PHPCompatibility/issues/294

But it would be nice if this library didn't generate false alarm. Can something be done to the following function to satisfy the compatibility checker?

```
public function zeroFill($a, $b)
{
        return ($a >= 0) ? ($a >> $b) : ($a >> $b) & (PHP_INT_MAX >> ($b - 1));
}
```

Thanks!
Sebastian

**Comment by robocoder** [comment]
I think this was addressed in the `wip/source-maps` branch.

**Comment by sebastianwebb** [comment]
Hey, thanks for replying.

As far as I can see there is [no equivalent file in that branch](https://github.com/leafo/scssphp/tree/wip/source-maps/src/SourceMap), which s 111 commits behind the master.

**Comment by robocoder** [comment]
What I meamt was making changes to switch from Base64VLQEncoder.php to Base64VLQ.php.

**Comment by sebastianwebb** [comment]
OK thanks for clarifying. For the potential benefit of anyone else dealing with this issue, can I just check that after adding the Base64VLQ.php file the only code changes will be:

This line:

`include_once __DIR__ . '/src/SourceMap/Base64VLQEncoder.php';`

To:

`include_once __DIR__ . '/src/SourceMap/Base64VLQ.php';`

And this line:

`$this->encoder = new Base64VLQEncoder(); `

To:

`$this->encoder = new Base64VLQ();`

Thanks,
Sebastian

**Comment by robocoder** [comment]
On the right track. Base64VLQEncoder has more public methods, so would need to check the dependencies.

**Comment by robocoder** [comment]
Doh. Looks like there's a bug in the Base64VLQ port that causes it to get stuck in an endless loop. I'll investigate it.

**Comment by sebastianwebb** [comment]
Ah, OK I'll hold off integrating for now. Thanks for your attention to this!

**Comment by sebastianwebb** [comment]
Thanks for sorting!
