### ISSUE TITLE
sass map and setVariables

### ISSUE THREAD

**Issue by Alexander-Slepchenko** [leafo/scssphp#605]
Is it possible to use a sass variable map through setVariables function? If possible, show me example?

**Comment by mistergraphx** [comment]
Hi,

as explain in the documentation the value must be a string in scss format

so you can write a map like this

```php
$settings = array(
  'header' => "(background:pink,
			height:2rem,
			)",
 'base-font-size'=> '1.5'
);

```

or using a php function to convert recursively a php array to a scss map string 

```php
function array2scssmap($p){
	if(is_array($p)){
		$map = '(';
		$i = 1;
		foreach($p as $key => $value){
			if(is_array($value))
				$value = array2scssmap($value);
			$map .= "$key: $value" ;
			if($i < count($p))
				$map .= ",";
			$i++;
		}
		$map .= ')';

		return $map;
	}
	return $p;
}
```

**Comment by Alexander-Slepchenko** [comment]
Hi, thanks for the answer, since no one answered for a long time, I had to write the function myself, based on the second part of the your answer.
