### ISSUE TITLE
Fatal Error

### ISSUE THREAD

**Issue by CallMarl** [leafo/scssphp#606]
I have encountered an error:

> Fatal error: Allowed memory size of 134217728 bytes exhausted (tried to allocate 147456 bytes) in C:\wamp\www\SCP\vendor\leafo\scssphp\src\Formatter.php on line 244

I juste want to report it.
Thank you

**Comment by willpower232** [comment]
If your SCSS file requires more than 1GB of memory to compile, your SCSS file is probably too big, too complex, or has a circular import

**Comment by CallMarl** [comment]
The error appened when i made an mistake in the scss script.

**Comment by robocoder** [comment]
@CallMarl : if you can paste a snippet here to reproduce, we'll see if we can mitigate the problem; otherwise, there isn't much to go on
