### ISSUE TITLE
proposal: move to org

### ISSUE THREAD

**Issue by DanielRuf** [leafo/scssphp#613]
As already outlined in https://github.com/leafo/scssphp/issues/376, it makes much sense to transfer this or fork it to an org account (easier collaboration, teams, rights / permission management, higher bus factor, ...).

**Comment by robocoder** [comment]
OK. I've created a new org

https://github.com/scssphp/scssphp is a copy rather than a fork, so it won't be affected if this repo gets nuked (e.g., DMCA'd).

Issues and PR's are still here until the move (gh-pages, travis, composer, packagist) is finalized.

**Comment by robocoder** [comment]
Done.
