### ISSUE TITLE
Named grid lines (proposal?)

### ISSUE THREAD

**Issue by gregamer** [leafo/scssphp#617]
Hi,

is there a way to use named grid lines, e.g. 
.grid{
grid-template-columns: [main-start] 1fr [content-start] 1fr [content-end] 1fr [main-end];
}

I was trying to make it work but so far no success. Is this supported? If not, is there a way to add it? It's a real life saver when more complicated grids are being used!

Thanks,
Grega

**Comment by Daijobou** [comment]
I have a issue with grid too in version 0.7.8. :(

> parse error: failed at `grid: [row1-start] "image header header" 150px [row1-end] `
