### ISSUE TITLE
parse error: failed at `$self: &amp

### ISSUE THREAD

**Issue by l2a** [leafo/scssphp#620]
when I compile I have this error:

Leafo\ScssPhp\Exception\ParserException</em>: parse error: failed at `$self: &amp;;` themes/custom/boots/src/sass/layout/_header.scss on line 56 in <em class="placeholder">Leafo\ScssPhp\Parser-&gt;throwParseError()</em> (line <em class="placeholder">128</em> of <em class="placeholder">/app/vendor/leafo/scssphp/src/Parser.php</em>).

is there any patch for this?
Thanks,

**Comment by Colir** [comment]
+1

**Comment by Cerdic** [comment]
Can you check if there is still an error in the last version? 
In this case can you provide the part of scss code that allow to reproduce?

**Comment by Cerdic** [comment]
OK, can reproduce:
```
.test {
	$s: &;
	content: #{$s};
}
```

produce

```
Fatal error: Uncaught Leafo\ScssPhp\Exception\ParserException: parse error: failed at `$s: &;` t1b.scss on line 2 in /Users/cedric/Sites/scssphp/src/Parser.php:128
Stack trace:
#0 /Users/cedric/Sites/scssphp/src/Parser.php(169): Leafo\ScssPhp\Parser->throwParseError()
#1 /Users/cedric/Sites/scssphp/src/Compiler.php(199): Leafo\ScssPhp\Parser->parse('.test {\n\t$s: &;...')
#2 /Users/cedric/Sites/scssphp/bin/pscss(211): Leafo\ScssPhp\Compiler->compile('.test {\n\t$s: &;...', 't1b.scss')
#3 {main}
  thrown in /Users/cedric/Sites/scssphp/src/Parser.php on line 128
```

where as
```
.test {
	$s: #{&};
	content: #{$s};
}
```

doesn't fail in the parsing but in the compilation

**Comment by Cerdic** [comment]
#652 is fixing this issue

**Comment by Cerdic** [comment]
This is fixed now, can be closed @robocoder
