### ISSUE TITLE
Skip specific imports

### ISSUE THREAD

**Issue by RdeWilde** [leafo/scssphp#621]
Is it possible to skip certain imports?

For example I have the bootstrap lib locally installed and imported to get auto-completion to work, but in production the actual file is served from CDN. Is there any way to exclude the complete bootstrap lib, but keep my custom code compiling?

**Comment by cyberalien** [comment]
I was looking for similar issue, found a solution.

Extend compiler class, override function findImport(). If parameter matches file you want to skip, return null (then you get to keep import statement in output) or replace with dummy file (then import will not be in output).
