### ISSUE TITLE
Dublicate merge params

### ISSUE THREAD

**Issue by Highter87** [leafo/scssphp#623]
I propose to make an association of this kind:
> a { font-weight:bold }
> a { color:#fff }

to

> a { font-weight:bold; color:#fff }

and this code:

> a { font-weight:bold; font-weight:bold }

to

> a { font-weight:bold }

**Comment by Cerdic** [comment]
IMHO this is not the role of this compiler as this is a complete different job that can introduce bugs.
If you want to optimize the final CSS you could have a look to CSSTidy https://github.com/Cerdic/CSSTidy/ :)

**Comment by robocoder** [comment]
Ruby sass doesn't optimize this either, and I would prefer we not add more complexity while we strive to improve compatibility and performance.
