### ISSUE TITLE
Is this project still maintained?

### ISSUE THREAD

**Issue by glOOmyART** [leafo/scssphp#624]
I wonder if this project is still maintained by anyone?
There are issues and merge requests open older than a year ago...

An if it's dead, is there an actively maintained alternative to render/compile SCSS in PHP?

**Comment by robocoder** [comment]
Anyone wishing to volunteer to maintain this project should contact leafo. I don't have admin privileges.

Anyone is welcome to fork the project.

As for the open issues, many are symptoms of other issues and/or lack small enough test cases.

Some of the older PRs are open for reference or of community interest, but will never be merged. Others introduce regressions, conflict with coding standards, etc., and thus, require more time to review.

**Comment by glOOmyART** [comment]
ah i see ;)
thanks for clearing this up...
