### ISSUE TITLE
Try to set a acf php variable into scssphp

### ISSUE THREAD

**Issue by birman91** [leafo/scssphp#625]
Please can u tell me what I'm doing wrong=(

```
<?php header('content-type: text/css');
require_once 'scssphp-0.7.6/scss.inc.php';
use Leafo\ScssPhp\Compiler;
$scss = new Compiler();
echo $scss->compile('
	$body-color:  . the_field("background_color", "option") . ;;
	body{
	background-color: $body-color;
	}
	
')
```

**Comment by vita10gy** [comment]
The error would help, but at the *very* least it looks like it needs to be 

`<?php header('content-type: text/css');
require_once 'scssphp-0.7.6/scss.inc.php';
use Leafo\ScssPhp\Compiler;
$scss = new Compiler();
echo $scss->compile('
	$body-color:'  . the_field("background_color", "option") . ';
	body{
	background-color: $body-color;
	}
	
')`

Assuming the_field() is a function that code can actually call and get a color back.

**Comment by birman91** [comment]
the error is: net::ERR_ABORTED 500 (Internal Server Error)

and if i try 
`echo (the_field("background_color", "option").';');`

I got the hexcode #c614c9; printed in the frontend

**Comment by birman91** [comment]
ah ok i think the problem is by acf.
if i do something like that:
```
echo (
	        '$body-color'. the_field("background_color", "option")

    );
```
the output is #c614c9$body-color

**Comment by vita10gy** [comment]
Well that doesn't make a ton of sense. Either way it looks like your question/issue isn't really with scssphp though. I'd suggest closing this.

**Comment by birman91** [comment]
ok thx...
