### ISSUE TITLE
export to styles.css 

### ISSUE THREAD

**Issue by birman91** [leafo/scssphp#628]
Hello, 
I made something like that to test and it works great=)

```
require_once 'scssphp-0.7.6/scss.inc.php';
	use Leafo\ScssPhp\Compiler;
	$scss = new Compiler();

	$test = '$body-color: '.get_field("background_color", "option") . '; body { background-color: lighten( $body-color, 30% ); }';
	echo $scss->compile($test);
```

Is there a way to export the compiled script to my style.css file?
And what have I to do?
I hope you can help me,
thank you so much.

**Comment by GrupoWebex** [comment]
Just write content on file
```
$test` = '$body-color: '.get_field("background_color", "option") . '; body { background-color: lighten( $body-color, 30% ); }';
$content = $scss->compile($test);
$path = '/myfolder/';
file_put_contents($path .'/style.css', $content);
```

**Comment by birman91** [comment]
I tried it like u said.

```
require_once 'scssphp-0.7.6/scss.inc.php';
	    use Leafo\ScssPhp\Compiler;
	    $scss = new Compiler();

	    $test = '$body-color: '.get_field("background_color", "option") . '; body { background-color: lighten( $body-color, 30% ); }';
	    $content = $scss->compile($test);
	    $path = get_template_directory();
	    file_put_contents($path .'/style.css', $content);
```

But it doesn't work=( am I doing anything wrong?

**Comment by GrupoWebex** [comment]
Common problem is when folder has wrong permission. 
Check you have write permission on folder, like 755.
Some output error?

**Comment by birman91** [comment]
no there is no error. 
I wrote the code inside the functions.php of a wordpress theme.
```
require_once 'scssphp-0.7.6/scss.inc.php';
	    use Leafo\ScssPhp\Compiler;
	    $scss = new Compiler();

	    $test = '$body-color: '.get_field("background_color", "option") . '; body { background-color: lighten( $body-color, 30% ); }';
	    $content = $scss->compile($test);
	    $path = get_template_directory();
	    file_put_contents($path .'/style.css', $content);
```
the style.css is in the same folder like my function.php

C:\Users\Julian\Desktop\wordpress\wp-content\themes\Birdman\style.css
C:\Users\Julian\Desktop\wordpress\wp-content\themes\Birdman\style.php

 get_template_directory() is the hook of my absolute path...

so if I do something like that` echo( get_template_directory());`
the output is: C:\Users\Julian\Desktop\wordpress/wp-content/themes/Birdman

**Comment by GrupoWebex** [comment]
Something is wrong here. Force display errors or check server config:
```
error_reporting(E_ALL);
ini_set('display_errors', 1);
```
Check write permission on FOLDER.

**Comment by birman91** [comment]
ok.... new try=)
Sry for taking ur time=P

I made a new Projekt the Name of the Projekt directory is: scssphp_test
this directory is on my Desktop an gets load by Mamp.

Inside this directory there are three files now.
1. index.php  with a content of  `<link rel="stylesheet" type="text/css" href="style.css">`
2. style.css which is empty
3. my style.php with a content of
```
 <?php
	require_once 'scssphp-0.7.6/scss.inc.php';
	use Leafo\ScssPhp\Compiler;
	$scss = new Compiler();

	$test = '$body-color: green; body { background-color: lighten( $body-color, 30% ); }';
	$content = $scss->compile($test);
	file_put_contents('style.css', $content);
```
Now my style.css get load but now export from the style.php to the style.css happened=/

Thank u so much for helping me... I hope now we get it to run...=)

**Comment by GrupoWebex** [comment]
Was a simple tip, so dont worry.
Now you should make a styles.scss with sass content and...
```
$test = file_get_contents('style.scss');
$content = $scss->compile($test);
```
Best method is working with a cache system which can helps you to regenerate styles.css when styles.scss is modified.
Have a nice programming day, :)
