### ISSUE TITLE
@at-root and & not working when used together

### ISSUE THREAD

**Issue by lesleyfernandes** [leafo/scssphp#630]
I tested this on the version 0.7.7 and dev (master) and the issue is happening in both of them. 

I have a code like this one:
```
.block-featured {
  @at-root {
    .col-flex-same-height &{
      height: 100%;
    }
  }
}

```
And I am getting this: 
```
.col-flex-same-height {
  height: 100%;
}

```
Instead of this (when using another compiler):
```
.col-flex-same-height .block-featured {
  height: 100%;
}
```

**Comment by nagyleventeimre** [comment]
same issue with 
`.class-name {
    color: blue;
    @at-root {
        .parent &{
            color: red;
        }
    }
}`

it should be 
`.class-name {
  color: blue;
}
.parent .class-name {
  color: red;
}`

**Comment by cyberalien** [comment]
I think its ruby sass bug, not php sass bug.

@at-root is not meant to be used with &. & represents parent selector, @at-root excludes parent selectors, so combining them doesn't make any sense. Yet it works by using only last selector.

Such usage is not in sass documentation. If using @at-root with & was intentional, it would be there.

If you want to achieve that result, simply remove @at-root from your code. You are using it wrong.

**Comment by lesleyfernandes** [comment]
@cyberalien, we used it before using ruby and other tools, and it worked:
https://gist.github.com/lesleyfernandes/5e7cd4af8ee5f547dcdf25a508365352

I tested here using SassMeister and Codepen, and it is also working there.

**Comment by cyberalien** [comment]
Yes, it works, but it doesn't mean syntax is correct.

That syntax doesn't make any sense - you are mixing 2 things that contradict each other: one that adds parent selectors, one that removes parent selectors. Remove at-root from your code and it will work as expected.

**Comment by nagyleventeimre** [comment]
Here is my example the #{$} and $ makes difference
`.article_notice{
    font-family:Arial;
    padding: 15px;
    margin:10px auto;
    max-width:200px;
    background:#f6f6f6;
    text-align:center;
    &:before{
        content: "!!!";
        margin-right: 5px;
    }
    @at-root .old #{&}{
        color:red;
    }
    @at-root .new #{&}{
        color:green;

   @at-root .long #{&}{
        color:blue;
    }
} 
`

**Comment by cyberalien** [comment]
I assume you forgot } at the end because otherwise code is broken.

Replace #{&} with & and remove at-root to get same result.

**Comment by lesleyfernandes** [comment]
`.block-featured {
 //Some CSS code and then:
  @at-root {
    .col-flex-same-height &{
      height: 100%;
    }
  }
}
`
Are you suggest to remove at-root and paste the code outside of my hierarchy to get the same result, right? There are two reasons why I was not doing that, one is to preserve the context inside the code structure that could have 1, 2, 3 or more levels, and the other one is not to have to repeat the selector.  I can not use & because it won't be inside the hierarchy anymore, otherwise it is going to be .block-featured 

I can not type .col-flex-same-height **.block-featured .col-flex-same-height .block-featured** and not **.col-flex-same-height .block-featured**.

**Comment by cyberalien** [comment]
No, remove only at-root from that code. You are using it incorrectly by adding & after it.
```
@at-root { .col-flex-same-height & {
```
is identical (with exception of adding another { and } ) to
```
.col-flex-same-height &
```

See https://sass-lang.com/documentation/file.SASS_REFERENCE.html#at-root

> The @at-root directive causes one or more rules to be emitted at the root of the document, rather than being nested beneath their parent selectors.

That's what at-root is for. It should not be used with & in same selector. You are using it incorrectly.

**Comment by lesleyfernandes** [comment]
Yes, you are right, we were using incorrectly here. For us, if we type .someclass & inside in a hierarchy is going to be like `.parent-class .someclass .parent-class` . That is why we were using ` @at-root`  not to print that first ` .parent-class` . 

Thank you.
