### ISSUE TITLE
support for color format #1f2526bf

### ISSUE THREAD

**Issue by charlymz** [leafo/scssphp#632]
If i compile this color #1f2526bf it separates the alpha channel like this #1f2526 bf creating an invalid color

**Comment by ange007** [comment]
Hi.
Maybe it looks like my problem: https://github.com/leafo/scssphp/issues/631 ?

**Comment by robocoder** [comment]
Yeah, scssphp hasn't kept up with all the standards updates. This one is still unofficial though.

https://caniuse.com/#feat=css-rrggbbaa

I'll add support but scssphp will output it using rgba() syntax.
