### ISSUE TITLE
Parse error: failed at `&} in bootstrap 4.3

### ISSUE THREAD

**Issue by padaliyajay** [leafo/scssphp#637]
Getting this error while compiling bootstrap 4.3. can you please fix it?
`Parse error: failed at &}`

Bootstrap 4 scss code

```
@mixin badge-variant($bg) {
  color: color-yiq($bg);
  background-color: $bg;

  @at-root a#{&} {
    @include hover-focus {
      color: color-yiq($bg);
      background-color: darken($bg, 10%);
    }

    &:focus,
    &.focus {
      outline: 0;
      box-shadow: 0 0 0 $badge-focus-width rgba($bg, .5);
    }
  }
}
```

**Comment by dleffler** [comment]
Looks like a duplicate of Issue #616

**Comment by padaliyajay** [comment]
Fixed By Modifying bootstrap code

Replace `@at-root a#{&}` to `&[href]` in following files

bootstrap4/mixins/_badge.scss
bootstrap4/_badge.scss

**Comment by robocoder** [comment]
Closing as a dupe of #616
