### ISSUE TITLE
Please update packagist :)

### ISSUE THREAD

**Issue by leonardfischer** [leafo/scssphp#649]
Hey there,

thanks a lot for the new version!
Just a small reminder: could you update packagist with the newest version? I'd like to use it but don't want to wait a week for the packagist crawler or rely on `dev-master` ;) Also you could implement a webhook, so the new versions get published immediately.

Best regards!

**Comment by Cerdic** [comment]
My guess is that the packagist project is frozen since some "recent" webhook deactivation by github. 

@leafo has to connect on his account and update it by linking it with his github account to have things work again

**Comment by cedric-anne** [comment]
Hi,

Here is a workaround to get latest releases.

First, add the github repository in composer config: `composer config repositories.leafo/scssphp vcs https://github.com/leafo/scssphp`.
Then, update the package: `composer update leafo/scssphp`.

That will prevent you to get a dev branch and so will be compatible to usage of `"minimum-stability": "stable"` composer configuration.

Regards

**Comment by mhavelka** [comment]
@Cerdic Hi is this really depended on the @leafo exclusively? I see no commit or comments from him since 2013, so is this package doomed to be not updated in packagist forever? Or are there some other ways?

Thanks a lot.

**Comment by Cerdic** [comment]
As the project is on the @leafo account it is needed that he connect to Packagist to update the connexion between his packagist account and his github account. 
There is nothing that @robocoder or I can do.

The lack of answer of @leafo is indeed pushing some wondering about #613 
(we have same problem with Travis project which is frozen also) but moving the project would have a lot more implications.

The better would really be that @leafo can unlock the situation here. I think he could gave some admin right to someone else as well on Packagist and Travis.

**Comment by AdamPerkins** [comment]
The last time @leafo was working on this project was 2013:
https://github.com/leafo/scssphp/graphs/contributors

So it seems he lost interest or has no time anymore. I vote to fork the project into a new one and give proper admin rights to the active maintainers.

**Comment by vita10gy** [comment]
Unless I really have a case of the Fridays, I think this seems to have happened. 

https://packagist.org/packages/leafo/scssphp

**Comment by Cerdic** [comment]
Wonderful!

**Comment by Cerdic** [comment]
Looks like the webhook was not updated (or the Packagist account linked to the github account to use the Github API) because de `0.8.3` version is not on https://packagist.org/packages/leafo/scssphp

**Comment by robocoder** [comment]
Leaving this open for visitors.

Development has moved to https://github.com/scssphp/scssphp. New org, new namespace, new package name (due to vendor namespace change). Travis-CI and Packagist webhooks updated.
