### ISSUE TITLE
v0.7.8 not yet available on Packagist?

### ISSUE THREAD

**Issue by Narno** [leafo/scssphp#654]
Hello, there is a reason why the last version, v0.7.8, is not yet available on Packagist? https://packagist.org/packages/leafo/scssphp

Thanks for your good job! 👍

**Comment by cyberalien** [comment]
Yes, see https://github.com/leafo/scssphp/issues/649

**Comment by Narno** [comment]
Arg sorry, thanks a lot @cyberalien!
