### ISSUE TITLE
BS4 @support repeating selector class - minor issue

### ISSUE THREAD

**Issue by STV11C** [leafo/scssphp#659]
Hi guys, well done on v0.8!
A small issue I noticed is the BS4 sticky top repeats the selector class instead of being in one class. It still works and is technically correct, but thought to mention it if it can be fixed.
Cheers, Stephan

```
@supports (position: sticky) {
    .sticky-top {
      position: sticky; }
    .sticky-top {
      top: 0; }
    .sticky-top {
      z-index: 1020; } }
```

**Comment by Cerdic** [comment]
I saw that and didn't dig, mea culpa.

The source code is producing the bug is:
```
.sticky-top {
  @supports (position: sticky) {
    position: sticky;
    top: 0;
    z-index: $zindex-sticky;
  }
}
```

Looks like I hadn't the best fix in 01ec539b3bdbf91bc5b78ffb783e42fda4826b24
