### ISSUE TITLE
@extends doesn't add :not(

### ISSUE THREAD

**Issue by STV11C** [leafo/scssphp#660]
Hi guys, I've noticed that v0.8 does not include **:not(** when using @extend.

**Simple test case:**
```
.comment-list {
  .comment {
    @extend .card;
  }
}
```
**compiles to:**
`.comment-list .accordion > .comment:not(:first-of-type):last-of-type)`
**instead of:**
`.comment-list .accordion > .comment:not(:first-of-type):not(:last-of-type)`

Note that it does the same thing on all my other @extends where it loses the **:not(** part.

Hopefully it's an easy fix. Cheers

**Comment by Cerdic** [comment]
the extend compilation is merging `:not(`, I got this bug today also!

Simple test case :
```
.class1:not(:last-child) {
	color:red;
}

.class2:not(.btn-link) {
	@extend .class1;
}

.class3:not(:last-child) {
	@extend .class1;
}
```

Expected:
```
.class1:not(:last-child), .class2:not(.btn-link):not(:last-child), .class3:not(:last-child) {
  color: red; }
```

Result :
```
.class1:not(:last-child), .class2:not(.btn-link):last-child), .class3:not(:last-child) {
  color: red; }
```
