### ISSUE TITLE
Always have (stdin) in source map

### ISSUE THREAD

**Issue by AdamPerkins** [leafo/scssphp#677]
I'm using master branch.

Whatever I do I have this kind of source map (here's a minimal example):
``{"version":3,"file":"cms.css","sourceRoot":"/","sources":["(stdin)"],"names":[],"mappings":"AAAA"}``

Instead of the name of _"cms.scss"_ (in my case) there is _"(stdin)"_

This is the simple cms.css:
``h1 {
  color: blue;
}
/*# sourceMappingURL=cms.css.map */``

The compiler works fine even in complex situations with importing Bootstrap framework. The generated css is well. 

Having a short look into the code I have seen that the word _(stdin)_ comes from the constructor of the parser class which is called by the compile function.

Don't know what I have to change or if it's a bug.

**Comment by robocoder** [comment]
What source map options are you using?

Reference: https://github.com/leafo/scssphp/wiki/Source-Maps

**Comment by Der-Alex** [comment]
Hi. I have the same issue with creating source maps. tried the SOURE_MAP_INLINE and the SOURCE_MAP_FILE option.

**Comment by airelibre** [comment]
Same here with options:
- sourceMapWriteTo
- sourceMapURL
- sourceMapBasepath
- sourceMapRootpath
- sourceRoot

But if I call $preprocessor->compile($scss, '/'); (with the second param), no more error - I just then get two times the base "path" in the sourcemap.map file:
{"version":3,"sourceRoot":"/","sources":["subdir/www/","subdir/www/","subdir/www/assets/themes/MyTheme/scss/foundation/vendor/normalize.scss" ...
