### ISSUE TITLE
Proposal (and bug): Update minimum PHP version to 5.6

### ISSUE THREAD

**Issue by timelsass** [leafo/scssphp#679]
Recent changes introduced a couple of areas that use class name resolution via $className::class.  This [feature was added in 5.5](https://php.net/manual/en/migration55.new-features.php#migration55.new-features.class-name), so 5.4 installs are impacted.

found in:
https://github.com/leafo/scssphp/blob/master/src/Compiler.php#L1493
https://github.com/leafo/scssphp/blob/master/src/Compiler.php#L2141

I'd suggest bumping to a minimum of 5.6 to start the process of making php 7 the minimum eventually

**Comment by robocoder** [comment]
That was an unintentional compat buster. =P

**Comment by robocoder** [comment]
Fixed in v0.8.2

**Comment by timelsass** [comment]
thanks ! :)

**Comment by mahagr** [comment]
@robocoder Which release is the last one to work with PHP 5.4?

**Comment by mahagr** [comment]
Answering to my own question: last version working with PHP 5.4 is scssphp 0.8.0

**Comment by robocoder** [comment]
If you run composer with `--ignore-platform-reqs`, I believe 1.0 will still work with PHP 5.4.

**Comment by mahagr** [comment]
It will not because of `::class` call which is PHP 5.5 only feature.

**Comment by mahagr** [comment]
Here are the correct links:
https://github.com/leafo/scssphp/blob/v0.8.1/src/Compiler.php#L1493
https://github.com/leafo/scssphp/blob/v0.8.1/src/Compiler.php#L2141
