### ISSUE TITLE
Is the server class deprecated?

### ISSUE THREAD

**Issue by alexsaalberg049** [leafo/scssphp#699]
I've successfully installed `scssphp` via `composer`, but I don't understand how it's actually intended to be used.

I want to be able to simply use my `.scss` files as `.css` files in my `.php` files. 

After my first reading through the docs I tried to use the "example `server` class" to have them compiled into `.css` files on demand and then include said files via `<link href="scss/file.css" rel="stylesheet" type="text/css">`. Where `/scss` is the folder containing all the `.scss` files.

Reading through the documentation again, and [looking](https://github.com/leafo/scssphp/issues/333) [through ](https://github.com/leafo/scssphp/issues/452) [older](https://github.com/leafo/scssphp/issues/524) [issues](https://github.com/leafo/scssphp/issues/30), it seems like the `server` class (and the library as a whole) has changed pretty significantly throughout the years. 

Currently, it seems like it isn't *really* a part of the library, but simply an example of what *could* be built using the library.

<br>

Here's my question:

**Is the `server` class intended to be used at all?**

Thanks!

**Comment by robocoder** [comment]
My guess is that the Server class still works but I haven't tested it in a long while. The reason it was moved to an example is that there's a ton of things that can affect behaviour if the webserver and/or php is configured differently from what the developers use; as such, it's quite the support headache.
