### ISSUE TITLE
Fails to generate correct .css in nested @each loop.

### ISSUE THREAD

**Issue by alexsaalberg049** [leafo/scssphp#705]
scssphp version `0.8.2`

**Description:**
It's a pretty simple issue to describe: `scssphp` does not process the `.scss` file correctly.

It should generate the file shown in `3`, but simply does not generate any of the `.bg-{COLOR}-{NUMBER}` rules it should be in that inner `@each` loop. 

It's possible that there's something quirky about my environment, so someone else should probably confirm the issue exists with their `scssphp` aswell.

**Relevant Stuff:**
1. [Source `.scss` File](https://gist.github.com/alexsaalberg049/edf0ee658d25796fe77958a77572d7f3)
2. [Resulting `.css` File](https://gist.github.com/alexsaalberg049/7adca254151f1b5537b4b55198a8f062)
3. [Online SCSS tool showing proper `.css` file](https://www.sassmeister.com/gist/3db61918a12112d4cc625f8915b629ac)

**Other**
- [Open Color source files](https://github.com/yeun/open-color/releases/download/v1.6.3/open-color.zip)

**Comment by robocoder** [comment]
Reproduceable in v0.8.3 and master (2e5e474b).

**Comment by robocoder** [comment]
Looks like `@each` doesn't work at the root level.

**Comment by robocoder** [comment]
(Comment deleted)

Looks like it's the nested map that's the source of grief.

**Comment by robocoder** [comment]
It doesn't like maps where the key is a list. Flipping the key/value is the workaround, e.g.,
```
$oc-gray-list: (
        "0": #f8f9fa,
        "1": #f1f3f5
);

$oc-red-list: (
        "0": #fff5f5,
        "1": #ffe3e3
);

$oc-color-list: (
    "gray": $oc-gray-list,
    "red": $oc-red-list
);

@each $color-name, $color-list in $oc-color-list {
  @each $color-index, $color in $color-list {
    .bg-#{$color-name}-#{$color-index} {
      background-color: $color;
    }
  }
}
```

**Comment by Cerdic** [comment]
This is now fix: see https://github.com/scssphp/scssphp/issues/3
