### ISSUE TITLE
Using @extend creates invalid output with nested classnames in some cases in 0.7.5

### ISSUE THREAD

**Issue by bmbrands** [leafo/scssphp#712]
Compiling this scss:

```
.btn-block {
  + .btn-block {
    margin-top: 1.5rem;
  }
}
.a {
    .b {
        @extend .btn-block;
        margin: auto;
    }
}
```

generates this css

```
.btn-block + .btn-blocks, .a .b + .btn-blocks {
  margin-top: 1.5rem; }
```
Which is not valid because of a selector ending with +

I know this is not the way @extend is advised to be used. I just want to report it as the issue did not exist in earlier versions of scssphp.

**Comment by robocoder** [comment]
This repo is no longer maintained.

You should open an issue at https://github.com/scssphp/scssphp/issues
