### ISSUE TITLE
@import just imports one file

### ISSUE THREAD

**Issue by patriceckhart** [leafo/scssphp#713]
In my package "neosrulez/scssparser" I use "leafo/scssphp". 
In the main scss file I'm doing @import. It works. But only with one file. In the next line, after the main file I use another @import. But this file is ignored. All others too.

The main scss looks like this. test.scss is ignored:
```
@import "resource://NeosRulez.Bootstrap/Private/Styles/bootstrap";
@import "resource://NeosRulez.Bootstrap/Private/Styles/test.scss";
```

**Comment by robocoder** [comment]
Double check your 2nd line of main.scss actually ends with a semi-colon.
