### ISSUE TITLE
Attempted to load class "Compiler" from namespace "Leafo\ScssPhp".

### ISSUE THREAD

**Issue by abelardolg** [leafo/scssphp#715]
Hi there,

I am using the package:
` "scssphp/scssphp": "^1.0.6"`

but this message outputs:
```
Attempted to load class "Compiler" from namespace "Leafo\ScssPhp".           
  Did you forget a "use" statement for e.g. "Twig_Compiler", "Twig\Compiler",  
   "Symfony\Component\ExpressionLanguage\Compiler", "Symfony\Component\Depend  
  encyInjection\Compiler\Compiler" or "ScssPhp\ScssPhp\Compiler"?  
```

I deleted cache (composer, directory) but it happens each time I run 

`composer install`

Last version of Ubuntu.
PHP 7.2.24-0ubuntu0.18.04.2 (cli) (built: Jan 13 2020 18:39:59) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.2.24-0ubuntu0.18.04.2, Copyright (c) 1999-2018, by Zend Technologies

**Comment by mahagr** [comment]
You're in the wrong repository, go to https://github.com/scssphp/scssphp

**Comment by mahagr** [comment]
Also delete vendor folder and make sure you don't have leafo/scssphp in your dependencies.

**Comment by abelardolg** [comment]
Yes, I deleted that dir and this dependency is never referenced. 

Move to another repo. Thanks.: )
